RavenDB-14332 Allow to filter index that has errors
ravendb/ravendb pull request #10013
Opened 2020-01-02 11:29 UTC by Danielle9897

2020-01-02 12:51 UTC, grisha-kotler approved these changes

2020-01-03 08:13 UTC, ml054 requested changes
The one thing that bothers me is we use word error in multiple meaning so it might be confusing for user. 
Index might have error state (so indexing is paused) or .. index can have *indexing errors*.

So instead of splitting normal status, I would put subsection under normal with extra toggle. It should control we should be show all indexes with normal status or with normal status but *indexing errors* count > 0

2020-01-03 08:18 UTC, ml054 commented
```
- Normal     (toggle - on by default) 
  - with indexing errors only  (toggle - off by default)
```

2020-01-05 16:20 UTC, Danielle9897 commented
https://issues.hibernatingrhinos.com/issue/RavenDB-14332#focus=streamItem-67-43581.0-0

2020-01-07 13:01 UTC, ml054 approved these changes

2020-01-07 13:01 UTC, merged