RavenDB-14590 : Include timeseries should modify the document etag
ravendb/ravendb pull request #10210
Opened 2020-02-16 16:32 UTC by aviv86

https://issues.hibernatingrhinos.com/issue/RavenDB-14590

2020-02-17 09:59 UTC, ayende requested changes

2020-02-17 09:59 UTC, ayende commented on src/Raven.Server/Documents/Includes/IncludeTimeSeriesCommand.cs
> +            var hc = new HashCode();
I wonder if we shouldn't also use `ComputeHttpEtags` here, instead.

2020-02-17 10:07 UTC, ppekrol approved these changes

2020-02-19 07:29 UTC, ayende approved these changes

2020-02-19 08:13 UTC, merged