RavenDB-14614: add retention time for IoMetrics
ravendb/ravendb pull request #10357
Opened 2020-03-19 13:17 UTC by garayx

2020-03-19 13:46 UTC, grisha-kotler requested changes

2020-03-19 13:46 UTC, grisha-kotler commented on src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
> +        public int IoMetricsCleanTimeInterval { get; set; }
```suggestion
        public TimeSetting IoMetricsCleanTimeInterval { get; set; }
```

2020-03-19 13:46 UTC, grisha-kotler commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +        public DateTime IoMetricsCleanTime => new DateTime(_ioMetricsCleanerTicks);
This isn't being used?

2020-03-19 13:46 UTC, grisha-kotler commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +            _ioMetricsCleanerTicks = DateTime.UtcNow.AddHours(Configuration.Databases.IoMetricsCleanTimeInterval).Ticks;
Save the `_lastMetriceCleanerRun` in `DateTime` format

2020-03-19 13:51 UTC, garayx commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +        public DateTime IoMetricsCleanTime => new DateTime(_ioMetricsCleanerTicks);
no, will delete it

2020-03-19 14:49 UTC, grisha-kotler commented on src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
> +        [DefaultValue(4)]
Missing `[TimeUnit(TimeUnit.Hours)]`
Let's make it 24 hours by default

2020-03-19 19:02 UTC, grisha-kotler approved these changes

2020-03-20 08:26 UTC, ppekrol commented on src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
> +        public TimeSetting IoMetricsCleanTimeInterval { get; set; }
Should go to `StorageConfiguration` IMO
and key should be `Storage.IoMetricsCleanupIntervalInHrs`

2020-03-20 08:26 UTC, ppekrol commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +        private DateTime _ioMetricsCleanerRun;
Rename to: `_nextIoMetricsCleanupTime`

2020-03-20 08:26 UTC, ppekrol commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +                    var msg = ranIoMetricsCleaner ? " with IO Metrics Cleaner" : string.Empty;
Why is this so important?

2020-03-20 08:26 UTC, ppekrol commented on src/Raven.Server/Config/Categories/DatabaseConfiguration.cs
> +        [Description("Retention time (in hours) for IO Metrics data")]
`Time (in hours) between IO Metrics cleanup`

2020-03-20 08:26 UTC, ppekrol commented on src/Raven.Server/Utils/IoMetrics/IoMetricsUtil.cs
> +        public static void CleanIoMetrics(IEnumerable<StorageEnvironmentWithType> environments, long ioMetricsCleanerTicks)
Rename `ioMetricsCleanerTicks` to `untilTicks`

2020-03-20 10:12 UTC, garayx commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +                    var msg = ranIoMetricsCleaner ? " with IO Metrics Cleaner" : string.Empty;
removed

2020-03-20 10:27 UTC, ppekrol commented on src/Raven.Server/Config/Categories/StorageConfiguration.cs
> +        public TimeSetting IoMetricsCleanupIntervalInHrs { get; set; }
property does not have to have 'InHrs' in contract to configuration key. It is a TimeSetting with TimeSpan value

2020-03-20 11:27 UTC, ppekrol commented on src/Raven.Server/Config/Categories/StorageConfiguration.cs
> +        public TimeSetting IoMetricsCleanupIntervalInHrs { get; set; }
Done

2020-03-20 11:27 UTC, ppekrol approved these changes

2020-03-20 17:50 UTC, merged