RavenDB-5244 V4.0 New client : implement LoadStartingWith
ravendb/ravendb pull request #1043
Opened 2016-12-07 10:05 UTC by iftahbe

- Move transformers logic to helper class (shared between several operations)
- Fix LoadStartingWith to be case insensitive
- Fix parsing of strings from $values array
- Fix DocumentHandler in case of LoadStartingWith
- Enable skipped tests

2016-12-07 11:22 UTC, ayende commented
Failing test
```
  SlowTests.MailingList.LoadAllStartingWith.LoadAllStartingWithShouldNotLoadDeletedDocs [FAIL]
    System.InvalidCastException : Unable to cast object of type 'Raven.Json.Linq.RavenJObject' to type 'Raven.Json.Linq.RavenJArray'.
    Stack Trace:
      C:\Work\ravendb-4.0\src\Raven.Client\Document\Batches\LazyStartsWithOperation.cs(90,0): at Raven.Client.Document.Batches.LazyStartsWithOperation`1.HandleResponse(GetResponse response)
      C:\Work\ravendb-4.0\src\Raven.Client\Document\DocumentSession.cs(991,0): at Raven.Client.Document.DocumentSession.ExecuteLazyOperationsSingleStep(ResponseTimeInformation responseTimeInformation)
      C:\Work\ravendb-4.0\src\Raven.Client\Document\DocumentSession.cs(943,0): at Raven.Client.Document.DocumentSession.ExecuteAllPendingLazyOperations()
      C:\Work\ravendb-4.0\src\Raven.Client\Document\DocumentSession.cs(879,0): at Raven.Client.Document.DocumentSession.<>c__DisplayClass73_0`1.<AddLazyOperation>b__0()
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.LazyInitValue()
      C:\Work\ravendb-4.0\test\SlowTests\MailingList\LoadAllStartingWith.cs(45,0): at SlowTests.MailingList.LoadAllStartingWith.LoadAllStartingWithShouldNotLoadDeletedDocs()
```

2016-12-07 21:33 UTC, ayende requested changes

2016-12-07 21:33 UTC, ayende commented on src/Raven.Server/Documents/Handlers/DocumentHandler.cs
> +                if (HttpContext.Request.Query.ContainsKey("ComingFromMultiGet") == false)
W.A. ? 

Why are you doing something like that? Why is there different behavior between the clients?

2016-12-08 07:31 UTC, iftahbe commented on src/Raven.Server/Documents/Handlers/DocumentHandler.cs
> +                if (HttpContext.Request.Query.ContainsKey("ComingFromMultiGet") == false)
When requestring Lazily.LoadStartingWith in the old client, it's being sent as part of a multi-get (Post) operation, then the multi-get handler redirects it to the normal document handler (Get) and the request looks exactly (!) like a request from the new client but the result is in a different structure (object vs array). I needed a way to tell between them

2016-12-08 07:35 UTC, ayende commented on src/Raven.Server/Documents/Handlers/DocumentHandler.cs
> +                if (HttpContext.Request.Query.ContainsKey("ComingFromMultiGet") == false)
Don't do it like that, change the old client to support the new way.
I don't want to have this kind of stuff in our codebase if we can avoid it, and we can do that if we change both.

2016-12-08 07:39 UTC, iftahbe commented on src/Raven.Server/Documents/Handlers/DocumentHandler.cs
> +                if (HttpContext.Request.Query.ContainsKey("ComingFromMultiGet") == false)
I mean it looks exactly like a request from LoadStartingWith in the new client

2016-12-08 09:38 UTC, merged

2016-12-09 07:43 UTC, ppekrol commented on src/Raven.Server/Documents/Handlers/DocumentHandler.cs
> +                if (isLoadStartingWith)
This introduces inconsistency. Endpoints that are returning documents return them in different JSON format depending of the option used. We should not go this way in our opinion.

2016-12-09 07:44 UTC, ml054 commented on src/Raven.Server/Documents/Handlers/DocumentHandler.cs
> +                if (isLoadStartingWith)
I will fix this as a part of: RavenDB-5796