RavenDB-5438 Implemented a persistent cache for database info (to be …
ravendb/ravendb pull request #1047
Opened 2016-12-07 12:46 UTC by talweiss1982

…displayed in the studio for unloaded databases)

2016-12-07 14:42 UTC, ayende requested changes

2016-12-07 14:42 UTC, ayende commented on src/Raven.Server/Documents/DatabaseInfoCache.cs
> +                var databaseName = databaseInfo["Name"] as string;
Promote to parameter externally

2016-12-07 14:42 UTC, ayende commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +        public DynamicJsonValue GenerateDatabaseInfo(bool forCache)
Removed `forCache` if not used, YAGNI for now

2016-12-07 14:42 UTC, ayende commented on src/Raven.Server/Documents/DatabasesLandlord.cs
> +            serverStore.DatabaseInfoCache.InsertDatabaseInfo(database.GenerateDatabaseInfo(true));
Here delete this on load, so we'll only have this for dbs that were successfully shutdown.

2016-12-08 12:41 UTC, closed without merging

2016-12-08 12:41 UTC, talweiss1982 commented
something went wrong with the rebase