HRINT-1715 - licensing adjustments for TimeSeries
ravendb/ravendb pull request #10868
Opened 2020-07-15 18:07 UTC by grisha-kotler

2020-07-15 18:16 UTC, ayende approved these changes

2020-07-16 07:35 UTC, ppekrol requested changes

2020-07-16 07:35 UTC, ppekrol commented on src/Raven.Client/Exceptions/Commercial/LimitType.cs
> +        TimeSeriesAggregationAndRetention,
TimeSeriesRollupsAndRetention

2020-07-16 07:35 UTC, ppekrol commented on src/Raven.Server/Commercial/LicenseManager.cs
> +                var message = GenerateDetails(timeSeriesAggregationAndRetentionCount, "time series aggregation and retention");
rollups

2020-07-16 07:35 UTC, ppekrol commented on src/Raven.Server/Commercial/LicenseManager.cs
> +            var details = $"Your current license ({LicenseStatus.Type}) does not allow adding time series aggregation and retention";
rollups

2020-07-16 07:35 UTC, ppekrol commented on src/Raven.Server/Commercial/LicenseValidator.cs
> +            "documentsCompression", "timeSeriesAggregationAndRetention"
rollups

2020-07-16 07:36 UTC, ppekrol commented
@karmeli87 will apply the fixes. Merging.

2020-07-16 07:37 UTC, merged