RavenDB-14533 Debug endpoint to show segments on time series
ravendb/ravendb pull request #10915
Opened 2020-07-22 12:00 UTC by efratshenhar

2020-07-22 12:13 UTC, karmeli87 commented on src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
> +        internal List<SegmentSummary> GetSegmantsSummary(DocumentsOperationContext context, string documentId, string name)
Need to expose it via an endpoint and limit it with `from` and `to`

2020-07-23 09:19 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +            var to = GetDateTimeQueryString("to") ?? DateTime.MaxValue;
`required: false`

2020-07-23 09:23 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +                }
Let's have `SegmentSummary` to implement `IDynamicJson`.
```
using (var writer = new BlittableJsonTextWriter(context, ResponseBodyStream()))
                {
                    context.Write(writer, summery.ToJson());
                }
```

2020-07-23 10:26 UTC, karmeli87 commented on src/Raven.Server/Documents/TimeSeries/TimeSeriesReader.cs
> +                    numberOfLiveEntries = _currentSegment.NumberOfLiveEntries,
shouldn't be `seg.Segment` as well?

2020-07-23 10:26 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +        [RavenAction("/databases/*/timeseries/debug", "GET", AuthorizationStatus.ValidUser)]
there might be more debug endpoints.
let's call this one:
`/databases/*/timeseries/debug/segments-summery`

2020-07-23 10:26 UTC, karmeli87 commented on src/Raven.Server/Documents/TimeSeries/TimeSeriesReader.cs
> +            InitializeSegment(out _, out _currentSegment);
this will happened in `SegmentsOrValues`, no?

2020-07-23 10:26 UTC, karmeli87 commented on src/Raven.Server/Documents/TimeSeries/TimeSeriesReader.cs
> +                }).ToList();
The `ToList` is not needed.

2020-07-26 08:32 UTC, karmeli87 approved these changes

2020-07-27 08:56 UTC, ppekrol requested changes

2020-07-27 08:56 UTC, ppekrol commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
>          [RavenAction("/databases/*/timeseries/names/config", "POST", AuthorizationStatus.ValidUser)]
It looks like your method landed in between other attribute and ConfigTimeSeriesNames

2020-07-27 08:56 UTC, ppekrol commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +        [RavenAction("/databases/*/timeseries/debug/segments-summery", "GET", AuthorizationStatus.ValidUser)]
typo: summery

2020-07-27 08:56 UTC, ppekrol commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +                    writer.WritePropertyName("Segments Summary");
Let's avoid spaces in properties. Change to `Results` ?

2020-07-27 08:56 UTC, ppekrol commented on src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
> +            public string documentId;
public fields should start from Uppercase

2020-07-27 08:56 UTC, ppekrol commented on test/SlowTests/Client/TimeSeries/Issues/RavenDB-14533.cs
> +        public async Task TimeSeriesSegmantsSummary()
typo: Segmants

2020-07-27 08:56 UTC, ppekrol commented on src/Raven.Server/Documents/TimeSeries/TimeSeriesStorage.cs
> +                    [nameof(documentId)] = documentId,
JSON fields should not be lowercased

2020-07-27 13:36 UTC, merged