RavenDB-15469 - @expires and @refresh can be both defined in the metadata
ravendb/ravendb pull request #10969
Opened 2020-08-04 13:42 UTC by grisha-kotler

https://issues.hibernatingrhinos.com/issue/RavenDB-15469

2020-08-04 15:09 UTC, ayende approved these changes

2020-08-04 15:09 UTC, ayende requested changes
Wait, why?
What is the issue with defining both of them?

2020-08-05 07:17 UTC, grisha-kotler commented
This was the original intension:
https://github.com/ravendb/ravendb/blob/e58e0ceddbf12ace06055383b58dc6c76d3b01f4/src/Raven.Server/Documents/Expiration/ExpirationStorage.cs#L45

However, this didn't work:
https://github.com/ravendb/ravendb/blob/e58e0ceddbf12ace06055383b58dc6c76d3b01f4/src/Raven.Server/Documents/Expiration/ExpirationStorage.cs#L41

Before the change, if you provide both @expires is the one which is going to be used.

2020-08-05 07:22 UTC, ayende commented
I would rather fix things so you can properly use both expires and refresh
The reason for this was that I reused some mechanisms early on, but there should be no reason they can't both work now

2020-08-06 09:30 UTC, ayende approved these changes

2020-08-10 07:46 UTC, merged