RavenDB-14655 Handling of tombstones in Pull Replication Hub
ravendb/ravendb pull request #11057
Opened 2020-08-27 12:35 UTC by efratshenhar

2020-08-27 17:09 UTC, karmeli87 commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +            public DateTime _lastCleanup;
`LastEtag` and `LastCleanup`

2020-08-27 17:09 UTC, karmeli87 commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +                    return _hubInfoForCleaner._lastEtag;
why not `long.MaxValue`?

2020-08-27 17:09 UTC, karmeli87 commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +                        foreach (var t in Database.DocumentsStorage.GetTombstonesInReverseOrderFrom(context, newEtag, 0, 2))
Let's make a function out of this.. `GetTombstoneAtOrBefore(...)`

2020-08-28 12:36 UTC, ppekrol commented on src/Raven.Server/Config/Categories/TombstoneConfiguration.cs
> +        [ConfigurationEntry("Tombstones.EtagCheckForCleanupWithHubInHours", ConfigurationEntryScope.ServerWideOrPerDatabase)]
IIRC we should use `Hrs` instead of `Hours`, please check that.

2020-08-28 12:36 UTC, ppekrol commented on src/Raven.Server/Config/Categories/TombstoneConfiguration.cs
> +        [ConfigurationEntry("Tombstones.TombstoneHistoryWithHubDefinitionInDays", ConfigurationEntryScope.ServerWideOrPerDatabase)]
`RetentionTimeWithReplicationHubInDays` maybe?

2020-08-28 12:36 UTC, ppekrol commented on src/Raven.Server/Config/Categories/TombstoneConfiguration.cs
> +        [ConfigurationEntry("Tombstones.EtagCheckForCleanupWithHubInHours", ConfigurationEntryScope.ServerWideOrPerDatabase)]
Let's try to simply the name. Maybe `CleanupIntervalWithReplicationHubInHrs` ?

2020-08-28 12:36 UTC, ppekrol commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +                if (!_server.Cluster.ReadRawDatabaseRecord(ctx, Database.Name).HubPullReplicationDefinitionExist())
we prefer `== false` instead `!`

2020-08-28 12:36 UTC, ppekrol commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +            public DateTime _lastCleanup;
We need to persist this? If server will be restarting every 3 days then what will happen?

2020-08-28 12:36 UTC, ppekrol commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +            public DateTime _lastCleanup;
If this needs to be persisted, then we need to do it after cleanup is successful probably a 2nd method in ITombstoneAware?

2020-08-30 07:05 UTC, karmeli87 commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +            public DateTime _lastCleanup;
I don't think we need to persist this.
@efratshenhar correct me If I'm wrong, but upon server restarted we simply will do the binary search again.

2020-08-30 09:37 UTC, efratshenhar commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +            public DateTime _lastCleanup;
yes

2020-09-02 12:16 UTC, ayende requested changes

2020-09-02 12:16 UTC, ayende commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +                    _hubInfoForCleaner.LastEtag = max;
What are the thread safety concerns that we should have here?

2020-09-02 12:16 UTC, ayende commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +                    _hubInfoForCleaner.LastEtag = max;
Shouldn't you set the LastModified here too?

2020-09-02 12:16 UTC, ayende commented on src/Raven.Server/Config/Categories/TombstoneConfiguration.cs
> +        [TimeUnit(TimeUnit.Days)]
If we allow shorter time periods, should this be in days?
What is I want this to be 36 hours?

2020-09-02 12:16 UTC, ayende commented on src/Raven.Server/Config/Categories/TombstoneConfiguration.cs
> +        [TimeUnit(TimeUnit.Hours)]
Left make this a value measured in minutes.

2020-09-02 12:16 UTC, ayende commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +        private readonly HubInfoForCleaner _hubInfoForCleaner = new HubInfoForCleaner();
Let's replace this value completely on each change.

2020-09-08 11:13 UTC, karmeli87 approved these changes

2020-09-08 11:13 UTC, karmeli87 commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +            long daysToSave = Database.Configuration.Tombstones.RetentionTimeWithReplicationHub.GetValue(TimeUnit.Hours);
`hoursToSave`  or simply `retainFor` ;)

2020-09-08 11:15 UTC, arekpalinski commented on src/Raven.Server/Documents/Replication/ReplicationLoader.cs
> +            long daysToSave = Database.Configuration.Tombstones.RetentionTimeWithReplicationHub.GetValue(TimeUnit.Hours);
daysToSave -> hoursToSave

2020-09-08 13:10 UTC, arekpalinski commented on src/Raven.Server/Documents/DocumentsStorage.cs
> +        public IEnumerable<Tombstone> GetTombstonesInReverseOrderFrom(DocumentsOperationContext context, long etag, long start, long take)
Please rename to `GetTombstonesInReverseEtagOrderFrom` for consistency with other methods e.g. `GetDocumentsInReverseEtagOrder`

2020-09-09 08:19 UTC, arekpalinski approved these changes

2020-09-09 08:19 UTC, merged