V4.0 ext3 supp 2
ravendb/ravendb pull request #1111
Opened 2016-12-14 13:26 UTC by aviviadi

http://issues.hibernatingrhinos.com/issue/RavenDB-5522

2016-12-14 17:45 UTC, ayende requested changes

2016-12-14 17:45 UTC, ayende commented on src/Voron/Platform/Posix/AllowBuildOnWindows.cs
> +                return rc;
You have to return to the right location first.

2016-12-14 17:45 UTC, ayende commented on src/Voron/StorageEnvironment.cs
> +                    return false;
You leaked the file handle here.

2016-12-14 17:45 UTC, ayende commented on src/Voron/StorageEnvironment.cs
> +                    File.Delete(filename);
Why not use unlink here?

2016-12-14 17:45 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +        public event EventHandler<NonDurabalitySupportEventArgs> OnNonDurabalitySupportError = (sender, args) => { };
This shouldn't have  default handler

2016-12-14 18:43 UTC, aviviadi commented on src/Voron/Platform/Posix/AllowBuildOnWindows.cs
> +                return rc;
it is fatal error any how..

2016-12-14 18:44 UTC, aviviadi commented on src/Voron/StorageEnvironment.cs
> +                    return false;
will be fixed

2016-12-14 18:45 UTC, aviviadi commented on src/Voron/StorageEnvironment.cs
> +                    File.Delete(filename);
we don't want the user to see the file at all

2016-12-14 18:45 UTC, aviviadi commented on src/Voron/StorageEnvironmentOptions.cs
> +        public event EventHandler<NonDurabalitySupportEventArgs> OnNonDurabalitySupportError = (sender, args) => { };
Where to add an handler for this one ? (and what to do inside of it?)

2016-12-15 14:19 UTC, ayende requested changes

2016-12-15 14:19 UTC, ayende commented on src/Voron/StorageEnvironment.cs
> +                    _log.Info("Failed to delete test file at '" + filename + "'", new IOException("Failed to unlink " + filename));
You are missing the _reason_ for the error.

2016-12-15 14:19 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +                if (_log.IsInfoEnabled)
No, it _should_ throw if no one is actually listening. This is a problem that we will handle in `ServerStore`

2016-12-15 17:04 UTC, merged