RavenDB-15898 Deleting document with Resolved flag, creates a revision
ravendb/ravendb pull request #11608
Opened 2020-12-24 08:45 UTC by efratshenhar

2020-12-24 08:59 UTC, karmeli87 approved these changes

2020-12-24 10:24 UTC, ayende requested changes

2020-12-24 10:24 UTC, ayende commented on test/SlowTests/Issues/RavenDB-15898.cs
> +        // {
Why is this commented?

2020-12-27 07:23 UTC, efratshenhar commented on test/SlowTests/Issues/RavenDB-15898.cs
> +        // {
this is for issue RavenDB-16051

2021-01-05 08:13 UTC, merged