RavenDB-15650 Server check for no detination in backup configuration
ravendb/ravendb pull request #11708
Opened 2021-01-27 10:32 UTC by haludi

https://issues.hibernatingrhinos.com/issue/RavenDB-15650

2021-01-28 13:22 UTC, ppekrol commented
Can you write a test for this?

2021-01-28 13:44 UTC, grisha-kotler requested changes

2021-01-28 13:44 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/BackupConfigurationHelper.cs
> +                throw new InvalidOperationException("The backup configuration contains no destination");
```suggestion
                throw new InvalidOperationException("The backup configuration contains no destinations");
```

2021-01-29 07:36 UTC, ppekrol commented
@haludi can you check failing tests?

2021-02-03 13:50 UTC, merged