RDBS-7263 Additional logs
ravendb/ravendb pull request #11908
Opened 2021-03-25 12:08 UTC by haludi

Do Not Merge!!!
This is for Tzunami to debug their issue 
https://issues.hibernatingrhinos.com/issue/RDBS-7263

2021-03-25 12:44 UTC, grisha-kotler commented on src/Raven.Server/Documents/DocumentsStorage.cs
> +                    if (collectionName.Name.Equals("executiontasks", StringComparison.OrdinalIgnoreCase))
missing `_logger.IsOperationEnabled`

2021-03-25 12:50 UTC, grisha-kotler requested changes

2021-03-25 12:50 UTC, grisha-kotler commented on src/Raven.Server/Documents/DocumentsStorage.cs
> +                    if (collectionName.Name.Equals("executiontasks", StringComparison.OrdinalIgnoreCase))
missing `_logger.IsOperationEnabled`

2021-03-25 12:50 UTC, grisha-kotler commented on src/Raven.Server/Documents/Indexes/Workers/CleanupDocuments.cs
> +                var shouldExtraLogs = collection.Equals("executiontasks", StringComparison.OrdinalIgnoreCase);
missing `_logger.IsOperationEnabled`

2021-03-25 12:50 UTC, grisha-kotler commented on src/Raven.Server/Documents/Indexes/Workers/CleanupDocuments.cs
> +                    else if (_logger.IsInfoEnabled)
```suggestion
                    else if (_logger.IsOpeartionEnabled)
```

2021-03-25 12:50 UTC, grisha-kotler commented on src/Raven.Server/Documents/TombstoneCleaner.cs
> +                            if (tombstone.Key.Equals("executiontasks", StringComparison.OrdinalIgnoreCase))
missing `_logger.IsOperationEnabled`

2021-03-25 12:50 UTC, grisha-kotler commented on src/Raven.Server/Documents/TombstoneCleaner.cs
> +                            if (tombstone.Key.Equals("executiontasks", StringComparison.OrdinalIgnoreCase))
missing `_logger.IsOperationEnabled`

2021-03-25 12:50 UTC, grisha-kotler commented on src/Raven.Server/Documents/TombstoneCleaner.cs
> +                        if (tombstone.Key.Equals("executiontasks", StringComparison.OrdinalIgnoreCase))
missing `_logger.IsOperationEnabled`

2021-03-26 07:49 UTC, closed without merging

2021-03-26 07:49 UTC, ppekrol commented
Reopen when needed.