RavenDB-5901 - Fetch the stats of the database when clicking on its block
ravendb/ravendb pull request #1213
Opened 2016-12-27 13:42 UTC by grisha-kotler

http://issues.hibernatingrhinos.com/issue/RavenDB-5901

2016-12-27 16:20 UTC, ml054 requested changes

2016-12-27 16:20 UTC, ml054 commented on src/Raven.Studio/wwwroot/App/views/resources/resources.html
> +                <div style="cursor: pointer" data-bind="click: $root.activateResource, attr: { 'data-state-text': badgeText, class: 'state ' + badgeClass() }"></div>
Can we use less files for this?

2016-12-27 16:20 UTC, ml054 commented on src/Raven.Studio/typescript/models/resources/info/databaseInfo.ts
> +    static empty(resourceName: string): databaseInfo {
Can we avoid having this method? Instead when we get info that new resource was created, then fetch information only for this resource and then add to resources list? I think @Danielle9897 so implementing something similar.

2016-12-27 16:20 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/resources/resources.ts
> +        let resource = this.resourcesManager.resources().filter(x => x.qualifiedName === rsInfo.qualifiedName)[0];
use find instead.

2016-12-27 16:20 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/resources/resources.ts
> +        resource.activate();
this call should trigger EVENT.Resource.Activate and update activeResourceTracker.default.resource(resource);, so please remove previous line.

2016-12-27 16:44 UTC, grisha-kotler commented on src/Raven.Studio/typescript/models/resources/info/databaseInfo.ts
> +    static empty(resourceName: string): databaseInfo {
We cannot get the information about the database until it's actually loaded anyway.
After we receive the "Load" notification we fetch the stats.

2016-12-27 16:45 UTC, grisha-kotler commented on src/Raven.Studio/typescript/viewmodels/resources/resources.ts
> +        resource.activate();
Without this line there is a delay in the resource activation.
I'll see why

2016-12-27 16:45 UTC, grisha-kotler commented on src/Raven.Studio/wwwroot/App/views/resources/resources.html
> +                <div style="cursor: pointer" data-bind="click: $root.activateResource, attr: { 'data-state-text': badgeText, class: 'state ' + badgeClass() }"></div>
Yes

2016-12-27 16:45 UTC, grisha-kotler commented on src/Raven.Studio/typescript/viewmodels/resources/resources.ts
> +        let resource = this.resourcesManager.resources().filter(x => x.qualifiedName === rsInfo.qualifiedName)[0];
ok

2016-12-27 17:48 UTC, ml054 commented on src/Raven.Studio/typescript/models/resources/info/databaseInfo.ts
> +    static empty(resourceName: string): databaseInfo {
not necessarily it's true.  tal implemented cache so we can fetch info even about offline databases, but event had name loaded not load  ( changed few days ago by Danielle) so right now we have assurance that database is already loaded when this notification arrives. so we remove this empty method and load info and then display on screen

2016-12-27 18:13 UTC, grisha-kotler commented on src/Raven.Studio/typescript/models/resources/info/databaseInfo.ts
> +    static empty(resourceName: string): databaseInfo {
What if I changed the database document (which will trigger a "Write")? This shouldn't "wake up" the database

2016-12-27 18:18 UTC, ml054 commented on src/Raven.Studio/typescript/models/resources/info/databaseInfo.ts
> +    static empty(resourceName: string): databaseInfo {
It shouldn't:
In general we should call /resources?name={dbName}&type=db
but this call can't wake database up ( and I have hope it is not). 

In v3.5 we fetched information using /stats endpoint, and it was waken up database. In v4.0 we have different behavior.

2016-12-28 08:13 UTC, closed without merging

2016-12-28 08:14 UTC, ayende commented
Please open a new one with the updated changes