Raven db 5944
ravendb/ravendb pull request #1218
Opened 2016-12-27 17:53 UTC by Danielle9897

2016-12-27 18:12 UTC, ml054 requested changes

2016-12-27 18:12 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/resources/deleteResourceConfirm.ts
> +        super.confirm();
please use this.confirm instead of super.confirm

Does we really need double confirmation?

2016-12-27 18:12 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/resources/deleteResourceConfirm.ts
> +        super.confirm();
same here.

2016-12-28 07:41 UTC, Danielle9897 commented on src/Raven.Studio/typescript/viewmodels/resources/deleteResourceConfirm.ts
> +        super.confirm();
1. OK - using this.confirm()
2. It is not duplicate confirmation,
The 'Delete' btn was removed from html, so now there is a direct call to 'keepFile()' from the html, and a direct call to 'deleteEverything()' and I just call 'confirm()' to complete the work and close dialog.

2016-12-28 07:41 UTC, Danielle9897 commented on src/Raven.Studio/typescript/viewmodels/resources/deleteResourceConfirm.ts
> +        super.confirm();
see above comment

2016-12-28 07:50 UTC, ml054 approved these changes

2016-12-28 08:10 UTC, merged