RavenDB-5930 Resources View: When clicking 'Enable' for a Disabled da…
ravendb/ravendb pull request #1223
Opened 2016-12-28 12:59 UTC by Danielle9897

…tabase that is Selected it should go 'Online'

2016-12-28 14:46 UTC, ml054 requested changes

2016-12-28 14:46 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/resources/resources.ts
> +import LoadResourceCommand = require("commands/resources/loadResourceCommand");
use lower case in import name

2016-12-28 14:46 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/resources/resources.ts
> +            if (matchedResource.isCurrentlyActiveResource() && !matchedResource.disabled()) {
don't construct database instance, call asResource instead. It will return database.

2016-12-28 20:45 UTC, Danielle9897 commented on src/Raven.Studio/typescript/viewmodels/resources/resources.ts
> +            if (matchedResource.isCurrentlyActiveResource() && !matchedResource.disabled()) {
done

2016-12-28 20:46 UTC, Danielle9897 commented on src/Raven.Studio/typescript/viewmodels/resources/resources.ts
> +import LoadResourceCommand = require("commands/resources/loadResourceCommand");
done

2016-12-28 20:46 UTC, Danielle9897 commented on src/Raven.Studio/typescript/viewmodels/resources/resources.ts
> +            if (matchedResource.isCurrentlyActiveResource() && !matchedResource.disabled()) {
done

2016-12-29 07:58 UTC, ml054 approved these changes

2016-12-29 08:12 UTC, merged