RavenDB-5830 Clicking outside of notification center should close it
ravendb/ravendb pull request #1259
Opened 2017-01-02 16:37 UTC by Danielle9897

2017-01-02 18:24 UTC, ml054 requested changes

2017-01-02 18:24 UTC, ml054 commented on src/Raven.Studio/typescript/common/shell/resourceSwitcher.ts
> +        let self = this;
this self is not needed, since we use it in arrow function which captures context.

2017-01-02 18:24 UTC, ml054 commented on src/Raven.Studio/wwwroot/App/views/notifications/notificationCenter.html
> +<div data-bind="click: notificationCenter.notificationsState.bind(notificationCenter, true), clickBubble: false">
Do we need click bubble? I think we need to return false from handler function if bubble is needed, but it shouldn't

2017-01-02 18:24 UTC, ml054 commented on src/Raven.Studio/typescript/common/notifications/notificationCenter.ts
> +        return true;
Is it needed to return true? Maybe it is better to have 2 methods: showNotifications, hideNotifications. 
NotificationsStats as method name might be misleading. Additionally you won't need .bind(...., true/false) in views. 

Optionally you will have to call bindAll on notification center to bind `this`.

2017-01-03 08:32 UTC, Danielle9897 commented
Closing this PR, A different design will be tried, 
(adding a transparent 'div' between page and resource switcher & notification center)

2017-01-03 08:32 UTC, closed without merging