RavenDB-17082 Missing HasAttachments, HasCounters, HasTimeSeries flag…
ravendb/ravendb pull request #12659
Opened 2021-08-16 11:56 UTC by efratshenhar

…s in a reverted revision document

2021-08-19 06:48 UTC, ppekrol commented
@efratshenhar Can you check failing tests?

2021-08-19 07:13 UTC, efratshenhar commented
yes

2021-10-04 20:10 UTC, karmeli87 requested changes

2021-10-04 20:10 UTC, karmeli87 commented on src/Raven.Server/Documents/AttachmentsStorage.cs
> +        public void DeleteAttachmentDirect2(DocumentsOperationContext context, LazyStringValue lowerDocId)
please rename

2021-10-04 20:10 UTC, karmeli87 commented on src/Raven.Server/Documents/AttachmentsStorage.cs
> +                var type = AttachmentType.Document;
why do we need those?

2021-10-04 20:10 UTC, karmeli87 commented on src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
> +                    CollectionName collectionName = RemoveOldMetadataInfo(context, documentsStorage, document);
do we need that if we revert to a tombstone?

2021-10-04 20:10 UTC, karmeli87 commented on src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
> +                }
Let's put it in a function and call it `RevertCounters`

2021-10-18 06:39 UTC, efratshenhar commented on src/Raven.Server/Documents/AttachmentsStorage.cs
> +                var type = AttachmentType.Document;
for GetAttachmentKey

2021-10-18 07:08 UTC, efratshenhar commented on src/Raven.Server/Documents/Revisions/RevisionsStorage.cs
> +                    CollectionName collectionName = RemoveOldMetadataInfo(context, documentsStorage, document);
no

2021-10-19 05:48 UTC, karmeli87 commented on test/SlowTests/Issues/RavenDB-17082.cs
> +                    var persons = await session.Advanced.Revisions.GetForAsync<Person>("foo/bar");
In all of the tests you are verifying the revision... let's verify the document as well

2021-10-19 12:01 UTC, karmeli87 approved these changes
After merge, need to handle the time-series as well

2021-10-19 12:56 UTC, merged