RavenDB-17292 - add new license properties
ravendb/ravendb pull request #12870
Opened 2021-10-19 09:47 UTC by grisha-kotler

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-17292
https://issues.hibernatingrhinos.com/issue/RavenDB-17294
https://issues.hibernatingrhinos.com/issue/RavenDB-17295

### Additional description

Add new license features

### Type of change

- Low

### Backward compatibility

- Ensured. Old licenses will work with the new licensing schema.

### Testing 

- It has been verified by manual testing

2021-10-19 09:48 UTC, ayende approved these changes

2021-10-20 06:00 UTC, ayende requested changes

2021-10-20 06:00 UTC, ayende commented on src/Raven.Server/Commercial/LicenseValidator.cs
> +
No, use `Encoding.UTF8.GetString()`, instead.

2021-10-20 11:42 UTC, grisha-kotler commented on src/Raven.Server/Commercial/LicenseValidator.cs
> +
done

2021-10-20 13:31 UTC, ayende approved these changes

2021-10-21 07:30 UTC, ppekrol commented on src/Raven.Server/Commercial/LicenseStatus.cs
> +        public double Version => GetValue<int?>("version") / (double)10 ?? -1;
why double? easier to handle int, like 40 or 50

2021-10-21 12:48 UTC, grisha-kotler commented on src/Raven.Server/Commercial/LicenseStatus.cs
> +        public double Version => GetValue<int?>("version") / (double)10 ?? -1;
done

2021-10-25 11:20 UTC, merged