RavenDB-17339 Support for nested projections in LINQ.
ravendb/ravendb pull request #12883
Opened 2021-10-20 10:14 UTC by maciejaszyk

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-17339

### Additional description

Added support for nested projections in LINQ.

### Type of change

- Bug fix

### How risky is the change?

- Moderate 

### Backward compatibility

- Not relevant

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- Tests have been added that prove the fix is effective or that the feature works

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

2021-10-20 11:15 UTC, ppekrol approved these changes

2021-10-20 12:16 UTC, aviv86 requested changes

2021-10-20 12:16 UTC, aviv86 commented on src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
> +                    }
I noticed a couple of problems here
- This will not work:
```
var q = session.Query<MyEntity>()
	.Select(e => new { Foo = e.Value, Nested = new Result { RawValue = RavenQuery.Raw<int>("e.Value") } })
	.ToList();
```
missing a comma between properties, i.e. select body is :
					
`select { Foo : e.ValueNested : { RawValue : e.Value } }`

need to add something like:
```
if (index > 0)
	sb.Append(", ");
```
			
- These cases of nested `Raw` projections are not covered :	
```	
var q = session.Query<MyEntity>()
	.Select(e => new ResultNested { Nested = new Result { RawValue = RavenQuery.Raw<int>("e.Value") } })
	.ToList();
```
here `expression` is `MemberInitExpression` (and not `NewExpression`) so we go to a different code path.
	
```	
var q = session.Query<MyEntity>()
	.Select(e => new { Nested = new { RawValue = RavenQuery.Raw<int>("e.Value") } })
	.ToList();
```	
here `newExpression.Arguments[0]` is `NewExpression` so we don't pass the `if (newExpression.Arguments[index] is MemberInitExpression)` check

2021-10-21 10:41 UTC, maciejaszyk commented on src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
> +                    }
Ok, done. Fixed now, I've also added an additional path  (last test) **MemberInitExpression** -> **NewExpression**.

2021-10-21 17:55 UTC, ppekrol commented
@aviv86 can you review?

2021-10-26 08:11 UTC, aviv86 approved these changes
LGTM

2021-10-26 08:24 UTC, merged