RavenDB-17381 Transaction recorder error handling
ravendb/ravendb pull request #13164
Opened 2021-11-28 15:54 UTC by Danielle9897

### Issue link
https://issues.hibernatingrhinos.com/issue/RavenDB-17381

### Additional description
Studio: fixed placeholder + added available directories
Server: added validation

### Type of change
- Bug fix

### How risky is the change?
- Low 

### Backward compatibility
- Non breaking change

### Is it platform specific issue?
- No

### Documentation update
- No documentation update is needed 

### Testing 
- It has been verified by manual testing

### Is there any existing behavior change of other features due to this change?
- No

### UI work
- No UI work is needed

2021-11-28 18:06 UTC, ayende requested changes

2021-11-28 18:06 UTC, ayende commented on src/Raven.Server/Documents/Handlers/TransactionsRecordingHandler.cs
> +                    throw new InvalidOperationException("Please enter a path including the file name");
```suggestion
                    throw new InvalidOperationException(outputFilePath + " is a directory, please enter a path to a file.");
```

2021-11-28 18:59 UTC, Danielle9897 commented on src/Raven.Server/Documents/Handlers/TransactionsRecordingHandler.cs
> +                    throw new InvalidOperationException("Please enter a path including the file name");
done

2021-11-28 20:13 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedRecordTransactionCommands.ts
> +    outputFilePathOptions = ko.observableArray<string>(["aaa"]);
aaa?

2021-11-28 20:13 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedRecordTransactionCommands.ts
> +        this.outputFile.throttle(300).subscribe((newPathValue) => {
no need for `(` `)`

2021-11-28 20:33 UTC, Danielle9897 commented on src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedRecordTransactionCommands.ts
> +        this.outputFile.throttle(300).subscribe((newPathValue) => {
done

2021-11-28 20:33 UTC, Danielle9897 commented on src/Raven.Studio/typescript/viewmodels/manage/debugAdvancedRecordTransactionCommands.ts
> +    outputFilePathOptions = ko.observableArray<string>(["aaa"]);
oops - forgot to remove...

2021-11-29 07:06 UTC, ml054 approved these changes

2021-11-30 13:20 UTC, merged