RavenDB-17633: Rearrange the backup timer if the backup got active by other node and then got active by current node while running
ravendb/ravendb pull request #13224
Opened 2021-12-07 11:53 UTC by garayx

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-17633
### Additional description

Currently if task state is `ActiveByCurrentNode` and is being processed we always assume the timer will rearrange when the backup finish, but if it got `ActiveByOtherNode` while running the backup timer is disposed, then when the backup finish it check if there is an active timer, but it there isn't so we end up without scheduling next backup, this PR is handling this edge case by always scheduling the timer (to next backup occurrence) if the task status got `ActiveByCurrentNode` while running and it doesn't have a timer.

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Backward compatibility

- Not relevant

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- Tests have been added that prove the fix is effective or that the feature works
 - Internal classes added to the test class
- It has been verified by manual testing

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

2021-12-07 14:14 UTC, grisha-kotler requested changes

2021-12-07 14:14 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
>                          if (_logger.IsOperationsEnabled)
Can we not dispose `existingBackupState.DisableFutureBackups(cancelRunningBackup: false)`?

2021-12-07 14:15 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
>                          if (_logger.IsOperationsEnabled)
This will not cancel the running backup. Once it's done it'll reschedule and won't run if it isn't on the current node.

2021-12-08 09:57 UTC, garayx commented on src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
>                          if (_logger.IsOperationsEnabled)
done

2021-12-08 10:54 UTC, grisha-kotler approved these changes

2021-12-09 08:16 UTC, merged