RavenDB-15357: try to print backup status when we fail to save backup status
ravendb/ravendb pull request #13278
Opened 2021-12-14 13:46 UTC by garayx

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-15357

### Additional description

If we fail to save backup status on backup, we don't show the exception, also now we will try to print the backup status that save in memory (in periodic status)

2021-12-14 13:59 UTC, ayende requested changes

2021-12-14 13:59 UTC, ayende commented on src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
> +                    return _messages;
That is a really bad idea. You are locking, but returning the a mutable instance.

2021-12-14 15:15 UTC, garayx commented on src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
> +                    return _messages;
done

2021-12-16 22:37 UTC, ppekrol commented on src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
> +        public IEnumerable<string> Messages => _messages;
This is a breaking change

2021-12-20 10:21 UTC, garayx commented on src/Raven.Client/Documents/Smuggler/SmugglerResult.cs
> +        public IEnumerable<string> Messages => _messages;
reverted

2022-01-04 08:35 UTC, merged