RavenDB-17262 - Creation of setup ZIP file from RVN implemented.
ravendb/ravendb pull request #13398
Opened 2022-01-04 18:05 UTC by omerlewitz

### Issue link
https://issues.hibernatingrhinos.com/issue/RavenDB-17262

### Additional description
It has been tested locally from `RVN` command and from the `setup wizard` and it worked. 
Regarding the ticket - `-u|--unsecured-ravendb-url http://localhost:3456  # optional` why do we need that?

**I noticed I ruined some indentations I will push a change tomorrow.**

2022-01-05 08:59 UTC, ayende requested changes

2022-01-05 08:59 UTC, ayende commented on src/Raven.Server/Commercial/LetsEncryptUtils.cs
> +            Console.WriteLine($"Getting challenge(s) from Let's Encrypt. Using e-mail: {setupInfo.Email}.");
Nope

2022-01-05 08:59 UTC, ayende commented on src/Raven.Server/Commercial/LetsEncryptUtils.cs
> +            Console.WriteLine($"Updating DNS record(s) and challenge(s) in {setupInfo.Domain.ToLower()}.{setupInfo.RootDomain.ToLower()}.");
Nope, etc.

2022-01-05 08:59 UTC, ayende commented on src/Raven.Server/ServerWide/SecretProtection.cs
> +            //ValidateKeyUsages(source, loadedCertificate, serverStore.Configuration.Security.CertificateValidationKeyUsages);
Why is this commented?

2022-01-05 15:26 UTC, omerlewitz commented
@ayende  it's a mess.
I can't Rebase and there's a lot of indentation problems.
Working on a new PR and I will attach the link later on.

2022-01-05 15:26 UTC, closed without merging

2022-01-06 19:37 UTC, omerlewitz commented
New PR here -https://github.com/ravendb/ravendb/pull/13408