HRINT-255 Moving script from jenkins to github actions
ravendb/ravendb pull request #13547
Opened 2022-01-26 10:26 UTC by hiddenshadow21

### Issue link

https://issues.hibernatingrhinos.com/issue/HRINT-255

### Additional description

Run compilation and message convention check using Github Actions instead of Jenkins.

2022-01-28 11:13 UTC, topalach approved these changes

2022-01-30 22:34 UTC, gregolsky commented on .github/workflows/compile.yml
> +  pull_request_target
We need to build the code on `pull_request`, but send a notification using another workflow that's run on `pull_request_target`. See this article: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

2022-01-30 22:36 UTC, gregolsky requested changes
Changes required around the notifications on GH actions targets. Please see my comments.

2022-01-31 13:25 UTC, gregolsky commented on .github/workflows/StudioTests.yml
> +        - v5.3
@ppekrol this PR is for 4.2 and here we have 5.3? That ok?

2022-01-31 13:33 UTC, gregolsky commented on .github/workflows/compile.yml
> +      - name: Setup .NET Core 3.1
Can we determine the .NET version from the PR base branch?

2022-01-31 14:57 UTC, gregolsky approved these changes

2022-02-01 07:22 UTC, gregolsky commented
@ppekrol Just FYI Bartek is still working on this one, please don't merge yet.

2022-02-03 09:00 UTC, gregolsky commented on scripts/githubActions/CompileGenerateMessage.sh
> +header="<${PRLINK}|[${PRTAGRETBRANCH}] [PR #${PRNUMBER}] ${PRTITLE}> failed (<$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|GITHUB ACTIONS>)"
typo PRTAGRETBRANCH -> PRTARGETBRANCH

2022-02-03 09:00 UTC, gregolsky commented on .github/workflows/conventions.yml
> +          PRTAGRETBRANCH: ${{ github.event.pull_request.base.ref }}
PRTAGRETBRANCH -> PRTARGETBRANCH

2022-02-03 09:10 UTC, hiddenshadow21 commented on scripts/githubActions/CompileGenerateMessage.sh
> +header="<${PRLINK}|[${PRTAGRETBRANCH}] [PR #${PRNUMBER}] ${PRTITLE}> failed (<$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|GITHUB ACTIONS>)"
done

2022-02-03 09:10 UTC, hiddenshadow21 commented on .github/workflows/conventions.yml
> +          PRTAGRETBRANCH: ${{ github.event.pull_request.base.ref }}
done

2022-02-03 09:19 UTC, gregolsky approved these changes

2022-02-03 10:10 UTC, merged