RavenDB-18008 - [Sharding] Allow to get database stats (shard wide)
ravendb/ravendb pull request #13713
Opened 2022-03-01 11:32 UTC by shiranshalom

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-18008

### Type of change

- New feature

### How risky is the change?

- Low 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- It has been verified by manual testing

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- It requires further work in the Studio

2022-03-01 12:04 UTC, grisha-kotler requested changes

2022-03-01 12:04 UTC, grisha-kotler commented on src/Raven.Server/Documents/ShardedHandlers/ShardedStatsHandler.cs
> +        private static void WriteDatabaseStatisticsInternal(AbstractBlittableJsonTextWriter writer, DatabaseStatistics statistics)
Can we reuse the code from `BlittableJsonTextWriterExtensions`?

2022-03-01 13:01 UTC, shiranshalom commented on src/Raven.Server/Documents/ShardedHandlers/ShardedStatsHandler.cs
> +        private static void WriteDatabaseStatisticsInternal(AbstractBlittableJsonTextWriter writer, DatabaseStatistics statistics)
done

2022-03-02 07:09 UTC, karmeli87 requested changes

2022-03-02 07:09 UTC, karmeli87 commented on src/Raven.Server/Documents/ShardedHandlers/ShardedStatsHandler.cs
> +            public RavenCommand<DatabaseStatistics> CreateCommandForShard(int shard) => new GetStatisticsOperation.GetStatisticsCommand(null, null);
what are those `null`,`null`? please use the named parameters
e.g. `GetStatisticsCommand(foo: null, bar: null)`

2022-03-02 07:09 UTC, karmeli87 commented on src/Raven.Server/Documents/ShardedHandlers/ShardedStatsHandler.cs
> +                        combined.CountOfIndexes = result.CountOfIndexes;
let's get the indexes & the index count from the database record if possible

2022-03-02 07:10 UTC, karmeli87 commented
Please add a simple test for this as well.

2022-03-02 08:48 UTC, shiranshalom commented on src/Raven.Server/Documents/ShardedHandlers/ShardedStatsHandler.cs
> +            public RavenCommand<DatabaseStatistics> CreateCommandForShard(int shard) => new GetStatisticsOperation.GetStatisticsCommand(null, null);
done

2022-03-02 11:03 UTC, shiranshalom commented on src/Raven.Server/Documents/ShardedHandlers/ShardedStatsHandler.cs
> +                        combined.CountOfIndexes = result.CountOfIndexes;
done

2022-03-02 12:33 UTC, karmeli87 commented on src/Raven.Server/Documents/ShardedHandlers/ShardedStatsHandler.cs
> +                    Priority = index.Priority ?? new IndexPriority(),
`IndexPriority` is an `enum` so it is wired for me to see `new IndexPriority()`.
Does the `Priority`/`LockMode`/`State` are nullable?

Wonder what about `IsStale`.. not sure what do to with that, but let's set it explicitly here.

Also the `State` is from the index definition while the actual state can be different. (e.g. we can disable an index locally)

We don't want to handle this right now, but do need to keep that in mind

2022-03-04 08:43 UTC, ppekrol commented on src/Raven.Server/Documents/ShardedHandlers/ShardedStatsHandler.cs
> +        {
Wouldn't it be better to move this inside the ShardedStatsOperation? Then each time I execute this (e.g. in a different place than this endpoint) the results will be consistent. cc @karmeli87 Thoughts?

2022-03-09 19:49 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/Processors/AbstractStatsHandlerProcessor.cs
> +            {
the sharded probably should simply override this?

2022-03-09 19:49 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/Processors/AbstractStatsHandlerProcessor.cs
> +            {
actually `GetDatabaseIndexesFromRecord` should be only at the sharded, no?

2022-03-09 19:49 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/Processors/AbstractStatsHandlerProcessor.cs
> +            {
okay, I realize there is a problem with the inheritance and we can't have a common abstract class..
wouldn't it be better to hook such things on the `ShardedContext` ? an extension for the  `record.Indexes` ?

2022-03-09 22:55 UTC, ppekrol approved these changes

2022-03-11 16:22 UTC, merged