5.2_RavenDB-18296: fix backup not ascii database name to AWS s3
ravendb/ravendb pull request #13869
Opened 2022-03-21 14:08 UTC by shaharhikri

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-18296

### Additional description

fix backup not ascii database name to AWS s3.

_Please delete below the options that are not relevant_

### Type of change

- Bug fix
 
### How risky is the change?

- Low 

### Backward compatibility

- Not relevant

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- Tests have been added that prove the fix is effective or that the feature works

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

2022-03-21 16:20 UTC, grisha-kotler requested changes

2022-03-21 16:20 UTC, grisha-kotler commented on test/SlowTests/Server/Documents/PeriodicBackup/Aws.cs
> +                Console.WriteLine(@object.Metadata.Keys);
Can be removed

2022-03-21 16:20 UTC, grisha-kotler commented on test/SlowTests/Server/Documents/PeriodicBackup/Aws.cs
> +            using (var client = new RavenAwsS3Client(settings, DefaultConfiguration, progress))
Can we reuse the `PutObject` function?

2022-03-22 09:21 UTC, shaharhikri commented on test/SlowTests/Server/Documents/PeriodicBackup/Aws.cs
> +                Console.WriteLine(@object.Metadata.Keys);
Done

2022-03-22 09:21 UTC, shaharhikri commented on test/SlowTests/Server/Documents/PeriodicBackup/Aws.cs
> +            using (var client = new RavenAwsS3Client(settings, DefaultConfiguration, progress))
Done

2022-03-22 10:38 UTC, grisha-kotler approved these changes

2022-03-22 18:41 UTC, merged