RavenDB-6103: Reuse journal files
ravendb/ravendb pull request #1392
Opened 2017-01-16 14:04 UTC by aviviadi

2017-01-16 14:05 UTC, aviviadi commented on src/Voron/Impl/Journal/JournalReader.cs
> +                // TODO : what to do on TxId == 1 ??
@ayende Should we fail here ?

2017-01-16 14:08 UTC, aviviadi commented on test/FastTests/Blittable/MemoryPoolTests.cs
> -﻿using System.Collections.Concurrent;
please ignore this file

2017-01-16 14:23 UTC, ayende requested changes

2017-01-16 14:23 UTC, ayende commented on src/Voron/Impl/Journal/JournalReader.cs
> +                        "Page has valid(!) hash but transaction id bigger more then '1' from last tx. transaction id = " +
Don't do `more than '1'` user has no concept, add the actual number

2017-01-16 14:23 UTC, ayende commented on src/Voron/Impl/Journal/JournalReader.cs
> +            // * TxId == current Id + 1  ::  valid, but if hash is invalid - we can assume corruption
Not corruption, just that the transaction hasn't been committed

2017-01-16 14:23 UTC, ayende commented on src/Voron/Impl/Journal/JournalReader.cs
> +                    throw new InvalidDataException("Compression error in transaction.");
Need better error msg here

2017-01-16 14:23 UTC, ayende commented on src/Voron/Impl/Journal/WriteAheadJournal.cs
> +            txHeader->Hash = Hashing.XXHash64.Calculate(compressionBuffer, (ulong)compressedLen, (ulong)txHeader->TransactionId);
Need to be sure to update the voron format here.
`Voron.Global.Constants.CurrentVersion`

2017-01-16 14:23 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +        private static long _reuseCounter;
why static?

2017-01-16 14:23 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +                var journalsForReuse = dirInfo.GetFiles("*.pending-recycle").Select(x => x.Name).ToList();
Why call `ToList` if you are just going to iterate and throw in a bit?

2017-01-16 14:23 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +                        var reuseNum = long.Parse(reuseNameWithoutExt);
TryParse

2017-01-16 14:23 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +                        // ignore
DeleteFile?

2017-01-16 14:23 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +                var fileInfoList = new List<Tuple<string, DateTime>>();
Use SortedList here, instead.

2017-01-16 14:23 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +                    if (_log.IsInfoEnabled)
Why is this logged? we will always have it when we start, at least

2017-01-16 14:23 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +                    if (DateTime.UtcNow - elementExist.Item2 > TimeSpan.FromHours(72))
Wrong, this should be 72 hours from the newest element in here.

2017-01-16 14:23 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +        private readonly ConcurrentStack<Tuple<string, DateTime>> _journalsForReuse =
This doesn't need to be concurrent, and better be SortedList

2017-01-16 14:23 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +                            _reuseCounter = reuseNum;
Not thread safe here, and shouldn't be, make this instance value

2017-01-16 14:23 UTC, ayende commented on src/Voron/StorageEnvironmentOptions.cs
> +                var newName = Path.GetDirectoryName(filename) + Path.DirectorySeparatorChar + PendingRecycleName(reuseCounter);
Never do that, use `Path.Combine`

2017-01-16 14:23 UTC, ayende commented on test/FastTests/Blittable/MemoryPoolTests.cs
> -﻿using System.Collections.Concurrent;
so why is it here

2017-01-16 15:04 UTC, aviviadi commented on src/Voron/StorageEnvironmentOptions.cs
> +                    if (_log.IsInfoEnabled)
No it isn't.  We TryPop from _journalsForReuse and if it is empty (at start i.e.) then we returning null from this method

2017-01-17 07:06 UTC, closed without merging

2017-01-17 07:15 UTC, arekpalinski commented on src/Voron/Impl/Journal/JournalReader.cs
> +                        "Page has valid(!) hash but transaction id bigger more then '1' from last tx. transaction id = " +
Name `FailOnValidHash` is confusing. It doesn't state that `txIdDiff > 1`.

2017-01-17 07:19 UTC, arekpalinski commented on src/Voron/Impl/Journal/JournalReader.cs
> -                }
Didn't we loose the validation check and raising recovery error here? I don't see `options.InvokeRecoveryError` to be moved somewhere.

2017-01-17 07:31 UTC, arekpalinski commented on src/Voron/StorageEnvironmentOptions.cs
> +                _journalsForReuse.Push(new Tuple<string, DateTime>(newName, fileModifiedDate));
Is is ok to not have any size limit on `_journalsForReuse`?

2017-01-17 07:32 UTC, arekpalinski commented on src/Voron/StorageEnvironmentOptions.cs
> +                    var reuseFileName = dirInfo.ToString() + reuseFileNameIter;
`Path.Combine`

2017-01-17 07:41 UTC, arekpalinski commented on src/Voron/StorageEnvironmentOptions.cs
> +                    var reuseFileName = dirInfo + reuseFileNameIter;
Path.Combine

2017-01-17 07:44 UTC, arekpalinski commented
Once we run this on indexes of SO dataset we will end up with dozen of journals residing on the disk even though the indexing work is done.

We might want to cleanup the files more frequently than 72 hours.

2017-01-17 07:50 UTC, arekpalinski commented
Note that we already have `StorageEnvironment.Cleanup`

2017-01-17 07:51 UTC, arekpalinski commented
It would be good to have some tests for journals reuse / cleanup