RavenDB-19181 support `string.Empty` & Throw for TimeSeriesCopy, AttachmentMOVE, AttachmentCOPY
ravendb/ravendb pull request #14862
Opened 2022-09-04 06:44 UTC by karmeli87

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-19181

### Additional description

- Support passing `string.Empty` as and ID
- Throw `NotSupportedInShardingException` for TimeSeriesCopy, AttachmentMOVE, AttachmentCOPY commands
Because this might require us to send the attachment/TS to a different shard, which might be complex. 
- Handle `PUT` command without any change vector (we get such thing from studio and probably from non-C# clients)

### Type of change

- Bug fix

### How risky is the change?

- Not relevant

### Backward compatibility

- Breaking change since we will throw for TimeSeriesCopy, AttachmentMOVE, AttachmentCOPY commands

### Is it platform specific issue?

- No

### Documentation update

- This change requires a documentation update.

### Testing 

- Tests have been added that prove the fix is effective or that the feature works
- It has been verified by manual testing

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- It requires further work in the Studio
Yes, cloning for a document with attachment/TimeSeries is not going to work for the sharded database

2022-09-04 16:08 UTC, ayende requested changes

2022-09-04 16:08 UTC, ayende commented on test/FastTests/Sharding/BasicSharding.cs
> +                    s.TimeSeriesFor(u, "Price").Append(DateTime.UtcNow, 1000);*/
?

2022-09-04 16:08 UTC, ayende commented on src/Raven.Server/Documents/Sharding/Handlers/Batches/ShardedBatchCommand.cs
> +            return _databaseContext.GetShardNumber(_context, cmd.Id.AsSpan(0, cmd.Id.Length - 2));   // here we are cheating by cutting '$/' from the end to detect shard number based on BASE26 part
I don't understand what you are doing here. Can this be moved to `ShardHelper` as well?

2022-09-05 11:43 UTC, ppekrol approved these changes

2022-09-05 11:49 UTC, merged

2022-09-06 09:19 UTC, arekpalinski commented
LGTM