RavenDB-5964 Why replication doesn't have IDocumentTombstoneAware?
ravendb/ravendb pull request #1496
Opened 2017-01-31 15:40 UTC by karmeli87

2017-01-31 19:05 UTC, ayende requested changes

2017-01-31 19:05 UTC, ayende commented on src/Raven.Server/Documents/Replication/DocumentReplicationLoader.cs
> +        public Dictionary<string, long> GetLastProcessedDocumentTombstonesPerCollection()
Might be just easier to change the tombstone deleter to just accept something that says "across all collections, my latest is X"

2017-01-31 19:05 UTC, ayende commented on src/Raven.Server/Documents/Replication/DocumentReplicationLoader.cs
> +            var minEtag = _outgoing.Select(o => o._lastSentDocumentEtag).Min();
This is wrong. What happens if the remote server has just restarted and isn't online. You are looking only at the _connected_ servers.
Instead, you need to keep track of all of the confirmations that we previously got across all of them.

2017-01-31 19:06 UTC, closed without merging

2017-01-31 20:51 UTC, ppekrol commented on src/Raven.Server/Documents/Replication/DocumentReplicationLoader.cs
> +        public Dictionary<string, long> GetLastProcessedDocumentTombstonesPerCollection()
Maybe support @all_docs? https://github.com/ravendb/ravendb/blob/v4.0/src/Raven.Client/Data/Constants.cs#L113

2017-01-31 21:28 UTC, HibernatingRhinosServiceAccount commented
I don't think we actually use this

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Tue, Jan 31, 2017 at 10:51 PM, Paweł Pekról <notifications@github.com>
wrote:

> *@ppekrol* commented on this pull request.
> ------------------------------
>
> In src/Raven.Server/Documents/Replication/DocumentReplicationLoader.cs
> <https://github.com/ravendb/ravendb/pull/1496>:
>
> >              ea.ThrowIfNeeded();
>          }
>
> +
> +        public Dictionary<string, long> GetLastProcessedDocumentTombstonesPerCollection()
>
> Maybe support @all_docs? https://github.com/ravendb/
> ravendb/blob/v4.0/src/Raven.Client/Data/Constants.cs#L113
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ravendb/ravendb/pull/1496>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AB4wABb7-jOi8BJERw8l3FcxVzPzEu4Fks5rX57TgaJpZM4Lyyv5>
> .
>

2017-01-31 22:24 UTC, ppekrol commented
this is why I was suggesting to add it to cover the case that replication requires. If the returned result will be <@all_docs, some_etag> then the cleaner will know how to handle that.

2017-02-01 02:41 UTC, ayende commented
Oh, as the special key, yeah, that would work