RavenDB-19385 Request timeout not applied for lazy queries
ravendb/ravendb pull request #15056
Opened 2022-10-03 11:21 UTC by ayende

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-19385 

### Additional description

In `MultiGetHandler`, we were flushing the stream to the client before we executed the first request. That means that the server response was immediate, and bypassed the actual query time.

Now we'll wait for the first request before flushing anything.

That said, it raised an interesting problem. What is the _scope_ of timeout for lazy query? 
A single operation, or all of them?
Consider the following sequence: `[slow, fast]` - which will result in a timeout, but `[fast, slow]` will not.

https://github.com/ravendb/ravendb/discussions/14988#

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- Tests have been added that prove the fix is effective or that the feature works

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

2022-10-03 11:54 UTC, ayende commented
A big difference here is that we'll wait for _all_ response to be complete before replying.
The alternative is that we'll send them one at a time, but then the caller cannot ensure timeout on the 2nd request.

2022-10-03 12:59 UTC, garayx commented on src/Raven.Server/Documents/Handlers/MultiGetHandler.cs
> +                context.ReturnMemoryStream(memoryStream);
ReturnMemoryStream should be in finally

2022-10-10 07:20 UTC, ppekrol requested changes
I think that this can have a severe impact on response times and memory consumption. There must be a better way to handle this.

2022-10-27 09:49 UTC, ayende commented
Will now flush the network stream after every internal request

2022-11-02 15:07 UTC, merged