RavenDB-6226
ravendb/ravendb pull request #1528
Opened 2017-02-02 13:18 UTC by aviviadi

2017-02-02 13:18 UTC, aviviadi commented
http://issues.hibernatingrhinos.com/issue/RavenDB-6226

2017-02-03 08:40 UTC, ayende requested changes

2017-02-03 08:40 UTC, ayende commented on src/Raven.Server/Documents/TransactionOperationsMerger.cs
> +                            finally
What sets the op.Exception here? Are we sure we won't be sending an ok when we actually errored?

2017-02-03 08:40 UTC, ayende commented on src/Voron/Impl/Journal/WriteAheadJournal.cs
> +            var files = _files;
Why did you do this? This reproduce the race condition we fixed.

2017-02-03 08:40 UTC, ayende commented on src/Voron/Platform/Posix/PosixMemoryMapPager.cs
> +        public override void FillZeroLengthJournalWithZeros(ulong size)
Will not actually work, the error is actually being thrown from the constructor.

2017-02-03 08:44 UTC, merged

2017-02-05 09:09 UTC, aviviadi commented on src/Voron/Impl/Journal/WriteAheadJournal.cs
> +            var files = _files;
I didn't do specifically that.. It was from your old pull i guess