RavenDB-16075 - LeaderCanCecedeFromClusterAndNewLeaderWillBeElected failed
ravendb/ravendb pull request #15489
Opened 2022-12-22 12:34 UTC by shaharhikri

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-16075/RachisTests.EmergencyOperations.LeaderCanCecedeFromClusterAndNewLeaderWillBeElected

### Additional description

LeaderCanCecedeFromClusterAndNewLeaderWillBeElected failed, because there's some follower which is still 'Promotable'
so the new candidate have no voters (one has topology mismatch and the other promotable) so it turn itself into 'Passive' mode.

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Backward compatibility

- Not relevant

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- Tests have been added that prove the fix is effective or that the feature works

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

2022-12-23 09:01 UTC, ayende commented
I don't understand. Are you fixing the test, or fixing the issue?
This is a test only fix. Do we need to worry about scenario like that for prod?

2022-12-25 08:05 UTC, karmeli87 commented
It is a race between node waiting to be promoted (on the RAFT level) and removing the leader from the cluster (via `HardResetToNewCluster`).
I think we can fix the test only, since `HardResetToNewCluster` is an emergency operation, which we don't want to fail.

2022-12-25 08:14 UTC, ayende commented
Okay, makes sense

2022-12-25 12:06 UTC, karmeli87 commented on src/Raven.Server/Rachis/Leader.cs
> +                    if(clusterTopology!=null && clusterTopology.AllNodes.Count>1)
1. formatting
2. let's add a new property `Count` to the `ClusterTopology` (similar to the `DatabaseTopology`)

2022-12-25 12:07 UTC, karmeli87 requested changes

2022-12-25 12:07 UTC, karmeli87 commented on src/Raven.Server/Rachis/Leader.cs
> +                    if(clusterTopology!=null && clusterTopology.AllNodes.Count>1)
also, does it mean that the leader is dead? can we execute new command if we reach this code?

2023-01-08 12:06 UTC, karmeli87 approved these changes

2023-01-10 10:15 UTC, ppekrol commented on src/Raven.Client/Http/ClusterTopology.cs
> +        public int Count => Members.Count + Promotables.Count + Watchers.Count;
internal

2023-01-10 10:20 UTC, shaharhikri commented on src/Raven.Client/Http/ClusterTopology.cs
> +        public int Count => Members.Count + Promotables.Count + Watchers.Count;
Done

2023-01-10 11:30 UTC, merged