RavenDB-19235: Add the ability to cancel and delay ongoing backups by Operator
ravendb/ravendb pull request #15614
Opened 2023-01-12 12:11 UTC by ArieSLV

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-19235/Add-the-ability-to-cancel-and-delay-server-wide-backups-by-Operator

### Additional description

In case the backup is causing problems for the server, we need to be able to delay and cancel such operation for a set time

### Type of change

- New feature

### How risky is the change?

- Low 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing 

- Tests have been added that prove the feature works

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- It requires further work in the Studio

2023-01-12 12:53 UTC, grisha-kotler requested changes

2023-01-12 12:53 UTC, grisha-kotler commented on test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
> +                var sw = new Stopwatch();
```suggestion
                var sw = Stopwatch.StartNew();
```

2023-01-12 12:53 UTC, grisha-kotler commented on test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
> +                var sw = new Stopwatch();
```suggestion
                var sw = Stopwatch.StartNew();
```

2023-01-12 12:53 UTC, grisha-kotler commented on test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
> +                var sw = new Stopwatch();
```suggestion
                var sw = Stopwatch.StartNew();
```

2023-01-12 12:53 UTC, grisha-kotler commented on test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
> +                var sw = new Stopwatch();
```suggestion
                var sw = Stopwatch.StartNew();
```

2023-01-12 19:45 UTC, ArieSLV commented on test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
> +                var sw = new Stopwatch();
Done.

2023-01-12 19:45 UTC, ArieSLV commented on test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
> +                var sw = new Stopwatch();
Done.

2023-01-12 19:45 UTC, ArieSLV commented on test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
> +                var sw = new Stopwatch();
Done.

2023-01-12 19:45 UTC, ArieSLV commented on test/SlowTests/Server/Documents/PeriodicBackup/PeriodicBackupSlowTests.cs
> +                var sw = new Stopwatch();
Done.

2023-01-16 11:29 UTC, grisha-kotler approved these changes

2023-01-16 11:56 UTC, ppekrol commented
Please check failing tests

2023-01-16 14:36 UTC, ppekrol commented
Can you rebase as well? We have updated .NET to 7.0.2

2023-01-16 14:47 UTC, ArieSLV commented
> Please check failing tests
> Can you rebase as well? We have updated .NET to 7.0.2

Done

2023-01-17 09:29 UTC, merged