RavenDB-19902 Add empty bucket list message
ravendb/ravendb pull request #15739
Opened 2023-02-01 11:52 UTC by mateuszbartosik

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-19902/Buckets-report-for-empty-database

### Additional description

Added a message that says the bucket list is empty.

_Please delete below the options that are not relevant_

### Type of change
- New feature

### How risky is the change?
- Not relevant

### Backward compatibility
- Not relevant

### Is it platform specific issue?
- No

### Documentation update
- No documentation update is needed 

### Testing by Contributor
- It has been verified by manual testing

### Testing by RavenDB QA team
- No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?
- No

### UI work
- No UI work is needed

2023-02-16 23:16 UTC, ml054 commented on src/Raven.Studio/wwwroot/App/views/database/status/bucketsReport.html
> +    <!-- ko if: node().internalChildren.length != 0 -->
!==

2023-02-16 23:16 UTC, ml054 commented on src/Raven.Studio/wwwroot/App/views/database/status/bucketsReport.html
> +    <!-- ko if: node().internalChildren.length == 0 -->
===

2023-02-16 23:16 UTC, ml054 requested changes
Please have a look at my comments.

2023-02-17 11:59 UTC, mateuszbartosik commented on src/Raven.Studio/wwwroot/App/views/database/status/bucketsReport.html
> +    <!-- ko if: node().internalChildren.length != 0 -->
Fixed

2023-02-17 11:59 UTC, mateuszbartosik commented on src/Raven.Studio/wwwroot/App/views/database/status/bucketsReport.html
> +    <!-- ko if: node().internalChildren.length == 0 -->
Fixed

2023-02-17 18:38 UTC, ml054 approved these changes

2023-02-18 17:16 UTC, merged