RavenDB-4323 Continue the work on PR #1567
ravendb/ravendb pull request #1595
Opened 2017-02-09 12:14 UTC by fitzchak

#1567

2017-02-09 13:39 UTC, ayende requested changes

2017-02-09 13:39 UTC, ayende commented on src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
> +                base.Commit(stats);
What happens if this throws?

2017-02-09 13:39 UTC, ayende commented on src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
> +                public LazyStringValue ReduceKeyHash;
Who owns the memory here?

2017-02-09 14:30 UTC, fitzchak commented on src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
> +                base.Commit(stats);
It will be handled as the higher level in indexing as before. 
Note that we had try..finally around this, not try..catch.

2017-02-09 14:30 UTC, fitzchak commented on src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
> +                public LazyStringValue ReduceKeyHash;
Working on this

2017-02-10 12:55 UTC, ayende commented on src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
> +                var propertyAccessor = PropertyAccessor.Create(reduceObject.GetType());
Shouldn't this be cached? See the impl in `AnonymousLuceneDocumentConverter.Getfields`

2017-02-10 12:56 UTC, merged

2017-02-12 14:24 UTC, fitzchak commented on src/Raven.Server/Documents/Indexes/Persistence/Lucene/OutputReduceIndexWriteOperation.cs
> +                var propertyAccessor = PropertyAccessor.Create(reduceObject.GetType());
https://github.com/ravendb/ravendb/pull/1606