RavenDB-20202: Cluster node health check issue when experiencing a timeout and topology update simultaneously.
ravendb/ravendb pull request #16121
Opened 2023-03-27 14:27 UTC by ArieSLV

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-20202/Cluster-node-health-check-issue-when-experiencing-a-timeout-and-topology-update-simultaneously.

### Additional description

The issue occurs when one of the nodes in the cluster becomes unavailable. The affected node is marked as failed in the node selector, and a health check timer is spawned to recheck the node's health after a specified period. Then, when the following events happen simultaneously:

1. An attempt is made to execute a command in the cluster, but none of the nodes respond, resulting in a timeout exception.
2. A topology update is performed.
3. A node health check is initiated to identify a healthy node.

A race condition arises where, after the topology update, we still have a "failed" flag on one of the nodes. However, the health check procedure for this node is not started due to the topology change.

As a result, the affected node is ignored when selecting a node for query execution because it has the "failed" flag, which is not cleared since the health check procedure has not been initiated.

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing by Contributor

- A test has been added that proves the fix is effective

### Testing by RavenDB QA team

- No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

2023-03-27 16:02 UTC, grisha-kotler requested changes

2023-03-27 16:02 UTC, grisha-kotler commented on src/Raven.Client/Http/RequestExecutor.cs
> +            var nodeIndex = _nodeSelector.GetRequestedNode(nodeStatus.Node.ClusterTag).Index;
It is possible that the node won't exist in the topology.

2023-03-27 16:02 UTC, grisha-kotler commented on test/SlowTests/Issues/RavenDB_20202.cs
> +        const string userName = "RavenDB-20202";
See the warning

2023-03-27 16:02 UTC, grisha-kotler commented on test/SlowTests/Issues/RavenDB_20202.cs
> +        const string userId = "user/1";
Also here

2023-03-28 06:22 UTC, ArieSLV commented on src/Raven.Client/Http/RequestExecutor.cs
> +            var nodeIndex = _nodeSelector.GetRequestedNode(nodeStatus.Node.ClusterTag).Index;
Done.

2023-03-28 06:23 UTC, ArieSLV commented on test/SlowTests/Issues/RavenDB_20202.cs
> +        const string userName = "RavenDB-20202";
Done.

2023-03-28 06:23 UTC, ArieSLV commented on test/SlowTests/Issues/RavenDB_20202.cs
> +        const string userId = "user/1";
Done.

2023-03-29 08:31 UTC, grisha-kotler approved these changes

2023-03-30 07:23 UTC, ppekrol approved these changes

2023-04-03 07:21 UTC, ayende approved these changes

2023-04-03 07:21 UTC, ayende commented on src/Raven.Client/Http/NodeSelector.cs
> +        internal int[] GetNodeSelectorFailures => _state.Failures;
Properties shouldn't start with `Get`

2023-04-03 07:21 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +            internal int[] GetNodeSelectorFailures => _requestExecutor._nodeSelector.GetNodeSelectorFailures;
```suggestion
            internal int[] NodeSelectorFailures => _requestExecutor._nodeSelector.NodeSelectorFailures;
```

2023-04-03 07:21 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +            internal ConcurrentDictionary<ServerNode, Lazy<NodeStatus>> GetFailedNodesTimers => _requestExecutor._failedNodesTimers;
```suggestion
            internal ConcurrentDictionary<ServerNode, Lazy<NodeStatus>> FailedNodesTimers => _requestExecutor._failedNodesTimers;
```

2023-04-03 07:21 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +            internal (int Index, ServerNode Node) GetPreferredNode => _requestExecutor._nodeSelector.GetPreferredNode();
```suggestion
            internal (int Index, ServerNode Node) PreferredNode => _requestExecutor._nodeSelector.GetPreferredNode();
```

2023-04-03 07:48 UTC, ArieSLV commented on src/Raven.Client/Http/NodeSelector.cs
> +        internal int[] GetNodeSelectorFailures => _state.Failures;
Done.

2023-04-03 07:48 UTC, ArieSLV commented on src/Raven.Client/Http/RequestExecutor.cs
> +            internal int[] GetNodeSelectorFailures => _requestExecutor._nodeSelector.GetNodeSelectorFailures;
Done.

2023-04-03 07:48 UTC, ArieSLV commented on src/Raven.Client/Http/RequestExecutor.cs
> +            internal ConcurrentDictionary<ServerNode, Lazy<NodeStatus>> GetFailedNodesTimers => _requestExecutor._failedNodesTimers;
Done.

2023-04-03 07:48 UTC, ArieSLV commented on src/Raven.Client/Http/RequestExecutor.cs
> +            internal (int Index, ServerNode Node) GetPreferredNode => _requestExecutor._nodeSelector.GetPreferredNode();
Done.

2023-04-03 09:25 UTC, ppekrol commented
@ArieSLV Please check failing test https://jenkins.hibernatingrhinos.com/job/PR_Tests/5730/testReport/junit/RachisTests/TopologyChangesTests/Adding_additional_node_that_goes_offline_and_then_online_should_still_work/

2023-04-03 11:54 UTC, ArieSLV commented
> @ArieSLV Please check failing test https://jenkins.hibernatingrhinos.com/job/PR_Tests/5730/testReport/junit/RachisTests/TopologyChangesTests/Adding_additional_node_that_goes_offline_and_then_online_should_still_work/
 
The reason for the failed test is not related to the changes in this pull request. I have re-run the test, and it passed successfully. I also ran the test on my local machine. It was completed successfully 50 out of 50 times in Debug mode and 100 out of 100 times in Release mode.

2023-04-04 11:01 UTC, merged