RavenDB-19743: Made Disabled configuration respected
ravendb/ravendb pull request #16287
Opened 2023-04-18 07:48 UTC by aharonlevy

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-19743/Disabled-configuration-not-respected

### Additional description

Found where the Disabled configuration is not respected,  
and added a check that will make sure that if disable is true, then we use the default identity separator
and not the one that the user provided

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Backward compatibility

- Not relevant

### Is it platform-specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing by Contributor

- Tests have been added that prove the fix is effective or that the feature works

### Testing by RavenDB QA team

- No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

2023-04-18 11:42 UTC, ppekrol commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +                if (record.Client?.Disabled ?? false)
Should't all of that be:
```
                IdentityPartsSeparator = record.Client is { Disabled: false }
                    ? record.Client.IdentityPartsSeparator ?? Constants.Identities.DefaultSeparator
                    : Constants.Identities.DefaultSeparator;
```

 ?

2023-04-18 12:31 UTC, aharonlevy commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +                if (record.Client?.Disabled ?? false)
TBH, I tried to implement it in one check but failed, so I made the 'if'.
Replaced the code with the one suggested here, and it works.
Pushing it with the change.

2023-04-18 14:46 UTC, garayx requested changes

2023-04-18 14:46 UTC, garayx commented on src/Raven.Client/Constants.cs
> +        public class Identities
we already have this class in v6.0, so lets use the same on:

https://github.com/ravendb/ravendb/blob/de44fd83233eddf0f7615eb6ee25271f990aa575/src/Raven.Client/Constants.cs#L471

2023-04-19 07:10 UTC, aharonlevy commented on src/Raven.Client/Constants.cs
> +        public class Identities
done

2023-04-19 11:18 UTC, garayx approved these changes
please check if the failing test fails because of this pr

2023-04-19 13:51 UTC, ppekrol commented on test/SlowTests/Issues/RavenDB_19743.cs
> +                {
shouldn't you set here `IdentityPartsSeparator = '!'` ?

2023-04-19 13:51 UTC, ppekrol commented
> please check if the failing test fails because of this pr

Known failure, we are investigating it

2023-04-20 06:16 UTC, aharonlevy commented on test/SlowTests/Issues/RavenDB_19743.cs
> +                {
I think that then it'll be the same as `DisabledConfigurationBaseCase` wanted to assert that when Disable is set as true, it'll be respected

2023-04-20 06:29 UTC, merged