RavenDB-6322 Initial implementation of RavenFS using Tree.Stream
ravendb/ravendb pull request #1637
Opened 2017-02-14 15:04 UTC by fitzchak

2017-02-14 16:51 UTC, ayende requested changes

2017-02-14 16:51 UTC, ayende commented on src/Raven.Server/Documents/DocumentsStorage.cs
> -        private UnmanagedBuffersPoolWithLowMemoryHandling _unmanagedBuffersPool;
Why do we have these modicaitions to the documents storage?

2017-02-14 16:51 UTC, ayende commented on src/Raven.Server/Files/FileSystem.cs
> +                Dispose();
You are losing the exception here. If we have an error during startup, we are now in a strange invalid state.

2017-02-14 16:51 UTC, ayende commented on src/Raven.Server/Files/FileSystem.cs
> +            var exceptionAggregator = new ExceptionAggregator(_logger, $"Could not dispose {nameof(FileSystem)}");
Include the fs name?

2017-02-14 16:51 UTC, ayende commented on src/Raven.Server/Files/FileSystemFile.cs
> +        public VoronStream Stream;
Why VoronStream and not just Stream?

2017-02-14 16:51 UTC, ayende commented on src/Raven.Server/Files/FilesStorage.cs
> +                options.Dispose();
options should probably the last disposed.

2017-02-14 16:51 UTC, ayende commented on src/Raven.Server/Files/Handlers/FileHandler.cs
> +        [RavenAction("/filesystem|s|fs/#1#docs", "HEAD", "/databases/{databaseName:string}/docs?id={documentId:string}")]
What are all those `|` in the route? and the docs is wrong.

2017-02-14 16:51 UTC, ayende commented on src/Raven.Server/Files/Handlers/FileHandler.cs
> +        public Task Get()
Bad route

2017-02-14 16:51 UTC, ayende commented on src/Raven.Server/Files/Handlers/FileHandler.cs
> +            if (string.IsNullOrEmpty(transformerName) == false)
huh?

2017-02-14 16:51 UTC, ayende commented on src/Raven.Server/Files/Handlers/FileHandler.cs
> +        private void GetDocumentsById(DocumentsOperationContext context, StringValues ids, Transformer transformer, bool metadataOnly)
This entire file needs to be removed.

2017-02-14 16:51 UTC, ayende commented on src/Raven.Server/ServerWide/Context/FilesContextPool.cs
> +            return new FilesOperationContext(_fileSystem, 1024*1024, 16*1024);
32 bits handling is missing

2017-02-14 16:51 UTC, ayende commented on test/FilesTests/RavenFilesTestBase.cs
> +﻿// -----------------------------------------------------------------------
We'll need to merge this with the `FastTests` (for now) code.
We don't want to have too many test proejcts.

For now it is fine while you are just looking at those, but we won't keep it long term

2017-02-14 16:51 UTC, ayende commented on test/FilesTests/Storage/StorageStreamTest.cs
> +    public class StorageStreamTest : RavenFilesTestBase
don't commit commented files

2017-02-14 20:04 UTC, merged

2017-02-15 08:07 UTC, arekpalinski commented on src/Raven.Server/Files/FileSystemFile.cs
> +    public class FileSystemFile
Why not to name it just `File`?

2017-02-15 08:19 UTC, arekpalinski commented on src/Raven.Server/ServerWide/Context/FilesOperationContext.cs
> +        {
Code duplication: this method is exactly the same as in `DocumentsOperationContext`

2017-02-15 08:20 UTC, arekpalinski commented on src/Raven.Server/ServerWide/Context/FilesOperationContext.cs
> +        {
We need to have a single method in a base class

2017-02-15 08:23 UTC, arekpalinski commented on src/Raven.Server/ServerWide/Context/FilesOperationContext.cs
> +            if ((options.TransactionsMode == TransactionsMode.Lazy || options.TransactionsMode == TransactionsMode.Danger) &&
Also the same logic as in `DocumentsOperationContext`

2017-02-15 08:24 UTC, arekpalinski commented on src/Raven.Server/ServerWide/Context/FilesOperationContext.cs
> +        public bool ShouldRenewTransactionsToAllowFlushing()
The same as in `DocumentsOperationContext`

2017-02-15 08:35 UTC, fitzchak commented on src/Raven.Server/Documents/DocumentsStorage.cs
> -        private UnmanagedBuffersPoolWithLowMemoryHandling _unmanagedBuffersPool;
_unmanagedBuffersPool no one is using this. As I went over this code I made there a few improvements. We should convert all strings there so using Slices.

2017-02-15 08:36 UTC, fitzchak commented on src/Raven.Server/Files/FileSystem.cs
> +                Dispose();
If so, this is exactly how it is in DocumetnsStorage. We losing the exception only in one implementation of the Initialize but not in the other... which looks strange.

2017-02-15 08:36 UTC, fitzchak commented on src/Raven.Server/Files/FileSystem.cs
> +            var exceptionAggregator = new ExceptionAggregator(_logger, $"Could not dispose {nameof(FileSystem)}");
ok, will do so also for DocumentsStorage.

2017-02-15 08:39 UTC, fitzchak commented on src/Raven.Server/Files/FileSystemFile.cs
> +        public VoronStream Stream;
In order to have also the length. This is not exposed to the client, it is part of the server.

2017-02-15 08:42 UTC, fitzchak commented on src/Raven.Server/Files/FilesStorage.cs
> +                options.Dispose();
OK. Will change this also in DocumentsStorage.Initialize(options)

2017-02-15 08:42 UTC, fitzchak commented on src/Raven.Server/Files/Handlers/FileHandler.cs
> +        [RavenAction("/filesystem|s|fs/#1#docs", "HEAD", "/databases/{databaseName:string}/docs?id={documentId:string}")]
FileHandler is a WIP - should not be commited

2017-02-15 08:45 UTC, fitzchak commented on test/FilesTests/RavenFilesTestBase.cs
> +﻿// -----------------------------------------------------------------------
I think it is better to be isolated, so if you work on FS you can run just those tests and if you word of documents you don't care about those tests.
But if you do not agree, I will merge them now.

2017-02-15 08:46 UTC, fitzchak commented on src/Raven.Server/Files/FileSystemFile.cs
> +    public class FileSystemFile
Because of conflicting with System.IO.File name

2017-02-15 08:49 UTC, fitzchak commented on src/Raven.Server/ServerWide/Context/FilesOperationContext.cs
> +        {
Done

2017-02-15 08:50 UTC, arekpalinski commented on src/Raven.Server/Files/FileSystemFile.cs
> +    public class FileSystemFile
That won't be a problem for us. If we have any usage of those two in the same class (I don't think so) we can use full qualified names then.

2017-02-15 08:50 UTC, fitzchak commented on src/Raven.Server/ServerWide/Context/FilesOperationContext.cs
> +        public bool ShouldRenewTransactionsToAllowFlushing()
It is OK to have the duplication now, as I just start to see what is needed by the FileSystem. Once it will be solid we will merge staff.

2017-02-15 11:19 UTC, ayende commented on src/Raven.Server/Files/FileSystem.cs
> +                Dispose();
Please fix both

2017-02-15 11:20 UTC, ayende commented on test/FilesTests/RavenFilesTestBase.cs
> +﻿// -----------------------------------------------------------------------
Yes, that is fine for now, not in the long run, though