RavenDB-20684 - Check Raven.Server.Exceptions.MissingAttachmentException
ravendb/ravendb pull request #16644
Opened 2023-06-13 10:32 UTC by shiranshalom

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-20684

**_Issue explanation:_**
Steps of deleting attachment operation (only one reference exists) of a document (document without revisions, revisions configuration is defined):

1. Deleting the attachment from `AttachmentsSchema` - no reference to this attachment exists.
2. Updating the document:
         2.1. Update document metadata
         2.2. Create revision for the old version:
            2.2.1. Create attachment revision: seeking for the relevant attachment in `AttachmentsSchema` by `documentId` - the entry is already deleted (step 1) -> nothing happens; therefore, because no reference to the stream exists, at the end of the transaction, the stream is removed.

**_Fix:_**
Changed step 2.2.1 - collect attachments from old document metadata.

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing by Contributor

- Tests have been added that prove the fix is effective or that the feature works
- It has been verified by manual testing

### Testing by RavenDB QA team

- No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

2023-06-13 10:45 UTC, ayende requested changes
Please explain, both in the commit and the PR, the logic behind those changes.

2023-06-13 10:45 UTC, ayende commented on src/Raven.Server/Documents/AttachmentsStorage.cs
> +                .Select(attachment => JsonDeserializationClient.AttachmentName(attachment));
Let's avoid using Linq here, that creates allocations that we would like to avoid

2023-06-13 11:15 UTC, shiranshalom commented on src/Raven.Server/Documents/AttachmentsStorage.cs
> +                .Select(attachment => JsonDeserializationClient.AttachmentName(attachment));
done

2023-06-13 13:41 UTC, shiranshalom commented
> Please explain, both in the commit and the PR, the logic behind those changes.

Done

2023-06-14 09:08 UTC, karmeli87 approved these changes

2023-06-14 12:05 UTC, merged