RavenDB-16659 Deleting the database during a restore will throw an ex…
ravendb/ravendb pull request #17041
Opened 2023-08-14 13:28 UTC by efratshenhar

…ception

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-16659

### Additional description

We don't want to delete a database during a restore due to https://issues.hibernatingrhinos.com/issue/RDBCL-1827/Database-stuck-deleting-when-deleted-during-restore. 
We will throw an exception instead 

_Please delete below the options that are not relevant_

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing by Contributor

- Tests have been added that prove the fix is effective or that the feature works

### Testing by RavenDB QA team

- No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

2023-08-14 13:41 UTC, grisha-kotler commented
Let's also check if the delete button is visible in the studio while the restore is in progress.
If it is, we need to hide it.

2023-08-15 10:33 UTC, grisha-kotler requested changes

2023-08-15 10:33 UTC, grisha-kotler commented on src/Raven.Server/ServerWide/ServerStore.cs
> +            internal Action AfterSavingDatabaseRecored;
```suggestion
            internal Action RestoreDatabaseAfterSavingDatabaseRecord;
```

2023-08-15 10:33 UTC, grisha-kotler commented on src/Raven.Server/Web/System/AdminDatabasesHandler.cs
> +                                throw new InvalidOperationException($"Can't delete database {databaseName} while restore is in progress.");
```suggestion
                                throw new InvalidOperationException($"Can't delete database '{databaseName}' while the restore process is in progress. In order to delete the database, you can cancel it from node {node}.");
```
You should be able to get the `node` from the topology.

2023-08-15 10:33 UTC, grisha-kotler commented on test/SlowTests/Issues/RavenDB-16659.cs
> +        {
Don't reuse this server.

2023-08-15 10:33 UTC, grisha-kotler commented on test/SlowTests/Issues/RavenDB-16659.cs
> +        private readonly int _reasonableTimeout = Debugger.IsAttached ? 60000 : 30000;
Not needed

2023-08-16 07:29 UTC, efratshenhar commented on src/Raven.Server/ServerWide/ServerStore.cs
> +            internal Action AfterSavingDatabaseRecored;
done

2023-08-16 07:29 UTC, efratshenhar commented on src/Raven.Server/Web/System/AdminDatabasesHandler.cs
> +                                throw new InvalidOperationException($"Can't delete database {databaseName} while restore is in progress.");
done

2023-08-16 07:29 UTC, efratshenhar commented on test/SlowTests/Issues/RavenDB-16659.cs
> +        {
done

2023-08-16 07:29 UTC, efratshenhar commented on test/SlowTests/Issues/RavenDB-16659.cs
> +        private readonly int _reasonableTimeout = Debugger.IsAttached ? 60000 : 30000;
done

2023-08-24 15:53 UTC, grisha-kotler requested changes

2023-08-24 15:53 UTC, grisha-kotler commented on src/Raven.Server/Web/System/AdminDatabasesHandler.cs
> +                                                                    $"you can cancel it from node {rawRecord.Topology.Members[0]}");
```suggestion
                                                                    $"you can cancel the restore task from node {rawRecord.Topology.Members[0]}");
```

2023-08-24 15:55 UTC, grisha-kotler requested changes

2023-08-24 15:55 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
> +                        _serverStore.ForTestingPurposesOnly()?.RestoreDatabaseAfterSavingDatabaseRecord.Invoke();
```suggestion
                        _serverStore.ForTestingPurposesOnly?.RestoreDatabaseAfterSavingDatabaseRecord?.Invoke();
```

2023-08-24 15:55 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
> +                        _serverStore.ForTestingPurposesOnly()?.RestoreDatabaseAfterSavingDatabaseRecord.Invoke();
This is probably the reason why the tests fail

2023-08-28 08:57 UTC, efratshenhar commented on src/Raven.Server/Documents/PeriodicBackup/Restore/RestoreBackupTaskBase.cs
> +                        _serverStore.ForTestingPurposesOnly()?.RestoreDatabaseAfterSavingDatabaseRecord.Invoke();
done

2023-08-28 08:57 UTC, efratshenhar commented on src/Raven.Server/Web/System/AdminDatabasesHandler.cs
> +                                                                    $"you can cancel it from node {rawRecord.Topology.Members[0]}");
done

2023-08-28 10:42 UTC, grisha-kotler approved these changes

2023-08-29 07:17 UTC, ppekrol commented on test/SlowTests/Issues/RavenDB-16659.cs
> +                    mre.Wait();
no timeout here, please add a timeout, can be high e.g. 30s and assert if it was true.

2023-08-30 07:59 UTC, efratshenhar commented on test/SlowTests/Issues/RavenDB-16659.cs
> +                    mre.Wait();
done

2023-08-30 09:14 UTC, merged