RavenDB-21504 Forcing update of expired license is successful but doe…
ravendb/ravendb pull request #17494
Opened 2023-10-10 07:24 UTC by efratshenhar

…sn't work

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-21504

### Additional description

Return information when the license update was unsuccessful.

### Type of change

- Bug fix

### How risky is the change?

- Low 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing by Contributor

- It has been verified by manual testing

### Testing by RavenDB QA team

- No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.

2023-10-10 09:10 UTC, grisha-kotler requested changes

2023-10-10 09:10 UTC, grisha-kotler commented on src/Raven.Server/Web/Studio/LicenseHandler.cs
> +using System.Security.Cryptography;
Is it needed?

2023-10-10 09:10 UTC, grisha-kotler commented on src/Raven.Server/Web/Studio/LicenseHandler.cs
> +                    ["Message"] = updated ? "License was updated Successfully" : "Unable to update license"
```suggestion
                    ["Message"] = updated ? "License was updated Successfully" : "The license wasn't modified"
```

2023-10-10 09:59 UTC, efratshenhar commented on src/Raven.Server/Web/Studio/LicenseHandler.cs
> +using System.Security.Cryptography;
no. removed

2023-10-10 13:47 UTC, efratshenhar commented on src/Raven.Server/Web/Studio/LicenseHandler.cs
> +                    ["Message"] = updated ? "License was updated Successfully" : "Unable to update license"
done

2023-10-10 18:00 UTC, grisha-kotler requested changes

2023-10-10 18:00 UTC, grisha-kotler commented on src/Raven.Server/Web/Studio/LicenseHandler.cs
> +                context.Write(writer, new DynamicJsonValue
Let's add a class with an enum with 2 states:
`Updated` and `NotModified` and return that.

2023-10-11 08:55 UTC, efratshenhar commented on src/Raven.Server/Web/Studio/LicenseHandler.cs
> +                context.Write(writer, new DynamicJsonValue
done

2023-10-11 09:30 UTC, grisha-kotler approved these changes

2023-10-12 13:43 UTC, merged