RavenDB-20628_v6.0 - Cluster wide transaction : throw `TaskCanceledException` when fails on timeout
ravendb/ravendb pull request #17657
Opened 2023-11-07 08:37 UTC by shaharhikri

Draft

2023-11-16 15:47 UTC, karmeli87 commented
please check failing tests

2023-11-29 13:44 UTC, karmeli87 requested changes

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +        using var _ = CreateClusterTransactionTask(id: options.TaskId, index, out var onDatabaseCompletionTask);
if you don't care about the value here why not to return `IDisposable`

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +            array.Add(new DynamicJsonValue { ["Type"] = clusterCommands.Type, ["Key"] = clusterCommands.Id, ["Index"] = index });
formatting

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Sharding/Handlers/Processors/Batches/ShardedClusterTransactionRequestProcessor.cs
> +        t.Start();
What is that???

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Sharding/Handlers/Batches/ShardedBatchHandler.cs
> +            // var database = await Server.ServerStore.DatabasesLandlord.TryGetOrCreateResourceStore(DatabaseName);
?

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +    protected static string GenerateChangeVector(long index, long count, bool? disableAtomicDocumentWrites, string databaseGroupId, string clusterTransactionId)
don't we already have method like this?

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +using Elastic.Clients.Elasticsearch;
?

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +    protected abstract void GenerateDatabaseCommandsEvaluatedResults(List<ClusterTransactionDataCommand> databaseCommands,
why not to return `DynamicJsonArray` here?

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +            array.Add(new DynamicJsonValue { ["Type"] = clusterCommands.Type, ["Key"] = clusterCommands.Id, ["Index"] = index });
use `nameof(...)`

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/Processors/Batches/ClusterTransactionRequestProcessor.cs
> +            using (RequestHandler.ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
why do you need that?

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Sharding/Handlers/Processors/Batches/ShardedBatchHandlerProcessorForBulkDocs.cs
> +using Raven.Server.Web;
revert this file

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Sharding/Handlers/Processors/Batches/ShardedClusterTransactionRequestProcessor.cs
> +using GeoAPI.CoordinateSystems;
?

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Sharding/Handlers/Processors/Batches/ShardedClusterTransactionRequestProcessor.cs
> +        using (RequestHandler.ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
why do you need a context here?

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Documents/Sharding/Handlers/Processors/Batches/ShardedClusterTransactionRequestProcessor.cs
> +        t.Start();
and you always return `null` here, is that correct?

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Rachis/ClusterTransactionWaiter.cs
> +    public sealed class ClusterTransactionWaiter : AsyncWaiter<long?>
let's keep the `ClusterTransactionCompletionResult` class here, but change the internals of it

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Rachis/ClusterTransactionWaiter.cs
> +    public sealed class ClusterTransactionWaiter : AsyncWaiter<long?>
or probably `ClusterTransactionResult` is even better?

2023-11-29 13:44 UTC, karmeli87 commented on src/Raven.Server/Rachis/ClusterTransactionWaiter.cs
> +    public sealed class ClusterTransactionWaiter : AsyncWaiter<long?>
let's replace all places of `long?` with `ClusterTransactionResult`

2023-12-04 10:46 UTC, shaharhikri commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +        using var _ = CreateClusterTransactionTask(id: options.TaskId, index, out var onDatabaseCompletionTask);
Done

2023-12-04 10:47 UTC, shaharhikri commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +            array.Add(new DynamicJsonValue { ["Type"] = clusterCommands.Type, ["Key"] = clusterCommands.Id, ["Index"] = index });
Done

2023-12-04 11:04 UTC, shaharhikri commented on src/Raven.Server/Documents/Sharding/Handlers/Processors/Batches/ShardedClusterTransactionRequestProcessor.cs
> +        t.Start();
Yes, it is correct..
because if you don't have the result here you know that was a failover and then you will take the count from other places ..

> What is that???

Cahnged to `Task.FromResult<long?>(null).WithCancellation(token)`

2023-12-04 11:05 UTC, shaharhikri commented on src/Raven.Server/Documents/Sharding/Handlers/Batches/ShardedBatchHandler.cs
> +            // var database = await Server.ServerStore.DatabasesLandlord.TryGetOrCreateResourceStore(DatabaseName);
Removed

2023-12-04 11:05 UTC, shaharhikri commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +    protected static string GenerateChangeVector(long index, long count, bool? disableAtomicDocumentWrites, string databaseGroupId, string clusterTransactionId)
Nope

2023-12-04 11:05 UTC, shaharhikri commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +using Elastic.Clients.Elasticsearch;
Removed

2023-12-04 11:07 UTC, shaharhikri commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +    protected abstract void GenerateDatabaseCommandsEvaluatedResults(List<ClusterTransactionDataCommand> databaseCommands,
because you don't always have database commands.. 
look at the 'AbstractClusterTransactionRequestProcessor.ProcessAsync' where we call GenerateDatabaseCommandsEvaluatedResults

2023-12-04 11:23 UTC, shaharhikri commented on src/Raven.Server/Documents/Handlers/Processors/Batches/AbstractClusterTransactionRequestProcessor.cs
> +            array.Add(new DynamicJsonValue { ["Type"] = clusterCommands.Type, ["Key"] = clusterCommands.Id, ["Index"] = index });
Done

2023-12-04 11:27 UTC, shaharhikri commented on src/Raven.Server/Documents/Handlers/Processors/Batches/ClusterTransactionRequestProcessor.cs
> +            using (RequestHandler.ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
Removed

2023-12-04 11:29 UTC, shaharhikri commented on src/Raven.Server/Documents/Sharding/Handlers/Processors/Batches/ShardedBatchHandlerProcessorForBulkDocs.cs
> +using Raven.Server.Web;
Done

2023-12-04 11:30 UTC, shaharhikri commented on src/Raven.Server/Documents/Sharding/Handlers/Processors/Batches/ShardedClusterTransactionRequestProcessor.cs
> +using GeoAPI.CoordinateSystems;
Removed

2023-12-04 11:30 UTC, shaharhikri commented on src/Raven.Server/Documents/Sharding/Handlers/Processors/Batches/ShardedClusterTransactionRequestProcessor.cs
> +        using (RequestHandler.ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
Yes

2023-12-17 08:12 UTC, closed without merging

2023-12-17 08:13 UTC, shaharhikri commented
closed because another PR was opened with the updated requirements and behavior:
https://github.com/ravendb/ravendb/pull/17871