RavenDB-21617 Fix replication loop for document & attachment tombstones
ravendb/ravendb pull request #17729
Opened 2023-11-20 08:49 UTC by karmeli87

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-21617

### Additional description

1. Fix replication loop that was caused due to having multiple tombstones and comparing against an out dated one, causing bumping the etag and replicate it over and over again.

The fixes seems to to affect only 6.0, I was unable to create the same conditions in 5.4 due to a different code here:
6.0
https://github.com/ravendb/ravendb/blob/91b1c3246a5699be0749fc21565f7e7ddf5d0087/src/Raven.Server/Documents/Replication/ConflictManager.cs#L276
5.4
https://github.com/ravendb/ravendb/blob/41c0797f5f5bc5d6b9bbf0a9cd06db251d1297a7/src/Raven.Server/Documents/Replication/ConflictManager.cs#L276

2. conflict on attachment tombstone was resolved and put with not the merged change vector which caused sending it over again. 
Also, here is seems to be manifested only in a 6.0 sharded database, which has a different change vector format. 

I believe that those issues are the root cause to the timeouts that we had in the tests, since external replication loop would cause an excessive amount of raft commands to be generated and choke the cluster tx merger

### Type of change

- Bug fix

### How risky is the change?

- Moderate 

### Backward compatibility

- Non breaking change

### Is it platform specific issue?

- No

### Documentation update

- No documentation update is needed 

### Testing by Contributor

- Current tests coverage
- It has been verified by manual testing

### Testing by RavenDB QA team

- No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- No

### UI work

- No UI work is needed

2023-11-20 14:02 UTC, shiranshalom requested changes

2023-11-20 14:02 UTC, shiranshalom commented on src/Raven.Server/Documents/DocumentsStorage.cs
> +                    mostRecent = current;
why we have `mostRecent = current;` here and also in line 1018? `mostRecent` can be null in that case? when we get `ConflictStatus.Update` if `mostRecent = current;`? :-)

2023-11-20 16:48 UTC, karmeli87 commented on src/Raven.Server/Documents/DocumentsStorage.cs
> +                    mostRecent = current;
you are absolutely right :-)

2023-11-21 09:17 UTC, shiranshalom approved these changes

2023-11-21 12:01 UTC, merged