RavenDB-22031 - Raft log is not truncated in followers
ravendb/ravendb pull request #18082
Opened 2024-02-01 13:30 UTC by shaharhikri

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-22031/Raft-log-is-not-truncated

### Additional description

Raft log is not truncated in followers, which caused the log history table to not clear.
This happened due to the fact that the leader did not update the variable `LowestIndexInEntireCluster`, which caused the follower ambassador to always send the follower `LowestIndexInEntireCluster` with a value of 0.

### Type of change

- [ ] Bug fix
- [ ] Regression bug fix
- [ ] Optimization
- [ ] New feature

### How risky is the change?

- [ ] Low 
- [ ] Moderate 
- [ ] High
- [ ] Not relevant

### Backward compatibility

- [ ] Non breaking change
- [ ] Ensured. Please explain how has it been implemented?
- [ ] Breaking change
- [ ] Not relevant

### Is it platform specific issue?

- [ ] Yes. Please list the affected platforms.
- [ ] No

### Documentation update

- [ ] This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.
- [ ] No documentation update is needed 

### Testing by Contributor

- [ ] Tests have been added that prove the fix is effective or that the feature works
- [ ] Internal classes added to the test class (e.g. entity or index definition classes) have the lowest possible access modifier (preferable `private`) 
- [ ] It has been verified by manual testing

### Testing by RavenDB QA team

- [ ] This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.
- [ ] No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- [ ] Yes. Please list the affected features/subsystems and provide appropriate explanation
- [ ] No

### UI work

- [ ] It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.
- [ ] No UI work is needed

2024-02-01 14:06 UTC, karmeli87 approved these changes

2024-02-01 15:26 UTC, karmeli87 requested changes

2024-02-01 15:26 UTC, karmeli87 commented on test/SlowTests/Issues/RavenDB-22031.cs
> +            }
why?

2024-02-01 15:26 UTC, karmeli87 commented on test/SlowTests/Issues/RavenDB-22031.cs
> +        for (int i = 0; i < 2100; i++)
is that necessary to have so many commands? 10 isn't enough?

2024-02-01 22:21 UTC, ppekrol commented on test/SlowTests/Issues/RavenDB-22031.cs
> +    public async Task RaftLogTrancateShouldWorkOnFollowers()
fact :)

2024-02-04 05:43 UTC, shaharhikri commented on test/SlowTests/Issues/RavenDB-22031.cs
> +    public async Task RaftLogTrancateShouldWorkOnFollowers()
Done

2024-02-04 11:26 UTC, shaharhikri commented on test/SlowTests/Issues/RavenDB-22031.cs
> +            }
Deleted

2024-02-04 11:26 UTC, shaharhikri commented on test/SlowTests/Issues/RavenDB-22031.cs
> +        for (int i = 0; i < 2100; i++)
You right. I changed it to 10.

2024-02-04 11:51 UTC, karmeli87 approved these changes

2024-02-05 11:18 UTC, merged