RavenDB-22217 - WaitForIndexNotification isn't waiting until the command is done
ravendb/ravendb pull request #18402
Opened 2024-04-16 08:00 UTC by shaharhikri

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-22217/WaitForIndexNotification-isnt-waiting-until-the-command-is-done

### Additional description

There is a race between updating the LastModifiedIndex when we have a database record change and a value was changed.
This would result in returning that we successfully completed the database record operation although it haven't been started yet.

### Type of change

- [ ] Bug fix
- [ ] Regression bug fix
- [ ] Optimization
- [ ] New feature

### How risky is the change?

- [ ] Low 
- [ ] Moderate 
- [ ] High
- [ ] Not relevant

### Backward compatibility

- [ ] Non breaking change
- [ ] Ensured. Please explain how has it been implemented?
- [ ] Breaking change
- [ ] Not relevant

### Is it platform specific issue?

- [ ] Yes. Please list the affected platforms.
- [ ] No

### Documentation update

- [ ] This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.
- [ ] No documentation update is needed 

### Testing by Contributor

- [ ] Tests have been added that prove the fix is effective or that the feature works
- [ ] Internal classes added to the test class (e.g. entity or index definition classes) have the lowest possible access modifier (preferable `private`) 
- [ ] It has been verified by manual testing

### Testing by RavenDB QA team

- [ ] This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.
- [ ] No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- [ ] Yes. Please list the affected features/subsystems and provide appropriate explanation
- [ ] No

### UI work

- [ ] It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.
- [ ] No UI work is needed

2024-04-16 13:52 UTC, karmeli87 requested changes

2024-04-16 13:52 UTC, karmeli87 commented on src/Raven.Server/Documents/DatabaseRaftIndexNotifications.cs
> +    private readonly Queue<DatabaseNotification> _recentNotifications = new Queue<DatabaseNotification>();
`_recentNotifications` seems to be relevant for both. So, let's make it generic.

2024-04-16 13:52 UTC, karmeli87 commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +    public class RachisLogIndexNotifications : AbstractRaftIndexNotifications
move it to a new file, this way it will be easier to merge it to 6.0, I think.

2024-04-17 10:02 UTC, karmeli87 approved these changes

2024-04-22 10:10 UTC, arekpalinski commented
@grisha-kotler I'm merging this but please review once you're back

2024-04-22 10:11 UTC, merged