RavenDB-22130 - Add Debug Info
ravendb/ravendb pull request #18861
Opened 2024-07-15 08:50 UTC by shaharhikri

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-22130/SlowTests.Issues.RavenDB21173.ClusterTransactionFailoverShouldntThrowConcurrencyExceptionoptions-DatabaseMode-Sharded

### Additional description

ClusterTransaction_Failover_Shouldnt_Throw_ConcurrencyException fails on Sharding with concurrency exception

### Type of change

- [ ] Bug fix
- [ ] Regression bug fix
- [ ] Optimization
- [ ] New feature

### How risky is the change?

- [ ] Low 
- [ ] Moderate 
- [ ] High
- [ ] Not relevant

### Backward compatibility

- [ ] Non breaking change
- [ ] Ensured. Please explain how has it been implemented?
- [ ] Breaking change
- [ ] Not relevant

### Is it platform specific issue?

- [ ] Yes. Please list the affected platforms.
- [ ] No

### Documentation update

- [ ] This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.
- [ ] No documentation update is needed 

### Testing by Contributor

- [ ] Tests have been added that prove the fix is effective or that the feature works
- [ ] Internal classes added to the test class (e.g. entity or index definition classes) have the lowest possible access modifier (preferable `private`) 
- [ ] It has been verified by manual testing

### Testing by RavenDB QA team

- [ ] This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.
- [ ] No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- [ ] Yes. Please list the affected features/subsystems and provide appropriate explanation
- [ ] No

### UI work

- [ ] It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.
- [ ] No UI work is needed

2024-07-16 12:18 UTC, karmeli87 requested changes

2024-07-16 12:18 UTC, karmeli87 commented on src/Raven.Server/Config/Categories/ClusterConfiguration.cs
> +        [Description("Maximum number of entires to keep in the RachisLogIndexNotifications.")]
I don't know if I like those configurations... let's try to avoid them

2024-07-16 12:18 UTC, karmeli87 commented on test/SlowTests/Issues/RavenDB-21173.cs
> +            throw e;
fix this warning please

2024-07-16 12:18 UTC, karmeli87 commented on src/Raven.Server/ServerWide/AbstractRaftIndexNotifications.cs
> +    private readonly int _recentNotificationsMaxEntries;
make this public and modify it directly from the test

2024-07-18 12:23 UTC, shaharhikri commented on src/Raven.Server/Config/Categories/ClusterConfiguration.cs
> +        [Description("Maximum number of entires to keep in the RachisLogIndexNotifications.")]
I can't avoid that because then I'll need to change this number for all project, this is hardcoded (value: 50)

2024-07-18 12:47 UTC, shaharhikri commented on src/Raven.Server/Config/Categories/ClusterConfiguration.cs
> +        [Description("Maximum number of entires to keep in the RachisLogIndexNotifications.")]
Done

2024-07-18 12:47 UTC, shaharhikri commented on test/SlowTests/Issues/RavenDB-21173.cs
> +            throw e;
Done

2024-07-18 12:47 UTC, shaharhikri commented on src/Raven.Server/ServerWide/AbstractRaftIndexNotifications.cs
> +    private readonly int _recentNotificationsMaxEntries;
Done

2024-07-18 14:34 UTC, karmeli87 approved these changes

2024-07-19 05:27 UTC, merged