RavenDB-22531 - Fix OutOfCpuCredits Exception
ravendb/ravendb pull request #19000
Opened 2024-08-06 09:49 UTC by shaharhikri

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-...

### Additional description

The exception caused the heartbeats spam upon low CPU credits is
```
2024-08-06T12:47:22.6229009, 24, Information, Heartbeats supervisor from A to A in term 1, Raven.Server.ServerWide.Maintenance.ClusterMaintenanceSupervisor+ClusterNode, Exception was thrown while collecting info from A, EXCEPTION: System.InvalidOperationException: We have databases with 'NoChange' status, but our last report from this node is 'OutOfCredits'
   at Raven.Server.ServerWide.Maintenance.ClusterMaintenanceSupervisor.ClusterNode.UpdateNodeReportIfNeeded(ClusterNodeStatusReport nodeReport, List`1 unchangedReports) in D:\work\RavenDB-22531\sln\src\Raven.Server\ServerWide\Maintenance\ClusterMaintenanceSupervisor.cs:line 392
   at Raven.Server.ServerWide.Maintenance.ClusterMaintenanceSupervisor.ClusterNode.ListenToMaintenanceWorker() in D:\work\RavenDB-22531\sln\src\Raven.Server\ServerWide\Maintenance\ClusterMaintenanceSupervisor.cs:line 333
```
As we can see here:
![image](https://github.com/user-attachments/assets/b1fc83f1-0b55-4fb0-84f2-aaee592a6c92)
![image](https://github.com/user-attachments/assets/85f06008-2857-429e-9fe5-52e3b208e596)

### Type of change

- [ ] Bug fix
- [ ] Regression bug fix
- [ ] Optimization
- [ ] New feature

### How risky is the change?

- [ ] Low 
- [ ] Moderate 
- [ ] High
- [ ] Not relevant

### Backward compatibility

- [ ] Non breaking change
- [ ] Ensured. Please explain how has it been implemented?
- [ ] Breaking change
- [ ] Not relevant

### Is it platform specific issue?

- [ ] Yes. Please list the affected platforms.
- [ ] No

### Documentation update

- [ ] This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.
- [ ] No documentation update is needed 

### Testing by Contributor

- [ ] Tests have been added that prove the fix is effective or that the feature works
- [ ] Internal classes added to the test class (e.g. entity or index definition classes) have the lowest possible access modifier (preferable `private`) 
- [ ] It has been verified by manual testing

### Testing by RavenDB QA team

- [ ] This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.
- [ ] No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- [ ] Yes. Please list the affected features/subsystems and provide appropriate explanation
- [ ] No

### UI work

- [ ] It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.
- [ ] No UI work is needed

2024-08-06 10:02 UTC, karmeli87 requested changes

2024-08-06 10:02 UTC, karmeli87 commented on test/SlowTests/Issues/RavenDB-22531.cs
> +    public async Task Test()
better name

2024-08-06 10:02 UTC, karmeli87 commented on test/SlowTests/Issues/RavenDB-22531.cs
> +    private async Task<string> ReadFromWebSocket(ArraySegment<byte> buffer, WebSocket source)
don't we have such code somewhere? let's unify all those places

2024-08-06 10:02 UTC, karmeli87 commented on test/SlowTests/Issues/RavenDB-22531.cs
> +        var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
using ?

2024-08-06 10:02 UTC, karmeli87 commented on test/SlowTests/Issues/RavenDB-22531.cs
> +        await client.ConnectAsync(new Uri(url), CancellationToken.None);
let's use a token here

2024-08-06 10:35 UTC, shaharhikri commented on test/SlowTests/Issues/RavenDB-22531.cs
> +        var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
Done

2024-08-06 10:35 UTC, shaharhikri commented on test/SlowTests/Issues/RavenDB-22531.cs
> +        await client.ConnectAsync(new Uri(url), CancellationToken.None);
Done

2024-08-06 10:44 UTC, shaharhikri commented on test/SlowTests/Issues/RavenDB-22531.cs
> +    private async Task<string> ReadFromWebSocket(ArraySegment<byte> buffer, WebSocket source)
Done

2024-08-06 10:44 UTC, shaharhikri commented on test/SlowTests/Issues/RavenDB-22531.cs
> +    public async Task Test()
Done

2024-08-06 11:20 UTC, karmeli87 approved these changes

2024-08-06 14:41 UTC, merged

2024-08-07 06:30 UTC, gregolsky commented on src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
> +                        throw new ArgumentOutOfRangeException();
Maybe it's worth adding a message with information about what kind of status did we get?

2024-08-07 09:16 UTC, shaharhikri commented on src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
> +                        throw new ArgumentOutOfRangeException();
https://github.com/ravendb/ravendb/pull/19019