RavenDB-22986 - Improve the performance of getting the free pages count
ravendb/ravendb pull request #19430
Opened 2024-10-10 19:41 UTC by grisha-kotler

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-22986/Free-space-fragmentation

### Additional description

This is used when generating the storage report.
Instead of calling `AllPages`, which is expensive as it iterates over the entire StreamBitArray for all sections (reference: [AllPages](https://github.com/grisha-kotler/ravendb/blob/35351eaff1ae7145058dcd05bbb7d36642198527/src/Voron/Impl/FreeSpace/FreeSpaceHandling.cs#L321)), we can efficiently count the set bits using `BitOperations.PopCount`.

This will reduce overhead and improve performance by avoiding the full iteration.

### Type of change

- [ ] Bug fix
- [ ] Regression bug fix
- [ ] Optimization
- [ ] New feature

### How risky is the change?

- [ ] Low 
- [ ] Moderate 
- [ ] High
- [ ] Not relevant

### Backward compatibility

- [ ] Non breaking change
- [ ] Ensured. Please explain how has it been implemented?
- [ ] Breaking change
- [ ] Not relevant

### Is it platform specific issue?

- [ ] Yes. Please list the affected platforms.
- [ ] No

### Documentation update

- [ ] This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.
- [ ] No documentation update is needed 

### Testing by Contributor

- [ ] Tests have been added that prove the fix is effective or that the feature works
- [ ] Internal classes added to the test class (e.g. entity or index definition classes) have the lowest possible access modifier (preferable `private`) 
- [ ] It has been verified by manual testing

### Testing by RavenDB QA team

- [ ] This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.
- [ ] No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- [ ] Yes. Please list the affected features/subsystems and provide appropriate explanation
- [ ] No

### UI work

- [ ] It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.
- [ ] No UI work is needed

2024-10-13 15:02 UTC, ayende requested changes

2024-10-13 15:02 UTC, ayende commented on src/Voron/Impl/FreeSpace/StreamBitArray.cs
> +
Remove this

2024-10-13 15:02 UTC, ayende commented on src/Voron/Impl/FreeSpace/FreeSpaceHandling.cs
> +                    count += current.GetNumberOfSetBits();
```suggestion
                    count += current.Setcount;
```

2024-10-14 08:38 UTC, grisha-kotler commented on src/Voron/Impl/FreeSpace/StreamBitArray.cs
> +
done

2024-10-14 08:38 UTC, grisha-kotler commented on src/Voron/Impl/FreeSpace/FreeSpaceHandling.cs
> +                    count += current.GetNumberOfSetBits();
done

2024-10-15 10:00 UTC, merged