RavenDB-22849 - Have a separate backup status for each node
ravendb/ravendb pull request #19797
Opened 2024-12-16 12:29 UTC by lastav5

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-22849

### Additional description

### Type of change

- [ ] Bug fix
- [ ] Regression bug fix
- [x] Optimization
- [ ] New feature

### How risky is the change?

- [ ] Low 
- [x] Moderate 
- [ ] High
- [ ] Not relevant

### Backward compatibility

- [x] Non breaking change
- [ ] Ensured. Please explain how has it been implemented?
- [ ] Breaking change
- [ ] Not relevant

### Is it platform specific issue?

- [ ] Yes. Please list the affected platforms.
- [x] No

### Documentation update

- [x] This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.
- [ ] No documentation update is needed 

### Testing by Contributor

- [x] Tests have been added that prove the fix is effective or that the feature works
- [ ] Internal classes added to the test class (e.g. entity or index definition classes) have the lowest possible access modifier (preferable `private`) 
- [ ] It has been verified by manual testing

### Testing by RavenDB QA team

- [ ] This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.
- [ ] No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- [x] Yes. Please list the affected features/subsystems and provide appropriate explanation
            Compare exchange tombstones deletion and local tombstones deletion - tests added for these scenarios
- [ ] No

### UI work

- [ ] It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.
- [x] No UI work is needed

2025-01-22 20:54 UTC, grisha-kotler requested changes

2025-01-22 20:54 UTC, grisha-kotler commented on src/Raven.Server/ServerWide/Maintenance/ClusterNodeStatusReport.cs
> +            public override string ToString()
Why is it needed?

2025-01-22 20:54 UTC, grisha-kotler commented on src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
> +        public override string ToString()
Why is it needed?

2025-01-22 20:54 UTC, grisha-kotler commented on src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
> +        public static string GenerateItemName(string databaseName, string base64DbId, long taskId)
Can this be `internal`?

2025-01-22 20:54 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +            using (var tx = context.OpenWriteTransaction(TimeSpan.FromSeconds(5)))
Increase timeout to 1 minute

2025-01-22 20:54 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +                using (var tx = ctx.OpenWriteTransaction(TimeSpan.FromSeconds(5)))
Increase timeout to 1 minute

2025-01-22 20:54 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +        {
Debug assert that we have an open write transaction

2025-01-22 20:54 UTC, grisha-kotler commented on src/Raven.Server/ServerWide/Commands/PeriodicBackup/UpdatePeriodicBackupStatusCommand.cs
> +    // This command is for updating the cluster backup status only. We do not want this to touch the local backup status
Let's make it simpler so we might not need to open a write transaction at all and update the `BackupStatusStorage` here.

2025-01-22 20:54 UTC, grisha-kotler commented on src/Raven.Server/Utils/BackupUtils.cs
> +            serverStore.DatabaseInfoCache.BackupStatusStorage.InsertBackupStatus(status, databaseName, serverStore._env.Base64Id, status.TaskId);
Since we need to open a write transaction here, can we avoid it and do this only in case we were unable to send the command to the cluster?
Note that we need to save the status only on our server.

2025-01-23 09:12 UTC, lastav5 commented on src/Raven.Server/ServerWide/Maintenance/ClusterNodeStatusReport.cs
> +            public override string ToString()
For easier printing when debugging

2025-01-23 09:14 UTC, lastav5 commented on src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
> +        public static string GenerateItemName(string databaseName, string base64DbId, long taskId)
done

2025-01-23 09:19 UTC, lastav5 commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +            using (var tx = context.OpenWriteTransaction(TimeSpan.FromSeconds(5)))
done

2025-01-23 09:19 UTC, lastav5 commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +                using (var tx = ctx.OpenWriteTransaction(TimeSpan.FromSeconds(5)))
done

2025-01-23 09:25 UTC, lastav5 commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +        {
done

2025-01-23 11:10 UTC, lastav5 commented on src/Raven.Server/ServerWide/Commands/PeriodicBackup/UpdatePeriodicBackupStatusCommand.cs
> +    // This command is for updating the cluster backup status only. We do not want this to touch the local backup status
done. checking correct server by backup status' node tag

2025-01-23 11:10 UTC, lastav5 commented on src/Raven.Server/Utils/BackupUtils.cs
> +            serverStore.DatabaseInfoCache.BackupStatusStorage.InsertBackupStatus(status, databaseName, serverStore._env.Base64Id, status.TaskId);
Done

2025-01-23 11:14 UTC, lastav5 commented on src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
> +                    report.BackupStatuses.Count == 0)
I am checking for backwards compatibilty like this instead of allowing null in BackupStatues to avoid any possible NREs

2025-01-27 12:18 UTC, grisha-kotler requested changes

2025-01-27 12:18 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +        public SystemTime Time = new SystemTime();
Can be removed?

2025-01-27 12:18 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +                if (_logger.IsInfoEnabled)
The error handling should be done at the caller level.

2025-01-27 12:18 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +                            var table = ctx.Transaction.InnerTransaction.OpenTable(BackupStatusTableSchema, BackupStatusSchema.TableName);
`table` can be opened outside the `foreach`

2025-01-27 12:18 UTC, grisha-kotler commented on src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
> +        public override string ToString()
This is public API so I would like to avoid it.

2025-01-27 12:18 UTC, grisha-kotler commented on src/Raven.Server/Web/System/BackupDatabaseHandler.cs
> +            var fetchLocalStatus = GetBoolValueQueryString("fetchLocalStatus", required: false) ?? false;
Shouldn't this be set to `true`?

2025-01-27 12:18 UTC, grisha-kotler commented on src/Raven.Server/Web/System/BackupDatabaseHandler.cs
> +                       BackupUtils.GetLocalBackupStatusBlittable(ServerStore, context, name, taskId.Value) :
`GetLocalBackupStatusBlittable` is also fetching from the cluster, no?

2025-01-27 12:18 UTC, grisha-kotler commented on src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
> +        internal long _iteration;
Can this stay private?

2025-01-27 12:18 UTC, grisha-kotler commented on src/Raven.Server/Utils/BackupUtils.cs
> +        if (backupStatus == null ||
How will this work when we upgrade and old version?
And old version has only cluster backup status?

2025-01-27 12:19 UTC, lastav5 commented on src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
> +        public override string ToString()
Will internal be ok?

2025-01-27 12:21 UTC, lastav5 commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +        public SystemTime Time = new SystemTime();
done

2025-01-27 12:59 UTC, lastav5 commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +                if (_logger.IsInfoEnabled)
done

2025-01-27 13:00 UTC, lastav5 commented on src/Raven.Server/Documents/PeriodicBackup/BackupStatusStorage.cs
> +                            var table = ctx.Transaction.InnerTransaction.OpenTable(BackupStatusTableSchema, BackupStatusSchema.TableName);
done

2025-01-27 13:05 UTC, lastav5 commented on src/Raven.Server/Web/System/BackupDatabaseHandler.cs
> +            var fetchLocalStatus = GetBoolValueQueryString("fetchLocalStatus", required: false) ?? false;
We decided to leave the behavior of this ep as is - have it fetch the cluster status - and have `fetchLocalStatus` be for debugging purposes. Returning the cluster status is a good representation of the last progress of the backup globally and some studio places use it so we didn't want to change it

2025-01-27 13:07 UTC, lastav5 commented on src/Raven.Server/Web/System/BackupDatabaseHandler.cs
> +                       BackupUtils.GetLocalBackupStatusBlittable(ServerStore, context, name, taskId.Value) :
It is only fetching from the cluster if the local one doesn't exist - which will never happen unless we just upgraded from an old version

2025-01-27 13:09 UTC, lastav5 commented on src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
> +        internal long _iteration;
Yes, it's a leftover. Done

2025-01-27 13:10 UTC, lastav5 commented on src/Raven.Server/Utils/BackupUtils.cs
> +        if (backupStatus == null ||
https://github.com/ravendb/ravendb/pull/19797/files#diff-48b59d72c36f43db2e6bd24c703190548cde92bca28fef4c48b5bcf07742c3b9R561

2025-01-27 13:12 UTC, lastav5 commented on src/Raven.Client/Documents/Operations/Backups/PeriodicBackupStatus.cs
> +        public override string ToString()
Deleted

2025-01-28 17:52 UTC, grisha-kotler approved these changes

2025-01-30 05:32 UTC, karmeli87 commented on src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
> +                    if (_serverStore.DatabaseInfoCache.BackupStatusStorage.DeleteBackupStatusesByTaskIds(_database.Name, _serverStore._env.Base64Id, taskIdsStatusesToDelete) == false)
You are in a `Task` here (the tombstone cleaner runs as task) and `DeleteBackupStatusesByTaskIds` opens a write tx, so it might be blocking.

Can we move this to be part of the raft command for the updating the backup status.

2025-02-04 21:42 UTC, ppekrol commented on src/Raven.Server/Web/System/BackupDatabaseHandler.cs
> +            var fetchLocalStatus = GetBoolValueQueryString("fetchLocalStatus", required: false) ?? false;
type=Local|Cluster

2025-02-04 21:42 UTC, ppekrol commented on src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
> +        private long GetMinLastEtag(out HashSet<long> taskIdsStatusesToDelete)
better name of the method

2025-02-04 21:42 UTC, ppekrol commented on src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
> +                    if (_serverStore.DatabaseInfoCache.BackupStatusStorage.DeleteBackupStatusesByTaskIds(_database.Name, _serverStore._env.Base64Id, taskIdsStatusesToDelete) == false)
I also do not like a side effect of this method, get method is opening a write tx

2025-02-23 06:44 UTC, lastav5 commented on src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
> +                    if (_serverStore.DatabaseInfoCache.BackupStatusStorage.DeleteBackupStatusesByTaskIds(_database.Name, _serverStore._env.Base64Id, taskIdsStatusesToDelete) == false)
moved to UpdatePeriodicBackupStatusCommand

2025-02-23 06:44 UTC, lastav5 commented on src/Raven.Server/Web/System/BackupDatabaseHandler.cs
> +            var fetchLocalStatus = GetBoolValueQueryString("fetchLocalStatus", required: false) ?? false;
done

2025-02-23 06:44 UTC, lastav5 commented on src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
> +        private long GetMinLastEtag(out HashSet<long> taskIdsStatusesToDelete)
done

2025-03-31 21:26 UTC, ppekrol approved these changes

2025-05-18 08:43 UTC, closed without merging