RavenDB-23254 Default search analyzer not shown in UI
ravendb/ravendb pull request #19808
Opened 2024-12-17 14:52 UTC by M4xymm

### Issue link

https://issues.hibernatingrhinos.com/issue/RavenDB-23254

Added autocomplete on choosing index, if database settings have changed values like Indexing.Analyzers...

### Type of change

- [ ] Bug fix
- [ ] Regression bug fix
- [ ] Optimization
- [ ] New feature

### How risky is the change?

- [ ] Low 
- [ ] Moderate 
- [ ] High
- [ ] Not relevant

### Backward compatibility

- [ ] Non breaking change
- [ ] Ensured. Please explain how has it been implemented?
- [ ] Breaking change
- [ ] Not relevant

### Is it platform specific issue?

- [ ] Yes. Please list the affected platforms.
- [ ] No

### Documentation update

- [ ] This change requires a documentation update. Please mark the issue on YouTrack using `Documentation Required` tag.
- [ ] No documentation update is needed 

### Testing by Contributor

- [ ] Tests have been added that prove the fix is effective or that the feature works
- [ ] Internal classes added to the test class (e.g. entity or index definition classes) have the lowest possible access modifier (preferable `private`) 
- [ ] It has been verified by manual testing

### Testing by RavenDB QA team

- [ ] This change requires a special QA testing due to possible performance or resources usage implications (CPU, memory, IO). Please mark the issue on YouTrack using `QA Required` tag.
- [ ] No special testing by RavenDB QA team is needed

### Is there any existing behavior change of other features due to this change?

- [ ] Yes. Please list the affected features/subsystems and provide appropriate explanation
- [ ] No

### UI work

- [ ] It requires further work in the Studio. Please mark the issue on YouTrack using `Studio Required` tag.
- [ ] No UI work is needed

2024-12-17 16:17 UTC, Danielle9897 commented
I have just run the latest code:

* The scenarios described in the related issue are solved and work ok

* However, **the following still needs fixing:**
   The analyzer shown does Not take into account the default analyzer that is set at the **Index Level**.
   For example:
   Set a custom analyzer as the default one from the index definition in the Client API:
   `Configuration["Indexing.Analyzers.Search.Default"] = "MyAnalyzer";`
   Or - set it from the UI (edit index view > configuration tab)
   
   This index-level setting should override the DB-level setting - but it doesn't.
   When you add a field configuration in the UI we should show "MyAnalyzer"  (when selecting Indexing: Search)
   But with the current UI,  you still see "Raven Standard Analyzer".

2024-12-17 16:19 UTC, Danielle9897 requested changes
I have just run the latest code:

* The scenarios described in the related issue are solved and work ok

* However, **the following still needs fixing:**
   The analyzer shown does Not take into account the default analyzer that is set at the **Index Level**.
   For example:
   Set a custom analyzer as the default one from the index definition in the Client API:
   `Configuration["Indexing.Analyzers.Search.Default"] = "MyAnalyzer";`
   Or - set it from the UI (edit index view > configuration tab)
   
   This index-level setting should override the DB-level setting - but it doesn't.
   When you add a field configuration in the UI we should show "MyAnalyzer"  (when selecting Indexing: Search)
   But with the current UI,  you still see "Raven Standard Analyzer".

2024-12-20 09:25 UTC, kalczur requested changes

2024-12-20 09:25 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
> +type indexingDatabaseSettings =
```suggestion
type IndexingDatabaseSetting =
```

2024-12-20 09:25 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
> +    constructor(dto: Raven.Client.Documents.Indexes.IndexDefinition, indexingDatabaseSettings?: Record<indexingDatabaseSettings[number], models.serverWideOnlyEntry | models.databaseEntry<string | num
By adding [number] you lose the union type
![image](https://github.com/user-attachments/assets/9ded0a6e-3a7c-4b6a-9df7-dbf78b802a19)

2024-12-20 09:25 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
> +    indexingDatabaseSettings = ko.observable<Record<indexingDatabaseSettings[number], models.serverWideOnlyEntry | models.databaseEntry<string | number>>>();
extract this Record to named type - is used multiple times

2024-12-20 09:25 UTC, kalczur commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +  | "Indexing.Analyzers.Search.Default"
It's defined twice

2024-12-20 09:25 UTC, kalczur commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +              const indexingAnalyzersDefaultsDatabaseSettingsKeys = ["Indexing.Analyzers.Default", "Indexing.Analyzers.Exact.Default", "Indexing.Analyzers.Search.Default"] as const;
Use `exhaustiveStringTuple` for typeseafty

2024-12-20 09:25 UTC, kalczur commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +        return new getDatabaseSettingsCommand(this.db)
How about getting this data somewhere else instead of pushing it in through the constructor multiple times?

2024-12-20 09:25 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +        console.log("@@TEST", thisIndexing, parentIndexing, this.analyzer(), "@@DB", this.databaseIndexConfiguration, this.indexLocalConfiguration, this.parent()?.analyzer());
remove

2024-12-20 09:25 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +        const databaseAnalyzerSetting = this.databaseIndexConfiguration?.[analyzerConfigurationKey];
Add a new line for readability

2024-12-20 09:25 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
> +    static empty(indexingDatabaseSettings?: Record<indexingDatabaseSettings[number], models.serverWideOnlyEntry | models.databaseEntry<string | number>>): indexDefinition {
If it's 'empty' then we'd rather not pass any argument and just use an empty object instead of indexingDatabaseSettings

2024-12-20 09:26 UTC, kalczur commented
Please apply suggestions to all places

2025-01-08 08:59 UTC, M4xymm commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +        return new getDatabaseSettingsCommand(this.db)
after a discussion, we have come to an agreement and are leaving the code as it is.

2025-01-08 10:36 UTC, M4xymm commented on src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
> +    static empty(indexingDatabaseSettings?: Record<indexingDatabaseSettings[number], models.serverWideOnlyEntry | models.databaseEntry<string | number>>): indexDefinition {
Changed method name to more descriptive: `createDefaultIndexDefinition`

2025-01-08 12:44 UTC, kalczur requested changes

2025-01-08 12:44 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +                          databaseIndexConfiguration?: Record<string, models.serverWideOnlyEntry | models.databaseEntry<string | number>>) {
Put `Record<string, models.serverWideOnlyEntry | models.databaseEntry<string | number>>` to named type

2025-01-08 12:44 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +            );
Also apply this aproach for getting `currentAnalyzerStudioName`

```suggestion
        const configuration = localAnalyzerConfiguration ?? databaseAnalyzerSetting?.effectiveValue();

        const isAnalyzerNameInDictionary = this.analyzersNamesDictionary().some((analyzerItem) => analyzerItem.serverName === configuration);
```

2025-01-08 12:44 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +        const defaultFieldAnalyzer = !thisIndexing && parentAnalyzer != null ? parentAnalyzerStudioName : currentAnalyzerStudioName;
Add new line for readability

2025-01-08 12:44 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +        const isAnalyzerNameInDictionary = localAnalyzerConfiguration
Add new line for readability

2025-01-08 13:52 UTC, kalczur requested changes

2025-01-08 13:52 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +            databaseAnalyzerSetting?.effectiveValue();
```suggestion
const currentAnalyzerStudioName = this.analyzersNamesDictionary().find((item) => item.serverName === configuration)?.studioName ?? configuration;
```

2025-01-08 13:52 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
> +
remove new line

2025-01-09 08:02 UTC, kalczur approved these changes

2025-01-15 14:27 UTC, Danielle9897 approved these changes
Tested the UI - LGTM

2025-01-15 17:16 UTC, ml054 commented on src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
> +import { IndexingDatabaseSettingsType } from "models/database/index/types";
this will shortly break linter rule. See: https://github.com/ravendb/ravendb/blob/v6.0/src/Raven.Studio/eslint-local-rules.js#L17  (mind as of now it isn't yet available in 6.2)

2025-01-15 17:17 UTC, ml054 commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +import { isEmpty } from "lodash";
same - eslint rule + avoid lodash if possible

2025-01-15 17:17 UTC, ml054 commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +type databaseIndexConfigurationType = Record<string, models.serverWideOnlyEntry | models.databaseEntry<string | number>>
missing `;`

2025-01-15 17:20 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +import getDatabaseSettingsCommand from "commands/database/settings/getDatabaseSettingsCommand";
same

2025-01-15 17:21 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +import genUtils from "common/generalUtils";
same

2025-01-15 17:21 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +        this.fetchDatabaseSettings();
do we fetch this twice? this.fetchDatabaseSettings()

2025-01-15 17:22 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +        this.fetchDatabaseSettings();
here and 3 lines below

2025-01-15 17:22 UTC, ml054 commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +        eventsCollector.default.reportEvent("database-settings", "get");
don't report event - this is getting data required for view.

2025-01-16 07:10 UTC, M4xymm commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +        this.fetchDatabaseSettings();
Yes, my oversight. Done.

2025-01-16 07:10 UTC, M4xymm commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +import getDatabaseSettingsCommand from "commands/database/settings/getDatabaseSettingsCommand";
Done.

2025-01-16 07:10 UTC, M4xymm commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +import genUtils from "common/generalUtils";
Done.

2025-01-16 07:11 UTC, M4xymm commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +type databaseIndexConfigurationType = Record<string, models.serverWideOnlyEntry | models.databaseEntry<string | number>>
Done.

2025-01-16 07:11 UTC, M4xymm commented on src/Raven.Studio/typescript/models/database/index/indexDefinition.ts
> +import { IndexingDatabaseSettingsType } from "models/database/index/types";
Done.

2025-01-16 07:11 UTC, M4xymm commented on src/Raven.Studio/typescript/viewmodels/database/indexes/editIndex.ts
> +        eventsCollector.default.reportEvent("database-settings", "get");
Done

2025-01-16 07:51 UTC, M4xymm commented on src/Raven.Studio/typescript/models/database/index/indexFieldOptions.ts
> +import { isEmpty } from "lodash";
Done

2025-01-16 08:17 UTC, M4xymm commented
Rebased

2025-01-16 08:42 UTC, ml054 approved these changes

2025-01-16 09:14 UTC, M4xymm commented
After discussing with @ppekrol , we concluded that the value should not be entered into the field but displayed as a placeholder instead.

2025-01-16 09:15 UTC, kalczur requested changes

2025-01-16 09:15 UTC, kalczur commented on src/Raven.Studio/typescript/common/typeUtils.ts
> +export const isEmpty = <T>(value: T | undefined): value is undefined => {
Why `value is undefined`? When you return true, the type of value will be casted to undefined.

```
function someFunction(value: string) {
    if (isEmpty(value)) {
        // Here type is undefined but it should be a string
        return value;
    }
}
```

2025-01-16 09:15 UTC, kalczur commented on src/Raven.Studio/typescript/common/typeUtils.ts
> +export const isEmpty = <T>(value: T | undefined): value is undefined => {
Also change from const to function declaration to be consistent in this file

2025-01-16 09:15 UTC, kalczur commented on src/Raven.Studio/typescript/common/typeUtils.spec.ts
> +            expect(isEmpty(' ')).toBe(true);
In lodash `' '` returns `false`

2025-01-16 09:15 UTC, kalczur commented on src/Raven.Studio/typescript/common/typeUtils.spec.ts
> +            expect(isEmpty(false)).toBe(false);
In lodash `0` and `false` returns true

2025-01-16 09:26 UTC, M4xymm commented on src/Raven.Studio/typescript/common/typeUtils.ts
> +export const isEmpty = <T>(value: T | undefined): value is undefined => {
> Why `value is undefined`? When you return true, the type of value will be casted to undefined.
> 
> ```
> function someFunction(value: string) {
>     if (isEmpty(value)) {
>         // Here type is undefined but it should be a string
>         return value;
>     }
> }
> ```

The remnants of the function I created in the beginning, removed.

2025-01-16 09:26 UTC, M4xymm commented on src/Raven.Studio/typescript/common/typeUtils.ts
> +export const isEmpty = <T>(value: T | undefined): value is undefined => {
Done

2025-01-16 09:27 UTC, M4xymm commented on src/Raven.Studio/typescript/common/typeUtils.spec.ts
> +            expect(isEmpty(' ')).toBe(true);
Done

2025-01-16 09:46 UTC, M4xymm commented on src/Raven.Studio/typescript/common/typeUtils.spec.ts
> +            expect(isEmpty(false)).toBe(false);
Done

2025-01-17 08:15 UTC, kalczur commented on src/Raven.Studio/typescript/common/typeUtils.ts
> +};
Prettier should add a new line at the end of a file

2025-01-17 08:16 UTC, kalczur commented on src/Raven.Studio/typescript/models/database/index/types.ts
> +export type IndexingDatabaseSettingsType = Record<IndexingDatabaseSetting, models.serverWideOnlyEntry | models.databaseEntry<string | number>>
same here

2025-01-17 11:38 UTC, ml054 approved these changes

2025-01-18 09:48 UTC, merged