RavenDB-6783 Refactor Put method to a standalone class.
ravendb/ravendb pull request #2149
Opened 2017-04-19 14:05 UTC by fitzchak

Refactor ShouldRecreateAttachment method out of the Put method.
Refactor identities related code to IdentitiesStorage.
Move AddConflict and DeleteConflicts to ConflictsStorage.
Remove duplicate GetChangeVectorEntriesFromTableValueReader method from ReplicationUtils.

2017-04-19 18:49 UTC, ayende requested changes

2017-04-19 18:49 UTC, ayende commented on src/Raven.Server/Documents/AttachmentsStorage.cs
> +                throw DocumentPutAction.ThrowRequiresTransaction();
No, we want to avoid having a throw in methods that might be called a lot

2017-04-19 18:49 UTC, ayende commented on src/Raven.Server/Documents/DocumentPutAction.cs
> +                throw ThrowRequiresTransaction();
Don't put throw inside the method.

2017-04-19 18:49 UTC, ayende commented on src/Raven.Server/Documents/DocumentPutAction.cs
> +            return new ArgumentException("Context must be set with a valid transaction before calling " + caller, "context");
Should throw here directly

2017-04-19 18:49 UTC, ayende commented on src/Raven.Server/Documents/DocumentsStorage.cs
> +                throw DocumentPutAction.ThrowRequiresTransaction();
Do not throw here, should throw inside the helper method.

2017-04-19 18:49 UTC, ayende commented on src/Raven.Server/Documents/DocumentPutAction.cs
> +        public string GetNextIdentityValueWithoutOverwritingOnExistingDocuments(string key, Table table, DocumentsOperationContext context, out int tries)
Shouldn't this go to identities storage?

2017-04-19 18:53 UTC, merged

2017-04-20 06:50 UTC, fitzchak commented on src/Raven.Server/Documents/AttachmentsStorage.cs
> +                throw DocumentPutAction.ThrowRequiresTransaction();
OK. I didn't realized that we wrap the throw because of perf, I thought it was purely for readability.
Will revert this specific change.

2017-04-20 07:04 UTC, fitzchak commented on src/Raven.Server/Documents/DocumentPutAction.cs
> +        public string GetNextIdentityValueWithoutOverwritingOnExistingDocuments(string key, Table table, DocumentsOperationContext context, out int tries)
I moved it there.

2017-04-20 07:04 UTC, fitzchak commented on src/Raven.Server/Documents/DocumentsStorage.cs
> +                throw DocumentPutAction.ThrowRequiresTransaction();
I see you already changed this. Thanks.