RavenDB-6783 Refactor Put method to be more readable
ravendb/ravendb pull request #2180
Opened 2017-04-23 11:44 UTC by fitzchak

2017-04-23 12:04 UTC, ayende requested changes

2017-04-23 12:04 UTC, ayende commented on src/Raven.Server/Documents/DocumentPutAction.cs
> +        private ChangeVectorEntry[] BuildChangeVector(DocumentsOperationContext context, string key, Slice lowerKey, long newEtag, ChangeVectorEntry[] changeVector, long? expectedEtag, DocumentFlags
Misleading method name here, you are also resolving the conflict here, and it is hidden and not visible for us.

2017-04-23 12:04 UTC, ayende commented on src/Raven.Server/Utils/ChangeVectorUtils.cs
> +            var sb = new StringBuilder();
Can calculate size of string here, so we don't need to allocate multiple times

2017-04-23 12:04 UTC, ayende commented on src/Raven.Server/Utils/ChangeVectorUtils.cs
> +        public static string ChangeVectorToString(ChangeVectorEntry[] changeVector)
Same, calc size ahead of time

2017-04-23 12:04 UTC, merged

2017-04-30 14:18 UTC, fitzchak commented on src/Raven.Server/Documents/DocumentPutAction.cs
> +        private ChangeVectorEntry[] BuildChangeVector(DocumentsOperationContext context, string key, Slice lowerKey, long newEtag, ChangeVectorEntry[] changeVector, long? expectedEtag, DocumentFlags
Changed to BuildChangeVectorAndResolveConflicts

2017-04-30 14:19 UTC, fitzchak commented on src/Raven.Server/Utils/ChangeVectorUtils.cs
> +            var sb = new StringBuilder();
No one is using those, so it will be deleted.

2017-04-30 14:19 UTC, fitzchak commented on src/Raven.Server/Utils/ChangeVectorUtils.cs
> +        public static string ChangeVectorToString(ChangeVectorEntry[] changeVector)
No one is using those, so it will be deleted.