RavenDB-5377: TxInfo debug EP
ravendb/ravendb pull request #2182
Opened 2017-04-23 13:05 UTC by aviviadi

2017-04-23 13:26 UTC, ayende requested changes

2017-04-23 13:26 UTC, ayende commented on src/Voron/Impl/LowLevelTransaction.cs
> +            ThreadId = Thread.CurrentThread.ManagedThreadId;
We don't want this, this is actually quite slow to compute.

2017-04-23 13:26 UTC, ayende commented on src/Voron/Impl/LowLevelTransaction.cs
> +            ThreadId = Thread.CurrentThread.ManagedThreadId;
Also, we don't typically remain on the same thread.

2017-04-23 13:59 UTC, aviviadi commented on src/Voron/Impl/LowLevelTransaction.cs
> +            ThreadId = Thread.CurrentThread.ManagedThreadId;
So which thread do we want to present ?

2017-04-23 14:00 UTC, aviviadi commented on src/Voron/Impl/LowLevelTransaction.cs
> +            ThreadId = Thread.CurrentThread.ManagedThreadId;
and what else do we want to see in this report ?

2017-04-23 14:50 UTC, aviviadi commented on src/Voron/Impl/LowLevelTransaction.cs
> +            ThreadId = Thread.CurrentThread.ManagedThreadId;
Ok.. I'll use NativeMemory.ThreadStats

2017-04-23 16:10 UTC, ayende requested changes

2017-04-23 16:10 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Debugging/TransactionDebugHandler.cs
> +            if (txInfos.Count < 1)
Why, same result if you remove this line

2017-04-23 16:10 UTC, ayende commented on src/Voron/Impl/LowLevelTransaction.cs
> +            ThreadId = Thread.CurrentThread.ManagedThreadId;
Waiting for this change

2017-04-24 07:50 UTC, merged

2017-04-24 07:50 UTC, ayende commented on src/Voron/Impl/LowLevelTransaction.cs
> +            TxStartTime = previous.TxStartTime;
Should we copy the previous start time?

2017-04-24 07:57 UTC, aviviadi commented on src/Voron/Impl/LowLevelTransaction.cs
> +            TxStartTime = previous.TxStartTime;
no...

2017-04-24 08:03 UTC, ayende commented on src/Voron/Impl/LowLevelTransaction.cs
> +            TxStartTime = previous.TxStartTime;
what is your reasoning?

2017-04-24 08:07 UTC, aviviadi commented on src/Voron/Impl/LowLevelTransaction.cs
> +            TxStartTime = previous.TxStartTime;
https://github.com/ravendb/ravendb/pull/2185