Raven db 6526 - WIP
ravendb/ravendb pull request #2265
Opened 2017-05-04 15:07 UTC by maximburyak

Do not merge
What's left:
Some of previous PR's comments
change subscripiton dictionary key to string (and make it work)
listen to database record change in subscription connection and disconnect when needed
fix failing tests (4 in fast tests, maybe some more in slow tests)
write cluster test(s) for subscriptions

2017-05-04 22:45 UTC, ayende requested changes

2017-05-04 22:45 UTC, ayende commented on src/Raven.Client/Documents/Operations/DatabaseStatistics.cs
> +        public ChangeVectorEntry[] LastChangeVector { get; set; }
`DatabaseChangeVector` might be better. It isn't actually the _last_ change vector. it is just the highest we have seen / extrapolated.

2017-05-04 22:45 UTC, ayende commented on src/Raven.Client/Documents/Subscriptions/Subscription.cs
> +                        ChangeVectorEntry[] lastReceivedEtag = null;
change param name

2017-05-04 22:45 UTC, ayende commented on src/Raven.Client/Documents/Subscriptions/Subscription.cs
>                  ThrowEtagRequired();
change method name and probably what it throws as well

2017-05-04 22:45 UTC, ayende commented on src/Raven.Client/Documents/Subscriptions/Subscription.cs
> +                _logger.Info($"Got {id} (etag: {lastReceivedChangeVector} on subscription {_options.SubscriptionId}, size {curDoc.Size}");
change log message

2017-05-04 22:45 UTC, ayende commented on src/Raven.Client/Documents/Subscriptions/SubscriptionCriteria.cs
> +        public long Etag { get; set; }
`Etag` -> `SubscriptionId`

2017-05-04 22:45 UTC, ayende commented on src/Raven.Client/Server/DatabaseRecord.cs
> +        public Dictionary<string, SubscriptionRaftState> Subscriptions;
Change to `Dictionary<int, ... >`

2017-05-04 22:45 UTC, ayende commented on src/Raven.Client/Server/DatabaseRecord.cs
> +        public void CreateSubscription(SubscriptionCriteria criteria, long etag, ChangeVectorEntry[] initialChangeVector = null)
`etag` -> `subscriptionId`

2017-05-04 22:45 UTC, ayende commented on src/Raven.Client/Server/DatabaseRecord.cs
> +        public void UpdateSusbscriptionChangeVector(long etag, ChangeVectorEntry[] changeVectorUpdate, string nodeTag)
change `etag` to `subscriptionId`

2017-05-04 22:45 UTC, ayende commented on src/Raven.Server/Documents/Handlers/StatsHandler.cs
> +                    stats.LastChangeVector = Database.DocumentsStorage.GetDocumentsFrom(context, stats.LastDocEtag.Value).FirstOrDefault()?.ChangeVector;
We already are tracking the global change vector, yes that.
Note that there is a major difference between what you are doing here and the actual observed global change vector

2017-05-04 22:45 UTC, ayende commented on src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
> +            var criteriaInstance = JsonDeserializationServer.SubscriptionCreationParams(criteria);
Why are we accepting blittable here and not the `SubscriptinCreationParams` ?

2017-05-04 22:45 UTC, ayende commented on src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
> +                var subscriptionRaftState = databaseRecord.Subscriptions[id.ToString()];
Error handling, what if we don't have such a subscription?

2017-05-04 22:45 UTC, ayende commented on src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
> +        public void GetCriteriaAndChangeVector(long id, DocumentsOperationContext context, out SubscriptionCriteria criteria, out ChangeVectorEntry[] startChangeVector)
wouldn't tuple be better here than multiple out params?

2017-05-04 22:45 UTC, ayende commented on src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
> +            Task.WaitAny(_db.WaitForIndexNotification(id), Task.Delay(timeout));
What is this doing here? It has no impact on the code.

2017-05-04 22:45 UTC, ayende commented on src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
> +        private static BlittableJsonReaderObject GetSubscriptionFromDatabaseRecordBlittable(BlittableJsonReaderObject databaseRecord, long subscriptionId)
Huh? What are you doing here? Looks like a binary search, but I can't figure out why you'll want / need that.
Leaving aside the fact that the `Subscriptions` is not sorted, you can just access the value directly.
Regardless, just get the `DatabaseRecord` and then use the `TryGetValue` on it.

2017-05-04 22:45 UTC, ayende commented on src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
> +                var databaseRecord = _serverStore.Cluster.Read(context, _db.Name);
We have `ReadDatabase` there for a reason.

2017-05-04 22:45 UTC, ayende commented on src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
> +            if (startEtag != 0)
Why do we even get a `startEtag` here? We are always passing it as 0.

2017-05-04 22:45 UTC, ayende commented on src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
> +                                low = high + 1; // stop here
Better to break / return here, than try to be smart with the low variable. It'll be clearer.

2017-05-04 22:45 UTC, ayende commented on src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
> +                        else if (conflictStatus == ConflictsStorage.ConflictStatus.Conflict)
Can we merge the two else branches?

2017-05-04 22:45 UTC, closed without merging

2017-05-07 09:40 UTC, maximburyak commented on src/Raven.Server/Documents/Handlers/StatsHandler.cs
> +                    stats.LastChangeVector = Database.DocumentsStorage.GetDocumentsFrom(context, stats.LastDocEtag.Value).FirstOrDefault()?.ChangeVector;
What we are tracking is the last change vector received through replication (found it out the hard way, before introducing the new value)

2017-05-07 09:42 UTC, maximburyak commented on src/Raven.Client/Documents/Operations/DatabaseStatistics.cs
> +        public ChangeVectorEntry[] LastChangeVector { get; set; }
That's confusing, because of the existing confusing function in DocumentStorage

2017-05-07 10:34 UTC, maximburyak commented on src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
> +            Task.WaitAny(_db.WaitForIndexNotification(id), Task.Delay(timeout));
Yeah, unless raft command did not arrive to the machine yet

2017-05-07 10:38 UTC, maximburyak commented on src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
> +            if (startEtag != 0)
Where do we pass it as 0?

2017-05-07 10:40 UTC, maximburyak commented on src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
> +                        else if (conflictStatus == ConflictsStorage.ConflictStatus.Conflict)
ok

2017-05-07 10:50 UTC, ayende commented on src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
> +            if (startEtag != 0)
Everywhere this is called.

2017-05-07 12:23 UTC, maximburyak commented on src/Raven.Server/Documents/Subscriptions/SubscriptionStorage.cs
> +        private static BlittableJsonReaderObject GetSubscriptionFromDatabaseRecordBlittable(BlittableJsonReaderObject databaseRecord, long subscriptionId)
ok

2017-05-07 12:24 UTC, maximburyak commented on src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
> +                                low = high + 1; // stop here
ok

2017-05-07 12:28 UTC, maximburyak commented on src/Raven.Server/Documents/TcpHandlers/SubscriptionConnection.cs
> +            if (startEtag != 0)
ok, now I got it