RavenDB-6707 Add hash to the File Header
ravendb/ravendb pull request #2372
Opened 2017-05-17 11:32 UTC by iftahbe

2017-05-17 12:15 UTC, ayende requested changes

2017-05-17 12:15 UTC, ayende commented on src/Voron/Impl/Backup/VoronBackupUtil.cs
> +                var hash = HeaderAccessor.CalculateFileHeaderHash(header);
No, this should be moved to the `ReadHeader` method.
The exception should be moved for the bottom of this method, if we failed to read both header files

2017-05-17 12:15 UTC, ayende commented on src/Voron/Impl/FileHeaders/FileHeader.cs
> +        public static int HashOffset = (int)Marshal.OffsetOf<FileHeader>(nameof(Hash));
Add assert that it is always the last thing on the file header

2017-05-17 12:15 UTC, ayende commented on src/Voron/Impl/FileHeaders/HeaderAccessor.cs
> +                if (f1->Hash != hash)
No, we should also check if we are valid of `f2` and use that

2017-05-18 06:16 UTC, iftahbe commented
Many tests are failing, I will close, merge and reopen the PR

2017-05-18 06:16 UTC, closed without merging