RavenDB-7203 Database record isn't updated after node removal
ravendb/ravendb pull request #2647
Opened 2017-06-05 16:24 UTC by karmeli87

2017-06-05 19:06 UTC, ayende requested changes

2017-06-05 19:06 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
> +                    var serverUrl = ServerStore.RavenServer.WebUrls[0];
Why?

2017-06-05 19:06 UTC, ayende commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +            if (_parent.CurrentState == RachisConsensus.State.Passive)
That is extremely invasive operation here. You are basically saying that while the node is passive, no databases can be accessed.
If I just remove a node from the cluster, I lost access to all its data.

2017-06-05 20:50 UTC, karmeli87 commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +            if (_parent.CurrentState == RachisConsensus.State.Passive)
This block the access to the database state, not the database itself.
I'll still be able to access the storage of the data, indexes, etc.

2017-06-06 05:24 UTC, ayende commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +            if (_parent.CurrentState == RachisConsensus.State.Passive)
Not a good idea, I think.
This is lying to the rest of the system.
And it won't help you with the state change for already running stuff, I think.

You need to be active about this and check in all the relevant locations.

2017-06-07 16:17 UTC, closed without merging