RavenDB-7371 Expose GetAttachmentNames in the session
ravendb/ravendb pull request #2654
Opened 2017-06-06 08:39 UTC by fitzchak

2017-06-06 08:45 UTC, ayende requested changes

2017-06-06 08:45 UTC, ayende commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        public AttachmentResult[] GetAttachmentNames<T>(string documentId)
Why is there a `<T>` here?

2017-06-06 08:45 UTC, ayende commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +            var entity = Load<T>(documentId);
You can look it up by id in the session, and if it isn't there, make a `Head` call, to get the metadata.

2017-06-06 09:57 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        public AttachmentResult[] GetAttachmentNames<T>(string documentId)
In order to call Load<T>(id)

2017-06-06 09:58 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +            var entity = Load<T>(documentId);
Head doesn't return the metadata... so in case that this is the session already Load is a no-op.

2017-06-06 10:58 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +            var entity = Load<T>(documentId);
I removed the overload the requires the T.

2017-06-06 11:15 UTC, ayende requested changes

2017-06-06 11:15 UTC, ayende commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +                return null;
Better to throw here. Or return empty array

2017-06-06 11:15 UTC, ayende commented on src/Raven.Client/Documents/Operations/AttachmentResult.cs
> +    public class AttachmentResult : AttachmentName
Why have this class now?

2017-06-06 11:15 UTC, ayende commented on src/Raven.Client/Documents/Operations/AttachmentResult.cs
> +    public class AttachmentResultWithStream : AttachmentResult, IDisposable
Don't think it is a good idea, we can just return a `Stream` directly from the method, don't need this.
We can also have a `out` param for the `AttachmentDetails`

2017-06-06 11:15 UTC, ayende commented on src/Raven.Client/Documents/Operations/AttachmentResult.cs
> +    public class AttachmentResultWithStream : AttachmentResult, IDisposable
This is fine for internal use, I just don't want to expose it externally.

2017-06-06 11:15 UTC, ayende commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +            var results = new AttachmentResult[attachments.Length];
Why not `AttachmentName`?

2017-06-06 11:15 UTC, ayende commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        public AttachmentResultWithStream GetAttachment(string documentId, string name)
Change it so it has two overloads on `Stream GetAttachment(...)` the second `Stream GetAttachment(..., out AttchmentDetails d`)

2017-06-06 11:17 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +            var results = new AttachmentResult[attachments.Length];
This is the result of PutAttachment method.

2017-06-06 11:17 UTC, fitzchak commented on src/Raven.Client/Documents/Operations/AttachmentResult.cs
> +    public class AttachmentResult : AttachmentName
This is the result of PutAttachment method.

2017-06-06 11:19 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +                return null;
If the document does not have an attachment should we return null, no?

2017-06-06 11:20 UTC, ayende commented on src/Raven.Client/Documents/Operations/AttachmentResult.cs
> +    public class AttachmentResult : AttachmentName
What is the difference from `AttachmentName` ?

2017-06-06 11:21 UTC, ayende commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +                return null;
Empty array or throw. No point in returning null to get NRE later on.

2017-06-06 11:21 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +                return null;
If yes, this is why I also return null in this case.

2017-06-06 11:21 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +            var results = new AttachmentResult[attachments.Length];
You're right, it should be AttachmentName here.

2017-06-06 11:22 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +                return null;
ok

2017-06-06 11:28 UTC, ayende reviewed
Will wait for merging until the `GetAttachment` change is done

2017-06-06 11:28 UTC, ayende commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        private static readonly AttachmentName[] NoAttachments = new AttachmentName[0];
`Array.Empty<AttachmentName>`

2017-06-06 11:28 UTC, fitzchak commented on src/Raven.Client/Documents/Operations/AttachmentResult.cs
> +    public class AttachmentResult : AttachmentName
AttachmentName does not have the attachment's etag.

2017-06-06 11:30 UTC, ayende commented on src/Raven.Client/Documents/Operations/AttachmentResult.cs
> +    public class AttachmentResult : AttachmentName
It is worth a separate class just for that? Can just return (AttachmentNAme, etag)

2017-06-06 12:20 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        public AttachmentResultWithStream GetAttachment(string documentId, string name)
Done

2017-06-06 12:20 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        private static readonly AttachmentName[] NoAttachments = new AttachmentName[0];
Changed

2017-06-06 12:21 UTC, fitzchak commented on src/Raven.Client/Documents/Operations/AttachmentResult.cs
> +    public class AttachmentResult : AttachmentName
Yes, we also need there the DocumentID for the case of reply in BatchHandler.

2017-06-06 13:22 UTC, ayende commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        public Stream GetAttachment(string documentId, string name)
Why not call `GetAttachment(string documentId, string name, out AttachmentDetails attachment)`

2017-06-06 13:22 UTC, ayende commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        public Stream GetAttachment(object entity, string name)
can call `GetAttachment(object entity, string name, out AttachmentDetails attachment)`

2017-06-06 13:22 UTC, ayende commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        public Stream GetRevisionAttachment(string documentId, string name, ChangeVectorEntry[] changeVector)
Same issue

2017-06-06 13:23 UTC, merged

2017-06-08 10:46 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        public Stream GetAttachment(string documentId, string name)
Fixed

2017-06-08 10:46 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        public Stream GetAttachment(object entity, string name)
Fixed

2017-06-08 10:46 UTC, fitzchak commented on src/Raven.Client/Documents/Session/DocumentSession.Attachments.cs
> +        public Stream GetRevisionAttachment(string documentId, string name, ChangeVectorEntry[] changeVector)
Fixed