RavenDB-7059 implementation
ravendb/ravendb pull request #2719
Opened 2017-06-12 13:08 UTC by myarichuk

2017-06-12 13:16 UTC, ayende requested changes

2017-06-12 13:16 UTC, ayende commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +                    goto case nameof(DeleteOngoingTaskCommand);
Why are you deleting the task here? Why not use `break`?

2017-06-12 13:16 UTC, ayende commented on src/Raven.Server/ServerWide/ServerStore.cs
> +        public async Task<(long clusterEtag, string clusterId)> GenerateClusterIdentityAsync(string id, string databaseName)
Use PublicCasing

2017-06-12 13:16 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                    _database.ServerStore.WaitForCommitIndexChange(RachisConsensus.CommitIndexModification.GreaterOrEqual, etag).Wait();
Why?

2017-06-12 13:16 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                    var (etag,_) = _database.ServerStore.SendToLeaderAsync(new UpdateClusterIdentityCommand(_database.Name,_identities)).Result;
You are _inside the transaction merger_, making a _raft consensus call_. That is not a good idea!

2017-06-12 13:20 UTC, ppekrol commented on src/Raven.Server/Documents/Handlers/StatsHandler.cs
> +                    stats.Identities = record.Identities;
Maybe this should go to a separate endpoint? Don't need to overload the DB stats.

2017-06-12 13:24 UTC, ppekrol commented on src/Raven.Client/Documents/Smuggler/DatabaseItemType.cs
> +        ClusterIdentities = 1 << 4
@myarichuk please open an issue that we need to support this block in 3.x (by skipping it). IIRC the 3.x smuggler throws if not supported property is encountered.

2017-06-12 13:25 UTC, ayende commented on src/Raven.Client/Documents/Smuggler/DatabaseItemType.cs
> +        ClusterIdentities = 1 << 4
Why change the name of this anyway? There is no distinction

2017-06-12 13:31 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
> +                    () => result.ClusterIdentities.ReadCount++,
If we have one type of identities, then maybe we can get rid of the lambdas here (maybe revert back to the old code?)

2017-06-13 15:07 UTC, myarichuk commented on src/Raven.Client/Documents/Smuggler/DatabaseItemType.cs
> +        ClusterIdentities = 1 << 4
hmm, no reason to change the name, I will change it back to Identities at the next PR

2017-06-13 15:08 UTC, myarichuk commented on src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
> +                    () => result.ClusterIdentities.ReadCount++,
I will get rid of lambdas

2017-06-14 06:22 UTC, ayende requested changes

2017-06-14 06:22 UTC, ayende commented on src/Raven.Client/Documents/Operations/GetClusterIdentitiesOperation.cs
> +    public class GetClusterIdentitiesCommand : RavenCommand<Dictionary<string, long>>
Rename to get database identities.

2017-06-14 06:22 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Debugging/IdentityDebugHandler.cs
> +                var identitiesAsJson = record.Identities.ToJson();
What happens if we have a lot of identities, should we place a limit on that?

2017-06-14 06:22 UTC, ayende commented on src/Raven.Server/ServerWide/Commands/UpdateClusterIdentityCommand.cs
> +    public class UpdateClusterIdentityCommand : UpdateDatabaseCommand
Rename class

2017-06-14 06:22 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/Data/ISmugglerSource.cs
> +        IEnumerable<KeyValuePair<string, long>> GetClusterIdentities();
Rename method

2017-06-14 06:22 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +        public IIdentityActions ClusterIdentities()
Rename method

2017-06-14 06:22 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                _database.ServerStore.SendToLeaderAsync(new UpdateClusterIdentityCommand(_database.Name, _identities)).Wait();
You _aren't_ doing fire and forget here.
And the smuggler is mostly async anyway. Move this behavior to FlushAsync()

2017-06-14 06:22 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/StreamDestination.cs
> +        public IIdentityActions ClusterIdentities()
Rename

2017-06-15 05:11 UTC, ayende commented
Manually merged

2017-06-15 05:11 UTC, closed without merging