RavenDB-4823 changes - after code review
ravendb/ravendb pull request #2848
Opened 2017-06-25 13:42 UTC by myarichuk

* Add GetRawStreamResultCommand so result of endpoint can be fetched as a raw stream
* Refactor debug-info handler to use RequestExecutor with ApiKey and GetRawStreamResultCommand 
* Remove change made to RachisAdminHandler -> could not reproduce the issue that was the reason I made the change in the first place
* Minor refactorings (fix NRE, better error handling)

2017-06-26 07:14 UTC, ayende requested changes

2017-06-26 07:14 UTC, ayende commented on src/Raven.Client/Server/ETL/RavenConnectionString.cs
> +            set => _url = value != null && value.EndsWith("/") ? value.Substring(0, value.Length - 1) : value;
`_url = value?.TrimEnd("/")` does it more clearly.

2017-06-26 07:14 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
> +                                    urlToDatabaseNamesMap.Value.Item1,
Use named value here to make it clear what it is that you are actually passing.

2017-06-26 07:14 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
> +            string apiKey)
You can integrate with @talweiss1982 work in `RavenDB-7466` to avoid needing this.

2017-06-26 07:14 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
> +                await requestExecuter.ExecuteAsync(rawStreamCommand, jsonOperationContext);
Where is the error handling? What happens if this fails?

2017-06-26 07:14 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
>                                  await WriteDebugInfoPackageForNodeAsync(
Probably better to execute all of those in parallel , you are already writing to memory stream anyway.
After you got it all, then write it to the archive.

2017-06-26 07:14 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Debugging/ServerWideDebugInfoPackageHandler.cs
> +                var requestExecuter = RequestExecutor.CreateForSingleNode(url, null, apiKey);
Make sure that we specify a timeout

2017-06-26 07:14 UTC, ayende commented on src/Raven.Server/ServerWide/LocalEndpointClient.cs
> +            catch (InvalidStartOfObjectException e)
Why catch just this exception, should do that for all exceptions.
Also, what happens if the endpoint fails for any reason? Do we fail the entire process?

2017-06-26 08:43 UTC, merged

2017-06-28 11:52 UTC, myarichuk commented on src/Raven.Server/ServerWide/LocalEndpointClient.cs
> +            catch (InvalidStartOfObjectException e)
I catch this exception because I want to throw more informative exception