RavenDB-7503
ravendb/ravendb pull request #2926
Opened 2017-07-03 13:18 UTC by talweiss1982

* Now allowing api keys with '/' as long as they are starting with Raven/ and properly split their secret.
* Opening an async task listening to a named pipe constructed as raven-control-pipe-<raven server pid>
* Added a method to create a system api key named Raven/System to be used by the admin in harden environment
* Added trust/init methods to RVN tool, still need TLC will open another issue to have better error handling and validation in RVN

2017-07-03 13:21 UTC, ppekrol commented on src/Raven.Server/ServerWide/ServerStore.cs
> +        public async Task<(string api_key, string public_key)> GetApiKeyAndPublicKey()
@talweiss1982 can you use C# casing here? Task(string ApiKey, string PublicKey)

2017-07-03 13:34 UTC, ayende requested changes

2017-07-03 13:34 UTC, ayende commented on src/Raven.Server/RavenServer.cs
> +            {
Add comment explaining why this is.
This is the second time I'm seeing this code and going `HuGH?`

2017-07-03 13:34 UTC, ayende commented on src/Raven.Server/RavenServer.cs
> +        private async Task ListenToPipe()
Missing error handling here.

2017-07-03 13:34 UTC, ayende commented on src/Raven.Server/RavenServer.cs
> +                Pipe.Dispose();
Failure to open / dispose would crash the process

2017-07-03 13:34 UTC, ayende commented on src/Raven.Server/ServerWide/ServerStore.cs
> +        public async Task<(string api_key, string public_key)> GetApiKeyAndPublicKey()
Please use PascalCase here.

2017-07-03 13:34 UTC, ayende commented on src/Raven.Client/Http/OAuth/ApiKeyAuthenticator.cs
> +                if (apiKeyParts[0] == "Raven" && apiKeyParts.Length > 3)
Maybe better of to use "Raven:Cluster/Secret" ?

2017-07-03 13:34 UTC, ayende commented on src/Raven.Client/Http/OAuth/ApiKeyAuthenticator.cs
> +                if (apiKeyParts[0] == "Raven" && apiKeyParts.Length > 3)
And then reserve just `Raven:`

2017-07-03 13:52 UTC, ppekrol commented on src/Raven.Client/Http/OAuth/ApiKeyAuthenticator.cs
> +                if (apiKeyParts[0] == "Raven" && apiKeyParts.Length > 3)
I think that 'Raven/' is already reserved: https://github.com/ravendb/ravendb/blob/v4.0/src/Raven.Server/Web/Authentication/AdminApiKeysHandler.cs#L26

2017-07-03 15:46 UTC, ayende requested changes

2017-07-03 15:46 UTC, ayende commented on src/Raven.Server/RavenServer.cs
> +            lock (this)
What, why? This is going to be locking effectively forever.

2017-07-03 15:46 UTC, ayende commented on src/Raven.Server/Web/Authentication/AdminApiKeysHandler.cs
> +        [RavenAction("/admin/server/reset-pipe", "GET", "/admin/server/reset-pipe")]
Why do we need this?

2017-07-04 10:45 UTC, ayende commented
We are going with a different route here, see: http://issues.hibernatingrhinos.com/issue/RavenDB-7696

2017-07-04 10:45 UTC, closed without merging