RavenDB-7549
ravendb/ravendb pull request #2956
Opened 2017-07-04 15:37 UTC by aviv86

2017-07-04 16:21 UTC, ayende commented on src/Raven.Server/Web/System/DatabasesHandler.cs
> +                if (ServerStore.Engine.LeaderTag == ServerStore.NodeTag)
Why are you doing that? This is going into persistent storage, and the data look ephemeral to me.

2017-07-04 20:56 UTC, ml054 commented on src/Raven.Client/Server/Operations/DatabasesInfo.cs
> +        public DateTime LastUpdateDateTime;
Should we use nullable here?

2017-07-04 20:58 UTC, ml054 commented on src/Raven.Server/Web/System/DatabasesHandler.cs
> +                if (ServerStore.Engine.LeaderTag == ServerStore.NodeTag)
@aviv86 It means this information will be only available when client connects to leader?

2017-07-11 14:35 UTC, ayende requested changes

2017-07-11 14:35 UTC, ayende commented on src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
> +                            reason = $"Demoted because the last report status was \"{nodeStats.LastReportStatus}\" ";
Need full error here.

2017-07-11 14:35 UTC, ayende commented on src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
> +                        if (nodeStats?.LastError?.Message != null)
If there is an error, append all of it.

2017-07-11 14:35 UTC, ayende commented on src/Raven.Server/ServerWide/Maintenance/ClusterObserver.cs
> +                        topology.DemotionReasons[member] = reason;
Try to avoid allocations

2017-07-11 14:36 UTC, merged