RavenDB-7533 implementation
ravendb/ravendb pull request #2966
Opened 2017-07-05 14:49 UTC by myarichuk

2017-07-05 18:02 UTC, ayende requested changes
This PR conflicts, please fix the conflict and my comments.

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Documents/Identity/AsyncHiLoIdGenerator.cs
> +            throw new FailedToFetchNextHiLoRangeException("Failed to fetch next HiLo range. See Inner Exception for details.", e);
What value is actually added by this exception? Please remove it.

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Exceptions/FailedToFetchNextHiLoRangeException.cs
> +    public class FailedToFetchNextHiLoRangeException  :Exception
Not required, kill it.

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/ClusterMode.cs
> +    public enum ClusterMode
@ppekrol any ideas for better names?

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/ClusterRequestExecutor.cs
> +                            executor._nodeSelector = executor.GetNodeSelector(new Topology
Any reason this is not already inside `FirstTopologyUpdate` ?

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/FailoverNodeSelector.cs
> +        public virtual void OnFailedRequest(int nodeIndex)
Why is this virtual?

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/FailoverNodeSelector.cs
> +            Interlocked.CompareExchange(ref _currentNodeIndex, nextNodeIndex, nodeIndex);
If two threads hits this in the same time? You are going to get an invalid nextNodeIndex. Need to use the return value of the `CompareExchange`

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/FailoverNodeSelector.cs
> +                    Interlocked.Exchange(ref _currentNodeIndex, 0);
Why are you resetting the index if this isn't forced?
Also, note that you did it before you changed the topology. Existing clients may get this part way.

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/FailoverNodeSelector.cs
> +            return Topology.Nodes[_currentNodeIndex];
Concurrency here can cause you to get argument out of range error.

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/LoadBalancingRoundRobinNodeSelector.cs
> +                RequestExecutor.ThrowEmptyTopology();
You are throwing here, and you left the `_syncFlag` on, killing it for all time.

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/LoadBalancingRoundRobinNodeSelector.cs
> +            if (Interlocked.CompareExchange(ref _syncFlag, 1, 0) == 1)
Why are you doing it in this manner, you are forcing all requests to experience contention.

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +        public event Action<string> FailedRequest;
If you are exposing the failure, it would be good to also exposed _what_ failed.

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +                            executor._nodeSelector = executor.GetNodeSelector(new Topology
This belongs in `FirstTopologyUpdate`

2017-07-05 18:02 UTC, ayende commented on src/Raven.Client/Http/RequestExecutor.cs
> +                if (_nodeSelector == null)
Why? There is no way we can recover from this. Instead, we need to throw and we'll keep trying next time.

2017-07-05 18:02 UTC, ayende commented on src/Raven.Server/Rachis/Leader.cs
> +                    //TODO: add here "error state" to prevent NRE in ServerStore::GetStatuses()  (line #538)
This has already been fixed,

2017-07-05 18:02 UTC, ayende commented on src/Raven.Server/ServerWide/Maintenance/ClusterMaintenanceSupervisor.cs
> +                        return Stream.Null;
You are catching _all_ errors here, not just `ObjectDisposedException` or `OperationCancelledException`. That can mask errors.
And it is better to let the calling code make decisions about this.

2017-07-06 07:51 UTC, myarichuk commented on src/Raven.Client/Http/FailoverNodeSelector.cs
> +        public virtual void OnFailedRequest(int nodeIndex)
it's an artifact, now no reasons for this

2017-07-06 08:33 UTC, ppekrol commented on src/Raven.Client/Http/RequestExecutor.cs
> +            _isSingleNode = isSingleNode;
what is the difference between this and _disableTopologyUpdates?

2017-07-06 08:34 UTC, ppekrol commented on src/Raven.Client/Http/RequestExecutor.cs
> +        public static void ThrowEmptyTopology()
Does it need to be public?

2017-07-06 08:47 UTC, ppekrol commented on src/Raven.Client/Http/ClusterMode.cs
> +    public enum ClusterMode
ReadBehavior
- Failover
- RoundRobin
- FastestNode

2017-07-14 10:48 UTC, closed without merging