RavenDB-7757 Compare Exchange over Raft - WIP
ravendb/ravendb pull request #3415
Opened 2017-08-24 14:57 UTC by karmeli87

- need better error handling
- need more tests

2017-08-24 17:00 UTC, ayende requested changes

2017-08-24 17:00 UTC, ayende commented on src/Raven.Client/ServerWide/Operations/UniqueValueOperation.cs
> +            public override void SetResponseRaw(HttpResponseMessage response, Stream stream, JsonOperationContext context)
Why do we need to use `SetReeponseRaw`, why not let the ReuqestExecuter do the parsing for us?

2017-08-24 17:00 UTC, ayende commented on src/Raven.Client/ServerWide/Operations/UniqueValueOperation.cs
> +                url = $"{node.Url}/unique?key={_key}&index={_index}";
Need a better url, just unique isn't good enough.
How about `/cluster/cmpxchg` ?

2017-08-24 17:00 UTC, ayende commented on src/Raven.Client/ServerWide/Operations/UniqueValueOperation.cs
> +    public class GetRawUniqueValueResult
This is meant to _implement_ unique constraints, but it have far wider applications.
We shouldn't limit ourselves in the naming, use something like `cmpxchg` or `CompareExchange` instead

2017-08-24 17:00 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
> +                var (etag, result) = await ServerStore.SendToLeaderAsync(command);
Nope, that is wrong. This is us getting a request from a node that think that _we_ are the leader.
If we aren't, we should throw.

2017-08-24 17:00 UTC, ayende commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +                        catch (Exception e)
Um, no. We need to tell them about an exception that happened _when this was going on, for example, the concurrency exception should be reported there.

2017-08-24 17:00 UTC, ayende commented on src/Raven.Server/Web/System/DatabasesHandler.cs
> +        [RavenAction("/unique", "GET", AuthorizationStatus.ValidUser)]
Rename

2017-08-24 17:00 UTC, ayende commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +        private static readonly TableSchema UniqueItemsSchema;
I'm not seeing any handling here for sending this over the wire via `InstallSnapshot` ?

2017-08-24 17:00 UTC, ayende commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +            UniqueItemsSchema = new TableSchema();
For that matter, where is this table created?

2017-08-24 20:45 UTC, karmeli87 commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +            UniqueItemsSchema = new TableSchema();
In the Initialize

2017-08-24 20:46 UTC, karmeli87 commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +                        catch (Exception e)
This exception can occur during notification. If we have  concurrency exception we throw it during the apply.

2017-08-24 20:53 UTC, karmeli87 commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +        private static readonly TableSchema UniqueItemsSchema;
I think we scan the entire voron file and send the structures with the relevant name. 
Which in this case I've named them both 'Items'. ( Not sure though if I need different names)

2017-08-24 21:07 UTC, ayende commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +        private static readonly TableSchema UniqueItemsSchema;
You cannot have two objects with the same name, that would cause corruption

2017-08-27 14:11 UTC, ayende requested changes

2017-08-27 14:11 UTC, ayende commented on src/Raven.Server/Web/System/DatabasesHandler.cs
> +        public Task GetUniqueValue()
Why is this randomly in the `DatabasesHandler` ?

2017-08-27 14:11 UTC, ayende commented on src/Raven.Server/Web/System/DatabasesHandler.cs
> +        public async Task PutUniqueValue()
Same

2017-08-27 14:13 UTC, merged