RavenDB-7589
ravendb/ravendb pull request #3474
Opened 2017-08-30 14:58 UTC by ppekrol

2017-08-30 15:01 UTC, ppekrol commented on src/Raven.Server/Documents/PeriodicBackup/RestoreBackupTask.cs
> +                    SmugglerRestore(_restoreConfiguration.BackupLocation, database, databaseRecord, restoreSettings.Identities, onProgress, restoreResult);
Need to save identities here. Will do that tomorrow.

2017-08-30 17:29 UTC, ayende requested changes

2017-08-30 17:29 UTC, ayende commented on src/Raven.Server/Documents/PeriodicBackup/RestoreBackupTask.cs
> +            Dictionary<string, long> identities,
What if we have a _lot_ of them?

2017-08-30 17:29 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Debugging/IdentityDebugHandler.cs
> +                var json = Database.ServerStore.Cluster.Read(context, Constants.Documents.IdentitiesPrefix + Database.Name.ToLowerInvariant());
This assume a single object holding all identities per database, right?
That is going to be a problem if we'll have users with thousands of identities. Better to use a value per identity per db.
So the key is going to be `db/db-name/identities/identity-name`.
The idea is that deleting the db will also delete the identities.

2017-08-31 12:33 UTC, ppekrol commented
Changes applied.

2017-08-31 14:26 UTC, merged