Raven db 8218
ravendb/ravendb pull request #3810
Opened 2017-09-27 11:37 UTC by aviv86

2017-09-27 13:00 UTC, ayende requested changes

2017-09-27 13:00 UTC, ayende commented on src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
> +                            TranslateSelectBodyToJs(newExpression);
And what if this is nested?

2017-09-27 13:00 UTC, ayende commented on src/Raven.Client/Documents/Session/IDocumentQuery.cs
> +        IDocumentQuery<TProjection> SelectFields<TProjection>(string[] fields, string[] projections, string fromAlias = null);
Why do we need this `fromAlias` here?

2017-09-27 13:00 UTC, ayende commented on src/Raven.Client/Util/JavascriptConversionExtensions.cs
> +                    var val = nodeAsConst.Value.ToString().ToLower();
Use static values here.

2017-09-27 13:00 UTC, ayende commented on src/Raven.Server/Documents/Patch/ScriptRunner.cs
> +                return new JsValue($"{days}.{hours}:{mins}:{secs}.{ms}");
Use a timespan here instead of string.

2017-09-27 17:21 UTC, merged

2017-09-28 08:02 UTC, arekpalinski commented on src/Raven.Client/Documents/Queries/QueryData.cs
> +        public string[] Fileds { get; set; }
typo: Fileds -> Fields

2017-09-28 08:07 UTC, arekpalinski commented on src/Raven.Client/Documents/Queries/QueryData.cs
> +    public class QueryData
I wonder if `QueryData` name isn't too wide for this class. Maybe `QuerySelectData`, `QuerySelection`

2017-09-28 08:11 UTC, arekpalinski commented on src/Raven.Client/Util/JavascriptConversionExtensions.cs
> +                                writer.Write(memberExpression.Member.Name == "UtcNow" ? ".getUTCMonth()+1" : ".getMonth()+1");
`.getUTCMonth()+1` that's is tricky :)