RavenDB-8832: Implement and use PeepingTomStream
ravendb/ravendb pull request #3840
Opened 2017-09-28 13:38 UTC by aviviadi

2017-09-28 16:09 UTC, aviviadi commented
@ayende - please wait until I add ReadAsync too

2017-09-29 13:35 UTC, ayende requested changes

2017-09-29 13:35 UTC, ayende commented on src/Raven.Client/Documents/Commands/MultiGet/MultiGetCommand.cs
> +                var peepingTomStream = new PeepingTomStream(stream);
This generates a 4KB buffer on every MultIGet call, let's see if we can use the context to get a pinnable buffer that is reused between calls.

2017-09-29 13:35 UTC, ayende commented on src/Sparrow/Json/Parsing/UnmanagedJsonParserHelper.cs
> +        private static string GetPeepingTomBufferAsString(PeepingTomStream peepingTomStream)
Duplicated code from RavenCommand.ThrowInvalidJson

2017-09-29 13:35 UTC, ayende commented on src/Sparrow/PeepingTomStream.cs
> +            while ((_bufferWindow[start] & 0x80) != 0)
Need to add a comment here to explain it.

2017-09-29 13:35 UTC, ayende commented
Okay, closing until then

2017-09-29 13:35 UTC, closed without merging