[4.0] RavenDB-10799 workaround for multiple localKeyId in certificate
ravendb/ravendb pull request #7016
Opened 2018-07-11 14:05 UTC by iftahbe

Workaround for #30946

2018-07-11 17:41 UTC, ppekrol approved these changes

2018-07-12 05:24 UTC, ayende requested changes
Beyond the class name, looks good

2018-07-12 05:24 UTC, ayende commented on src/Raven.Server/ServerWide/PkcsStore.cs
> +    public class PkcsStore
Let's give it a clearer name, `PkcsStoreWorkaroundFor30946` or something like that.

2018-07-12 05:24 UTC, ayende commented on src/Raven.Server/ServerWide/PkcsStore.cs
> +    public class PkcsStore
Also, make this class private

2018-07-12 07:27 UTC, ayende approved these changes

2018-07-12 07:49 UTC, merged