RavenDB-5090 Add exporter page
ravendb/ravendb pull request #726
Opened 2016-10-28 08:46 UTC by IdanHaim

2016-10-28 09:15 UTC, ppekrol requested changes

2016-10-28 09:15 UTC, ppekrol commented on src/Raven.Server/Documents/Document.cs
> +                if (expirationDateTime - DateTime.Now < TimeSpan.Zero)
Use DocumentDatabase.Time.UtcNow instead of DateTime.Now

2016-10-28 09:15 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/Data/ExportResult.cs
> +        public int DocumentExported { get; set; }
rename to DocumentCount

2016-10-28 09:15 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/Data/ExportResult.cs
> +                ["documentExported"] = DocumentExported,
use nameof(DocumentCount)

2016-10-28 09:15 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/Handlers/SmugglerHandler.cs
> +                var fileName = string.IsNullOrEmpty(exporter.Options.FileName) ?
Detect if the file contains any invalid file name chars (check 3.5 - StudioTasksController)

2016-10-28 09:15 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/SmugglerExporter.cs
> +            Options = options;
Options can be null, but later I do not see any NRE checks. Probably if they are null then you want to create new instance with default values.

2016-10-28 09:15 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/SmugglerExporter.cs
> +                    var batchSize = DocumentsLimit.HasValue ? Math.Min(Options.BatchSize, DocumentsLimit.Value) : Options.BatchSize;
Should we have DocumentLimit option? I do not understand the usability and it was problematic in the past. @ayende ?

2016-10-28 09:15 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/SmugglerExporter.cs
> +                            var patchResult = patch.Apply(context, document, patchRequest);
I think if the result is null then you must filter-out this document. You need to test this and check 3.5 if I'm right.

2016-10-28 09:15 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/SmugglerExporter.cs
> +                                indexField.Analyzer = null;
You can't do this. You are changing in-memory index instances.

2016-10-28 09:15 UTC, ppekrol commented on src/Raven.Server/Documents/DocumentsStorage.cs
> +                foreach (var document in GetDocumentsFrom(context, collection, etag, start, take))
remove the start, you cannot handle this properly without iterating half of the database and you will be setting 0 here always.

take needs to be handled in the inner loop. Currently you will take N x take where N - number of collections

2016-10-29 08:01 UTC, ayende commented on src/Raven.Server/Documents/Document.cs
> +                if (expirationDateTime - DateTime.Now < TimeSpan.Zero)
In general, in our entire codebase, we should never use DateTime.Now

2016-10-29 08:02 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/SmugglerExporter.cs
> +                    var batchSize = DocumentsLimit.HasValue ? Math.Min(Options.BatchSize, DocumentsLimit.Value) : Options.BatchSize;
No, we had to do that to avoid problems in the way we were using the smuggler, makes no sense to do so now

2016-10-29 08:02 UTC, closed without merging