RavenDB-11657 Add the source url to PutRaftCommand
ravendb/ravendb pull request #7327
Opened 2018-08-12 16:23 UTC by IdanHaim

2018-08-12 16:41 UTC, ppekrol commented on src/Raven.Server/ServerWide/ServerStore.cs
> +                Console.WriteLine(_source);
I think we can remove this?

2018-08-13 06:21 UTC, ayende requested changes

2018-08-13 06:21 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Admin/RachisAdminHandler.cs
> +                var source = GetStringQueryString("source", required: false);
We don't actually need it here.
We put the `source` here _just_ for debug.

2018-08-13 06:21 UTC, ayende commented on src/Raven.Server/ServerWide/ServerStore.cs
> +                var command = new PutRaftCommand(cmdJson, _engine.Url);
Let's also send the type of the command.

2018-08-14 07:01 UTC, merged