changes related to RavenDB-11747
ravendb/ravendb pull request #7360
Opened 2018-08-15 15:54 UTC by myarichuk

Multiple small fixes to different issues.

2018-08-16 07:24 UTC, ppekrol requested changes

2018-08-16 07:24 UTC, ppekrol commented on src/Raven.Client/Exceptions/Database/DatabaseDoesNotExistException.cs
> +        public string ThownAtStackTrace { get; }
This looks like a debugging code. Should be removed.

2018-08-16 07:24 UTC, ppekrol commented on src/Raven.Server/Rachis/Leader.cs
> +                                Debugger.Break();
Debugging code.

2018-08-16 07:24 UTC, ppekrol commented on src/Sparrow/Json/JsonOperationContext.cs
> +                _lastResestStack = Environment.StackTrace;
Debugging code. Should be removed.

2018-08-16 07:24 UTC, ppekrol commented on src/Sparrow/Json/JsonOperationContext.cs
> +            lock (_renewSyncObj)
Are we expecting to invoke this method in a concurrent manner?

2018-08-16 08:00 UTC, ayende requested changes

2018-08-16 08:00 UTC, ayende commented on src/Raven.Server/ServerWide/ServerStore.cs
> +                        return (response.Index, cmd.FromRemote(response.Result));
IIRC, we have commands that hold `BlittableJsonReaderObject`, but here you are disposing the context while the BJRO is still in use, no?

2018-08-16 08:00 UTC, ayende commented on src/Sparrow/Json/JsonOperationContext.cs
> +            catch (NullReferenceException e)
We should never catch NREs. We need to handle this properly.

2018-08-16 08:00 UTC, ayende commented on src/Sparrow/Json/JsonOperationContext.cs
> +            lock (_renewSyncObj)
There should never be such a case.

2018-08-16 08:00 UTC, ayende commented on test/RachisTests/DatabaseCluster/EtlFailover.cs
> +                catch (Exception e)
can remove this

2018-08-16 08:00 UTC, ayende commented on test/RachisTests/DatabaseCluster/EtlFailover.cs
> +                    {
remove this

2018-08-21 19:30 UTC, karmeli87 commented on test/RachisTests/TopologyChangesTests.cs
>              Assert.True(await leader.RemoveFromClusterAsync(oldTag).WaitAsync(TimeSpan.FromMilliseconds(leader.ElectionTimeout.TotalMilliseconds * 10)), "Was unable to remove node from cluster in tim
I think this test is fixed here: https://github.com/ravendb/ravendb/pull/7404

2018-08-22 07:17 UTC, closed without merging