RavenDB-11196 JsBlittableBridge.Translate should not mutate the Blitt…
ravendb/ravendb pull request #7483
Opened 2018-08-29 13:48 UTC by talweiss1982

…ableObjectInstance

2018-08-29 21:38 UTC, ayende requested changes

2018-08-29 21:38 UTC, ayende commented on src/Raven.Server/Documents/Patch/JsBlittableBridge.cs
> +                if(modifiedProperties.Contains(modificationKvp.Key))
Can't this be null here? (`OwnValue that doesn't `existInObject` ?)

2018-08-30 08:22 UTC, talweiss1982 commented on src/Raven.Server/Documents/Patch/JsBlittableBridge.cs
> +                if(modifiedProperties.Contains(modificationKvp.Key))
yes it can

2018-08-30 08:39 UTC, ayende approved these changes

2018-08-30 10:26 UTC, merged