RavenDB-12292: Added the ability to filter out Attachments when doing smuggler import.
ravendb/ravendb pull request #8001
Opened 2018-11-12 10:38 UTC by garayx

2018-11-12 11:11 UTC, grisha-kotler commented
What about import database?

2018-11-12 11:40 UTC, ppekrol commented
I've talked with @garayx we will add it there too. Also we will check if this (along with Counters) can be added to export.

2018-11-12 13:23 UTC, garayx commented
> What about import database?

done

2018-11-13 07:31 UTC, ml054 commented on src/Raven.Studio/typescript/models/database/tasks/exportDatabaseModel.ts
> +                this.validationMessage("Note: Attachments can only be included with documents.");
Can we automatically check documents when user checks attachments + avoid having generic field: validationMessage in this model?

2018-11-13 07:34 UTC, ml054 requested changes
@garayx Please have a look at my comment

2018-11-13 15:23 UTC, ppekrol approved these changes

2018-11-14 13:27 UTC, merged