fix for RavenDB-12276
ravendb/ravendb pull request #8002
Opened 2018-11-12 11:24 UTC by myarichuk

Make graph queries throw when trying to fetch vertices from non-existing collection + relevant test

2018-11-12 12:31 UTC, ayende requested changes

2018-11-12 12:31 UTC, ayende commented on src/Raven.Server/Documents/Queries/Graph/QueryQueryStep.cs
> +                  _context, _resultEtag, _token, true);
Use named arg here to make this clearer

2018-11-13 14:53 UTC, ppekrol commented on src/Raven.Server/Documents/Queries/AbstractQueryRunner.cs
> +            if (index == null && !throwIfDoesNotExist)
This should be the other way around and all values by default should be 'true'

2018-11-21 16:20 UTC, myarichuk commented
Will open another PR for this issue

2018-11-21 16:20 UTC, closed without merging