RavenDB-12354 Allow to filter out Studio notifications
ravendb/ravendb pull request #8078
Opened 2018-11-22 14:05 UTC by iftahbe

2018-11-22 14:20 UTC, ayende requested changes

2018-11-22 14:20 UTC, ayende commented on src/Raven.Server/Config/Categories/StudioConfiguration.cs
> +        [ConfigurationEntry("Studio.Notifications.FilterOut", ConfigurationEntryScope.ServerWideOnly)]
That isn't a Studio decisions, it belongs to notifications

2018-11-22 14:20 UTC, ayende commented on src/Raven.Server/Config/Categories/StudioConfiguration.cs
> +        private void ValidateFilteredOutNotificationNames()
Let's not do that, we might change this and we don't want to break things if the user has a configuration for new version, frex.

2018-11-22 14:20 UTC, ayende commented on src/Raven.Server/Config/Categories/StudioConfiguration.cs
> +        public string[] FilteredOutNotifications { get; set; }
You are always comparing on this, easier if you will use `HashSet<string>` (case insensitive)

2018-11-23 08:45 UTC, ppekrol requested changes
All of this should be moved to:
https://github.com/ravendb/ravendb/blob/v4.1/src/Raven.Client/ServerWide/Operations/Configuration/ServerWideStudioConfiguration.cs
or
https://github.com/ravendb/ravendb/blob/v4.1/src/Raven.Client/Documents/Operations/Configuration/StudioConfiguration.cs

it depends if we want to have it configurable server-wide only or database and server-wide.

After that we can add it to Studio.

2018-11-23 09:00 UTC, arekpalinski commented
Please create a test

2018-11-25 09:32 UTC, iftahbe commented
@ppekrol I don't follow why you want this. 
It is all handled server side, and the Studio is not aware of the filtered out notifications.

About the question whether it should also be per-database... I assumed that people will filter out mostly performance hints which should be server wide but if you think there are use-cases where people need this per database I can change that.

2018-11-25 10:41 UTC, ppekrol commented
I've meant that we should move `public HashSet<string> FilteredOutNotifications { get; set; }` to `StudioConfiguration.cs` and let @ml054 add this to the UI, so users can configure it via Studio when Server is running.

Filtering should be done server-side as you do it now.

2018-11-25 13:47 UTC, ayende commented
@ppekrol One of the reasons to do this is to allow the admin to shut down notifications.
This shouldn't be something that any user can edit.

I'm fine with having _additional_ items that are filtered, but the base line is fixed

2018-11-25 20:55 UTC, ppekrol commented
@iftahbe add what I've wrote about to 4.2. For 4.1 this is enough.

2018-11-25 20:55 UTC, merged