RavenDB-12145 PR Comments + Tests + fixes
ravendb/ravendb pull request #8102
Opened 2018-11-26 10:00 UTC by talweiss1982

2018-11-26 10:35 UTC, ayende requested changes

2018-11-26 10:35 UTC, ayende commented on src/Raven.Server/Documents/Queries/GraphQueryOrderByFieldComparer.cs
> +                        case int i:
```
case int _:
case long _:
  yObject = yResult;
  break;
```
Is easier

2018-11-26 10:35 UTC, ayende commented on src/Raven.Server/Documents/Queries/GraphQueryOrderByFieldComparer.cs
> +                    return LogMissmatchTypesReturnOrder(xResult, yResult);
And if it is double, we should still support it.

2018-11-26 10:35 UTC, ayende commented on src/Raven.Server/Documents/Queries/GraphQueryOrderByFieldComparer.cs
> +                    return LogMissmatchTypesReturnOrder(xResult, yResult);
and if it is double, long?

2018-11-26 10:35 UTC, ayende commented on src/Raven.Server/Documents/Queries/GraphQueryOrderByFieldComparer.cs
> +                    return LogMissmatchTypesReturnOrder(xObject, yObject);
double ?

2018-11-26 10:35 UTC, ayende commented on src/Raven.Server/Documents/Queries/GraphQueryOrderByFieldComparer.cs
> +                    return LogMissmatchTypesReturnOrder(xObject, yObject);
long -> double, etc

2018-11-26 10:35 UTC, ayende commented on src/Raven.Server/Documents/Queries/GraphQueryOrderByFieldComparer.cs
> +                        return string.CompareOrdinal(xBlittableJsonReaderArray.ToString(), yBlittableJsonReaderArray.ToString());
You are allocating what may be very large value.
Need to recurse here.

2018-11-26 10:35 UTC, ayende commented on src/Raven.Server/Documents/Queries/GraphQueryOrderByFieldComparer.cs
> +                        return string.CompareOrdinal(xBlittableJsonReaderObject.ToString(), yBlittableJsonReaderObject.ToString());
There is no meaningful way to compare them, and I certainly don't want to use strings.
Use the `Base` as a way to get just a stable sort order.

2018-11-26 12:41 UTC, talweiss1982 commented on src/Raven.Server/Documents/Queries/GraphQueryOrderByFieldComparer.cs
> +                        case int i:
its actually does the conversion

2018-11-26 15:43 UTC, talweiss1982 commented
updated

2018-11-26 20:26 UTC, ayende commented
Also, check the failing tests

2018-11-27 11:29 UTC, ayende approved these changes

2018-11-28 06:37 UTC, ayende commented
There is a failing test that needs to be handled.

2018-11-28 06:38 UTC, ayende commented
There are also conflicts from my recent merge, please fix them and re-sumbit the PR

2018-11-28 06:38 UTC, closed without merging

2018-11-28 13:58 UTC, talweiss1982 commented
I have resolved conflicts in my PR are there new modification you made?
 Which test is failing i have passed fast test and on slow test only SQL test failed from what i recall.

2018-11-28 14:59 UTC, arekpalinski commented
Probably `SlowTests.Graph.SortGraphQueries.SortOnObjectShouldWork` test - http://jenkins.hibernatingrhinos.com/job/PR_Tests_v4.2/184/

2018-11-28 16:33 UTC, talweiss1982 commented
@arekpalinski 
I was afraid this test might be flaky.
Since now we don't really do a real comparison on blittable might as well delete the test since we can't know the order of objects.

2018-11-29 12:08 UTC, ayende commented
Yes, we have a stable sort on the _existing_ system, but never between runs, so that might certainly be it.
Can you remove the test and reissue the PR?

2018-11-29 12:09 UTC, talweiss1982 commented
@ayende I'm just running the test and will submit a fixed PR once they pass

2018-11-29 12:10 UTC, talweiss1982 commented
acouple of tests are failing i might have done something wrong in the merge, checking.