fix for RavenDB-12459
ravendb/ravendb pull request #8213
Opened 2018-12-11 17:53 UTC by myarichuk

…ression with multiple values (for example: Order -> OrderLines.Product) (RavenDB-12459)

2018-12-12 08:39 UTC, arekpalinski approved these changes

2018-12-12 11:48 UTC, ayende requested changes

2018-12-12 11:48 UTC, ayende commented on src/Raven.Server/Documents/Queries/Graph/SingleEdgeMatcher.cs
>                          break;
Same issue below, line 67

2018-12-13 08:29 UTC, ayende commented on src/Raven.Server/Documents/Queries/Graph/SingleEdgeMatcher.cs
> +                if (Edge.Project == null)
I'm trying to think if there is any case where we want a `where` without a `select`
`[Friend where startsWith(Friend, $prefix)]` looks like the only thing, but that seems... odd

2018-12-13 08:30 UTC, merged