RavenDB-12137 [WIP] Add graph queries to RunningQueries
ravendb/ravendb pull request #8431
Opened 2019-01-07 17:35 UTC by talweiss1982

2019-01-07 19:25 UTC, ppekrol requested changes

2019-01-07 19:25 UTC, ppekrol commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +            CurrentlyRunningGraphQueries.Add(executingQueryInfo);
Can we move it to GraphQueryRunner and acces it via Database.QueryRunner.Graph.CurrentlyRunningGraphQueries ?

2019-01-07 19:25 UTC, ppekrol commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +            return Interlocked.Increment(ref _numberOfGraphQueries);
Can we move it to GraphQueryRunner and acces it via Database.QueryRunner.Graph.CurrentlyRunningGraphQueries ?

2019-01-07 19:25 UTC, ppekrol commented on src/Raven.Server/Documents/Handlers/Debugging/QueriesDebugHandler.cs
> +            if (name == "@graph")
'@graph' should be moved to constants e.g. Constants.Documents.Indexing.GraphIndexName

2019-01-07 19:25 UTC, ppekrol commented on src/Raven.Server/Documents/Handlers/Debugging/QueriesDebugHandler.cs
> +                writer.WritePropertyName("Graph queries");
Can we use property without space? Maybe `@graph` that you used before?

2019-01-07 19:25 UTC, ppekrol commented on src/Raven.Server/Documents/Queries/GraphQueryDoneRunning.cs
> +        private static readonly TimeSpan DefaultLockTimeout = TimeSpan.FromSeconds(3);
Is this used?

2019-01-07 19:25 UTC, ppekrol commented on src/Raven.Server/Documents/Queries/GraphQueryDoneRunning.cs
> +        private static readonly TimeSpan ExtendedLockTimeout = TimeSpan.FromSeconds(30);
Is this used?

2019-01-07 21:00 UTC, ayende requested changes
I don't like this impl.
What we want to do here is to use the exact same code and process that we have for the already existing running queries impl, as well as the same cancellation support.

That means that we call the regular `AddToRunningQueries` and (maybe) handle any changes there, but I think we probably shouldn't have to do much there.

2019-01-07 21:00 UTC, ayende commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +            return Interlocked.Increment(ref _numberOfGraphQueries);
Yes, this shouldn't be on `DocumentDatabase`

2019-01-07 21:00 UTC, ayende commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +        public readonly ConcurrentSet<ExecutingQueryInfo> CurrentlyRunningGraphQueries = new ConcurrentSet<ExecutingQueryInfo>();
Why do we need a separate behavior for graph queries? Can't we use the existing running queries for the same thing?

2019-01-07 21:00 UTC, ayende commented on src/Raven.Server/Documents/Handlers/Debugging/QueriesDebugHandler.cs
> +                writer.WritePropertyName("Graph queries");
I really don't like it being separate. 
These are just queries, and should be treated the same.

2019-01-08 08:56 UTC, ppekrol commented
@ayende this is because running queries were only on index-level

@talweiss1982 I think we need to take this opportunity and move running queries to QueryRunner, so we can handle all types of queries (index, collection, graph). Thoughts?

2019-01-08 15:39 UTC, ayende commented
fine by me

2019-01-09 14:48 UTC, maximburyak commented
@ayende @ppekrol can we postpone the change proposed be @ppekrol to 4.2.x? I think that right now we want to concentrate on getting all graph features done

2019-01-09 17:04 UTC, ppekrol commented
We will do it in 2 stages.
1. @talweiss1982 will move the code to GraphQueryRunner (as was written in one of the first comments) and add the cancellation support
2. To allow @talweiss1982 to continue the work on Graph issues, I will do the unification

2019-01-13 12:47 UTC, talweiss1982 commented
@ppekrol i added cancelation to graph queries and moved the running graph queries under the runner

2019-01-14 13:21 UTC, ppekrol approved these changes
Rebased and did some minor adjustments.

2019-01-15 10:13 UTC, ayende approved these changes

2019-01-15 10:21 UTC, merged