RavenDB-5435 added the ability to compact an index
ravendb/ravendb pull request #854
Opened 2016-11-10 14:39 UTC by ppekrol

2016-11-10 14:58 UTC, ayende requested changes

2016-11-10 14:58 UTC, ayende commented on src/Raven.Server/Documents/Indexes/Index.cs
> +                _isCompactionInProgress = true;
This isn't thread safe.
what is going to happen to queries that are currently running? Or indexing that is currently using?
You are pulling the carpet on them by disposing the environment, and then making the memory they use invalid.

You need to add a reader / writer lock here to ensure that we are the only one accessing it.

2016-11-10 15:18 UTC, ppekrol commented
I will change approach.

2016-11-12 21:43 UTC, ppekrol commented
Draining queries before compaction now.

2016-11-13 09:51 UTC, ayende commented on src/Raven.Server/Documents/Indexes/Index.cs
> +                    Thread.Sleep(TimeSpan.FromSeconds(1));
You are sleeping while holding the lock, that isn't a very good idea.

2016-11-13 09:51 UTC, ayende commented on src/Raven.Server/Documents/Indexes/Index.cs
> +                var currentlyRunningQueriesCount = CurrentlyRunningQueries.Count;
There is a race here, a user can check the `_isCompactionInProgress` in `AssertIndexState`, see it is valid, and then start querying, and we check if there are running queries before that. 
You can't rely on this

2016-11-13 11:25 UTC, ayende commented on src/Raven.Server/Documents/Indexes/Index.cs
> +                var progress = new IndexCompactionProgress();
Who is this reporting to? It looks like this goes into the void.

2016-11-13 11:25 UTC, ayende commented on src/Raven.Server/Documents/Indexes/Index.cs
> +                var progress = new IndexCompactionProgress();
I think you meant to add this to the operations?

2016-11-13 11:30 UTC, ppekrol commented on src/Raven.Server/Documents/Indexes/Index.cs
> +                var progress = new IndexCompactionProgress();
It is added to the operations, check https://github.com/ppekrol/ravendb/blob/v4.0/src/Raven.Server/Documents/Handlers/Admin/AdminIndexHandler.cs#L28

2016-11-13 11:31 UTC, ppekrol commented on src/Raven.Server/Documents/Indexes/Index.cs
> +                    Thread.Sleep(TimeSpan.FromSeconds(1));
Fixed

2016-11-13 11:31 UTC, ppekrol commented on src/Raven.Server/Documents/Indexes/Index.cs
> +                var currentlyRunningQueriesCount = CurrentlyRunningQueries.Count;
Fixed

2016-11-13 11:37 UTC, ayende commented
User RW implemetnation for this.

2016-11-13 11:37 UTC, closed without merging

2016-11-13 11:46 UTC, ppekrol commented
Ok, note that RW is not async/await compatible IIRC

2016-11-13 11:46 UTC, ayende commented
Yes, I handled that by exiting the lock before the await