RavenDB-12320 When smuggler imports revisions w/o documents, it creat…
ravendb/ravendb pull request #8603
Opened 2019-01-30 08:41 UTC by efratshenhar

…es orphans

2019-01-30 09:30 UTC, ppekrol requested changes

2019-01-30 09:30 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                _cmd.Context.CloseTransaction();
would be better to do that few lines up. After waiting for the task to complete and in try_finally

2019-01-30 09:30 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
> +                case DatabaseDestination databaseDestination:
Move to DatabaseDestination.Dispose or action Dispose actually IIRC

2019-01-30 09:30 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
> +                        result.Counters.ErroredCount++;
we need to increase by the amount of the counters in batch.

2019-01-30 09:40 UTC, ayende requested changes

2019-01-30 09:40 UTC, ayende commented on src/Raven.Server/Documents/Handlers/CountersHandler.cs
> +                _database.DocumentsStorage.ContextPool.AllocateOperationContext(out Context);
Where is this being disposed?

2019-01-30 09:40 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +        public ConcurrentDictionary<string, CollectionName> MissingDocumentsForRevisions;
Why concurrent dic?

2019-01-30 09:40 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                                _missingDocumentsForRevisions.TryAdd(document.Id.ToString(), collection);
NRE here

2019-01-30 09:40 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
> +                    using (var tx = context.OpenWriteTransaction())
We must _never_ do this.
All `WriteTransaction` _must_ be through the tx merger

2019-01-30 10:10 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
> +                        result.Counters.ErroredCount++;
Was wrong here. Everything OK.

2019-02-03 13:55 UTC, ppekrol commented on src/Raven.Server/Documents/Handlers/CountersHandler.cs
> +                                        ErrorCount++;
Are we doing something with that? We need to increase the error count in the progress, right?

2019-02-03 13:55 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                                DateTime.Now.Ticks,
need to be _database.Time.GetUtcNow()... Also probably can be handled inside the command.

2019-02-03 13:55 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                            var command = new RevisionsOperations.DeleteRevisionCommand(docId.Key,
You need to pass the _missingDocumentsForRevisions into the command and process everything in one batch inside the command.

2019-02-03 13:55 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                using (context.OpenReadTransaction())
Why are we opening the read tx?

2019-02-03 13:55 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseSmuggler.cs
> +                    actions.WriteCounter(counterDetail);
Need to increase the error count here

2019-02-03 13:55 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                            var changeVector = _database.DocumentsStorage.GetNewChangeVector(context, _database.DocumentsStorage.GenerateNextEtag());
move this to the command

2019-02-03 13:55 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                        using (DocumentIdWorker.GetSliceFromId(context, docId.Key, out var lowerId))
this can be handled inside the command

2019-02-03 13:55 UTC, ppekrol commented on src/Raven.Server/Documents/Revisions/RevisionsOperations.cs
> +        internal class DeleteRevisionCommand : TransactionOperationsMerger.MergedTransactionCommand
This should be moved to Smuggler

2019-02-03 13:55 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                            var command = new RevisionsOperations.DeleteRevisionCommand(docId.Key,
Or batch the number of items by the same rules as we have in MergedBatchPutCommand.

2019-02-03 13:55 UTC, ppekrol commented on test/SlowTests/Smuggler/SmugglerApiTests.cs
> +            var file = Path.GetTempFileName();
Let's use `Path.Combine(NewDataDir(force: true), Guid.New)`

2019-02-04 14:58 UTC, ppekrol approved these changes

2019-02-04 16:30 UTC, ppekrol commented
@efratshenhar can you rebase and check the test failure? `ImportRevisionDocumentsWithoutDocuments` failed.

2019-02-05 12:07 UTC, merged