RavenDB-12819 Backup Subscriptions
ravendb/ravendb pull request #8779
Opened 2019-02-24 09:17 UTC by efratshenhar

2019-02-24 11:21 UTC, ayende requested changes

2019-02-24 11:21 UTC, ayende commented on src/Raven.Server/ServerWide/Commands/Subscriptions/PutSubscriptionCommand.cs
> +                            SubscriptionName = $"{SubscriptionName}.{new Random().Next()}";
Let's use something better here. This will generate a double.
Either use a Guid or an incrementing number

2019-02-24 11:21 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                var commandTask = _database.TxMerger.Enqueue(_command);
This is wrong. We should be invoking the `PutSubscription` here on each one of them, not trying to ship it to the Tx Merger and invoking it from there.
That is a bad idea.

2019-02-24 11:21 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +        public class MergedBatchPutSubscriptionCommand : TransactionOperationsMerger.MergedTransactionCommand, IDisposable
Drop this

2019-02-24 11:21 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                    _database.SubscriptionStorage.PutSubscription(new SubscriptionCreationOptions
Note that you aren't actually waiting for this to complete here!

2019-02-24 11:21 UTC, ayende commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +                _command.Add(subscriptionState);
How are we handling the change vector of the subscription?

2019-02-24 19:35 UTC, ppekrol commented on src/Raven.Server/ServerWide/Commands/Subscriptions/PutSubscriptionCommand.cs
> +        private string OldName;
rename to `_originalName`

2019-02-24 19:35 UTC, ppekrol commented on src/Raven.Server/ServerWide/Commands/Subscriptions/PutSubscriptionCommand.cs
> +    public class PutSubscriptionBatchCommand : CommandBase
please move it to separate file

2019-02-24 19:35 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/Data/ISmugglerSource.cs
> +        IEnumerable<SubscriptionState> GetSubscriptionValues();
`GetSubscriptions`

2019-02-24 19:35 UTC, ppekrol commented on src/Raven.Server/Smuggler/Documents/DatabaseDestination.cs
> +            {
no need for `async` and `await` here, I think?

2019-02-25 09:18 UTC, ppekrol approved these changes

2019-02-25 09:24 UTC, ayende approved these changes

2019-02-25 09:24 UTC, ayende commented on src/Raven.Server/ServerWide/Commands/Subscriptions/PutSubscriptionCommand.cs
> +                            SubscriptionName = $"{SubscriptionName}.{Guid.NewGuid()}";
long index = 0;
while(true) {
    var subscriptionName = "{SubscriptionName}.{++index}";
   if( SubscriptionNameExists(SubscriptionName ) == false ) {
         SubscriptionName = subscriptionName + "." + index;
        break;
}

2019-02-25 09:25 UTC, ayende commented on src/Raven.Server/ServerWide/Commands/Subscriptions/PutSubscriptionCommand.cs
> +                            SubscriptionName = $"{SubscriptionName}.{Guid.NewGuid()}";
Ignore this, old stuff

2019-02-25 15:26 UTC, merged