RavenDB-12027 Have dedicated threads for backups
ravendb/ravendb pull request #8829
Opened 2019-02-28 17:16 UTC by karmeli87

2019-02-28 17:41 UTC, grisha-kotler requested changes

2019-02-28 17:41 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
> +            CreateUploadTaskIfNeeded($"Upload to Glacier (task: {taskName})",_configuration.GlacierSettings, tasks, backupPath, _isFullBackup,
Also add the database name

2019-02-28 17:41 UTC, grisha-kotler commented on src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
> +            }, null, $"Backup task {periodicBackup.Configuration.Name}");
Missing database name

2019-03-01 08:37 UTC, ppekrol submitted a review, later dismissed

2019-03-01 08:42 UTC, ppekrol reviewed
Check in other places in the flow if we need to take into account AggregateException now and unwrap it

2019-03-01 08:42 UTC, ppekrol commented on src/Raven.Server/Documents/PeriodicBackup/BackupTask.cs
> +                        {
it might be an AggregateException now. ExtractSingleInnerException on `e`

2019-03-01 08:42 UTC, ppekrol commented on src/Raven.Server/Documents/PeriodicBackup/PeriodicBackupRunner.cs
> +                {
can we get AggregateException here now?

2019-03-01 10:57 UTC, karmeli87 commented
Actually it is worse.. each uploading thread must handle it's own exceptions, otherwise the process will crash.

2019-03-03 07:53 UTC, ayende commented on src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsGlacierClient.cs
> +            var response = client.PostAsync(url, content, CancellationToken).Result;
Need timeout configuration

2019-03-03 07:53 UTC, ayende commented on src/Raven.Server/Documents/PeriodicBackup/Aws/RavenAwsGlacierClient.cs
> +            Thread.Sleep(1000);
Let's add a log here

2019-03-03 09:51 UTC, karmeli87 commented
Closing this PR, since There is no added value of having the backups in a dedicated threads.

2019-03-03 09:51 UTC, closed without merging