RavenDB-12889 Provide the user to find an ongoing task by name
ravendb/ravendb pull request #8882
Opened 2019-03-06 12:18 UTC by efratshenhar

2019-03-06 14:14 UTC, maximburyak commented on src/Raven.Server/Web/System/OngoingTasksHandler.cs
> +                            var watcher = name != null ?
I noticed that we have a "taskName" query param for subscriptions, we should probably use the same param for all other tasks

2019-03-06 20:47 UTC, ayende requested changes

2019-03-06 20:47 UTC, ayende commented on src/Raven.Client/Documents/Operations/OngoingTasks/GetOngoingTaskInfoOperation.cs
> +                url = _taskName != null ? $"{node.Url}/databases/{node.Database}/task?name={_taskName}&type={_type}" : $"{node.Url}/databases/{node.Database}/task?key={_taskId}&type={_type}";
Can you break this on multiple lines?

2019-03-06 20:47 UTC, ayende commented on src/Raven.Server/Web/System/OngoingTasksHandler.cs
> +                throw new ArgumentException($"Query string key or name is mandatory, but wasn't specified.");
```suggestion
                throw new ArgumentException($"You must specify a query string argument of either 'key' or 'name' , but none was specified.");
```

2019-03-07 07:46 UTC, ppekrol commented on src/Raven.Client/Documents/Operations/OngoingTasks/GetOngoingTaskInfoOperation.cs
> +            _taskName = taskName;
assert that string is not null of whitespace

2019-03-07 07:46 UTC, ppekrol commented on src/Raven.Server/Web/System/OngoingTasksHandler.cs
> +                                record.ExternalReplications.Find(x => x.Name.Equals(name, StringComparison.InvariantCultureIgnoreCase))
`StringComparison.OridinalIgnoreCase`

2019-03-07 07:46 UTC, ppekrol commented on src/Raven.Server/Web/System/OngoingTasksHandler.cs
> +                                record.PeriodicBackups.Find(x => x.Name.Equals(name, StringComparison.InvariantCultureIgnoreCase))
`StringComparison.OridinalIgnoreCase`

2019-03-07 07:46 UTC, ppekrol commented on src/Raven.Server/Web/System/OngoingTasksHandler.cs
> +                                record.SqlEtls.Find(x => x.Name.Equals(name, StringComparison.InvariantCultureIgnoreCase))
`StringComparison.OridinalIgnoreCase`

2019-03-07 07:46 UTC, ppekrol commented on src/Raven.Server/Web/System/OngoingTasksHandler.cs
> +                                record.RavenEtls.Find(x => x.Name.Equals(name, StringComparison.InvariantCultureIgnoreCase))
`StringComparison.OridinalIgnoreCase`

2019-03-11 07:57 UTC, ppekrol approved these changes

2019-03-11 13:38 UTC, merged