RavenDB-13060
ravendb/ravendb pull request #8918
Opened 2019-03-12 14:12 UTC by aviv86

https://issues.hibernatingrhinos.com/issue/RavenDB-13060

2019-03-12 14:56 UTC, grisha-kotler requested changes

2019-03-12 14:56 UTC, grisha-kotler commented on src/Raven.Client/Util/JavascriptConversionExtensions.cs
>              public bool DoNotIgnore { get; set; }
private bool _doNotIgnore;

2019-03-12 14:56 UTC, grisha-kotler commented on src/Raven.Client/Util/JavascriptConversionExtensions.cs
> +            private int MinSuffixToNotIgnore { get; set; }
private int _minSuffixToNotIgnore ;

2019-03-13 11:54 UTC, ppekrol approved these changes

2019-03-13 11:56 UTC, merged