[WIP] RavenDB-10956 Support remove CV entries from a specific database
ravendb/ravendb pull request #8988
Opened 2019-03-21 18:39 UTC by karmeli87

The removal occurs in 2 phases.
First we send command for removal of specific CVs. Upon committing the command each node will strip those CVs from _outgoing_ replication. So the peers will not receive documents with those CVs.

Only when all outgoing connections of a node stripping those CVs the node will confirm the removal command.
In the second phase when all nodes confirmed the 1st phase it is safe to remove those CVs from the global database change vector.

2019-03-21 18:42 UTC, karmeli87 commented
This PR is still missing tests, but I would like to have comments about the logic.

2019-03-22 11:06 UTC, ayende requested changes
I don't follow why you are using the replication for that.

The flow that I had in mind was that you register the list of CV to filter.
You then immediately update the global change vector.
You then filter out this db ids whenever we generate a new CV.

The list of db ids to ignore is static and remains the same until admin edits it again.

Another possible impl is to just filter the change vectors at _global db cv time_, which is probably cheaper, but need some verification to see that it does the right thing.

2019-03-22 11:06 UTC, ayende commented on src/Raven.Client/ServerWide/DatabaseRecord.cs
> +    public class RemoveChangeVectors
Should be either nested class or a separate file

2019-03-22 11:06 UTC, ayende commented on src/Raven.Client/ServerWide/DatabaseRecord.cs
> +        public RemoveChangeVectors RemoveChangeVectors;
What if I have multiple removals?

2019-03-22 11:06 UTC, ayende commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +            ConfirmChangeVectorRemoval(newRecord);
Shouldn't we confirm anyway if we removed the ignored list? Or is it expected that this will be empty list, then?

2019-03-22 11:06 UTC, ayende commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +                        if (ReplicationLoader.OutgoingHandlers.Any() == false || ReplicationLoader.OutgoingHandlers.Min(h => h.RaftIndex) >= index)
I don't understand why you are involving the `OutgoingHandlers` here?
I think that I'm missing something here in terms of logical flow of the operation.

In terms of what is actually going on, the `OutgoingHandlers` may not contain tasks that have just been added (this can happen on db startup, mind) or tasks that failed.

2019-03-22 11:06 UTC, ayende commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +                                break;
You need cancellation tokens here, no?
Or is that handled internally?

2019-03-22 11:06 UTC, ayende commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +                    while (DatabaseShutdown.IsCancellationRequested == false)
Why is this a loop?

2019-03-22 11:06 UTC, ayende commented on src/Raven.Server/Documents/DocumentDatabase.cs
> +            //TODO: optimize this
Probably *rare* operation, don't really need to optimize it

2019-03-22 11:06 UTC, ayende commented on src/Raven.Server/Documents/DocumentsStorage.cs
> +                DocumentDatabase.RemoveIgnoredChangeVectors(_ignoredList, ref context.LastDatabaseChangeVector);
first use `context.LastDatabaseChangeVector = context.LastDatabaseChangeVector ?? GetDatabaseChangeVector()`

2019-03-22 11:06 UTC, ayende commented on src/Raven.Server/Documents/DocumentsStorage.cs
> +                    var tree = context.Transaction.InnerTransaction.ReadTree(GlobalTreeSlice);
I'm pretty sure we have `SaveDatabseChangeVector`, no? If no, create it, this leaks the storage abstraction

2019-03-22 11:06 UTC, ayende commented on src/Raven.Server/Documents/Replication/OutgoingReplicationHandler.cs
> +        public long RaftIndex;
I don't understand what is the purpose of this. 
This just tells you what is the last raft index that we sent this with, not whatever we properly updated anything internally about it.

Note that the `LastRaftCommitIndex` is updated *without* waiting for the commands to actually finish applying (async)

2019-04-02 14:29 UTC, ppekrol commented
Closing. Moved to 4.2.x

2019-04-02 14:29 UTC, closed without merging