RavenDB-13215: If db being deleted from group, display it as deleted …
ravendb/ravendb pull request #9060
Opened 2019-04-04 14:30 UTC by garayx

…only.

2019-04-04 14:34 UTC, grisha-kotler requested changes

2019-04-04 14:34 UTC, grisha-kotler commented on src/Raven.Studio/typescript/viewmodels/resources/manageDatabaseGroup.ts
> +            let nodeToDisplay = incomingDbInfo.nodes().filter(x => incomingDbInfo.deletionInProgress().indexOf(x.tag()) < 0);
const

2019-04-04 14:34 UTC, grisha-kotler requested changes

2019-04-04 14:34 UTC, grisha-kotler commented on src/Raven.Studio/typescript/viewmodels/resources/manageDatabaseGroup.ts
> +            let nodeToDisplay = incomingDbInfo.nodes().filter(x => incomingDbInfo.deletionInProgress().indexOf(x.tag()) < 0);
*nodesToDisplay

2019-04-04 14:35 UTC, grisha-kotler requested changes

2019-04-04 14:35 UTC, grisha-kotler commented on src/Raven.Studio/typescript/viewmodels/resources/manageDatabaseGroup.ts
> +        if (incomingDbInfo.deletionInProgress().length > 0) {
const deletionInProgress = incomingDbInfo.deletionInProgress();

2019-04-05 06:00 UTC, ml054 requested changes
we also have RavenDB-13089 which targets for 4.1, so the question is if we should PR this against 4.1 as well? Additionally I think this should be server side issue - not studio side - since currently you are filtering some state you get from server. Why can't we filter that on server side?

2019-04-07 14:46 UTC, garayx commented
will open a new PR with server side fix

2019-04-07 14:46 UTC, closed without merging