RavenDB-13434: Added SearchOperator parameter to IRavenQueryable's Se…
ravendb/ravendb pull request #9170
Opened 2019-04-21 20:16 UTC by maximburyak

…arch

2019-04-22 08:56 UTC, ayende requested changes

2019-04-22 08:56 UTC, ayende commented on src/Raven.Client/Documents/Linq/RavenQueryProviderProcessor.cs
> +                    throw new InvalidOperationException("Could not extract searchTemrs value from " + expression);
```suggestion
                    throw new InvalidOperationException("Could not extract searchTerms value from " + expression);
```

2019-04-22 08:56 UTC, ayende commented on src/Raven.Client/Documents/LinqExtensions.cs
>          public static IRavenQueryable<T> Search<T>(this IQueryable<T> self, Expression<Func<T, object>> fieldSelector, string searchTerms,
You need to create an overload here, not modify the method.
This is a backward compatability concern

2019-04-22 17:52 UTC, ppekrol commented
I've pushed some small adjustments. If this will go to 4.2 and as far as I understood this was the target, then we will not have any backward compatibility concerns here.

2019-04-22 18:03 UTC, ppekrol commented
4.2 PR: https://github.com/ravendb/ravendb/pull/9176

2019-04-23 05:58 UTC, ayende commented
This is important in v4.1, we have a customer that is being blocked by this.

2019-04-23 06:41 UTC, ppekrol approved these changes

2019-04-23 06:43 UTC, closed without merging

2019-04-23 06:45 UTC, ppekrol commented
Merged.