RavenDB-13512 : Restore doesn't restore the legacy counters
ravendb/ravendb pull request #9224
Opened 2019-05-05 12:40 UTC by aviv86

https://issues.hibernatingrhinos.com/issue/RavenDB-13512

2019-05-05 14:42 UTC, ayende approved these changes

2019-05-05 15:13 UTC, grisha-kotler approved these changes

2019-05-06 09:59 UTC, ppekrol requested changes

2019-05-06 09:59 UTC, ppekrol commented on src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
> +            options.OperateOnTypes |= DatabaseItemType.Counters;
This shouldn't be here

2019-05-07 09:40 UTC, aviv86 commented on src/Raven.Client/Documents/Smuggler/DatabaseSmuggler.cs
> +            options.OperateOnTypes |= DatabaseItemType.Counters;
removed

2019-05-07 09:48 UTC, ppekrol approved these changes

2019-05-07 11:53 UTC, merged