RavenDB-11909: Verify task are unchanged on DatabaseRecord update, verify CreateDatabaseOperation doesnt have tasks configurations
ravendb/ravendb pull request #9291
Opened 2019-05-21 13:20 UTC by garayx

2019-05-21 13:51 UTC, grisha-kotler requested changes

2019-05-21 13:51 UTC, grisha-kotler commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +                                            $"Cannot update {task} configuration with DatabaseRecord. Please use dedicated operation to update {task} configuration.");
```suggestion
                                            $"Cannot update {task} configuration with DatabaseRecord. Please use a dedicated operation to update the {task} configuration.");
```

2019-05-21 13:51 UTC, grisha-kotler commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +                                            $"Failed to create a new Database {addDatabaseCommand.Name}. Updating tasks configurations via DatabaseRecord is not supported, please use dedicated operat
```suggestion
                                            $"Failed to create a new Database {addDatabaseCommand.Name}. Updating tasks configurations via DatabaseRecord is not supported, please use a dedicated operation to update the {task} configuration.");
```

2019-05-22 12:35 UTC, garayx commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +                                            $"Cannot update {task} configuration with DatabaseRecord. Please use dedicated operation to update {task} configuration.");
done

2019-05-22 12:35 UTC, garayx commented on src/Raven.Server/ServerWide/ClusterStateMachine.cs
> +                                            $"Failed to create a new Database {addDatabaseCommand.Name}. Updating tasks configurations via DatabaseRecord is not supported, please use dedicated operat
done

2019-05-23 09:18 UTC, merged