RavenDB-13098 TimeSeries replication
ravendb/ravendb pull request #9598
Opened 2019-08-15 12:06 UTC by karmeli87

2019-08-18 15:07 UTC, ayende commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +                    // TODO: I guess we can do it more efficient
Yes, we can. We can create a dictionary to hold that and add to it, would be much faster

2019-08-18 15:07 UTC, ayende commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +                    // TODO: I guess we can do it more efficient
Remember that in 99% of cases, this is going to be a single one

2019-08-18 15:07 UTC, ayende commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +                        changes += group.Appendies.Count();
You are iterating the iterator again here

2019-08-19 09:09 UTC, karmeli87 commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +                    // TODO: I guess we can do it more efficient
So would make a sense to have a different code path for each case to avoid allocations?

2019-08-19 09:43 UTC, ayende commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +                    // TODO: I guess we can do it more efficient
I think so

2019-08-21 12:25 UTC, ayende requested changes

2019-08-21 12:25 UTC, ayende commented on src/Raven.Server/Documents/Handlers/BatchHandler.cs
> +            private readonly Dictionary<string, SortedList<long, AppendTimeSeriesOperation>> _appendDictionary;
This can be removed, no? It's always null

2019-08-21 12:25 UTC, ayende commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +                            kvp.Value.Values.Select(x =>
For perf, we probably want to do this without the lambda.

2019-08-21 12:25 UTC, ayende commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +                    IEnumerable<TimeSeriesStorage.Reader.SingleResult> Single(AppendTimeSeriesOperation element)
I don't really like this approach, can we accept `AppendTimeSeriesOperation` directly and convert internally?

2019-08-21 12:25 UTC, ayende commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +            public ExecuteTimeSeriesBatchCommand(DocumentDatabase database, DocumentTimeSeriesOperation batch, bool fromEtl, Dictionary<string, SortedList<long, AppendTimeSeriesOperation>> appendDict
`appendDictionary` is always null, can be removed.

2019-08-21 12:25 UTC, ayende commented on src/Raven.Server/Documents/Handlers/TimeSeriesHandler.cs
> +                    appendDictionary[item.Name] = sorted;
Add this in the `if` statement, instead

2019-08-21 13:18 UTC, ayende approved these changes

2019-08-23 07:55 UTC, merged