RavenDB-14036
ravendb/ravendb pull request #9702
Opened 2019-09-19 14:04 UTC by aviv86

fix JS projection of stored string field with value that 'looks' like a large number 
https://issues.hibernatingrhinos.com/issue/RavenDB-13973

2019-09-19 14:18 UTC, grisha-kotler requested changes

2019-09-19 14:18 UTC, grisha-kotler commented on src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
> +                if (f.Name == field + LuceneDocumentConverterBase.IsArrayFieldSuffix)
```suggestion
var arrayField = field + LuceneDocumentConverterBase.IsArrayFieldSuffix
                if (f.Name == arrayField)
```

2019-09-19 14:23 UTC, aviv86 commented on src/Raven.Server/Documents/Queries/Results/QueryResultRetrieverBase.cs
> +                if (f.Name == field + LuceneDocumentConverterBase.IsArrayFieldSuffix)
done

2019-09-19 16:11 UTC, grisha-kotler approved these changes

2019-09-22 13:31 UTC, ppekrol approved these changes

2019-09-22 15:45 UTC, merged